import { compileExpectedEdgeAlphaCandidate } from "../../../supabase/functions/_shared/evolution_candidates/expected-edge-alpha-expected-edge.ts";

const envelope = {
  sourceObservations: [
    {
      observationId: "o1",
      providerId: "p1",
      sensorFamily: "momentum",
      horizon: "300s",
      direction: "up",
      observedAt: "2026-09-13T12:00:00Z",
      cadenceSeconds: 300,
      evaluationStartAt: "2026-09-13T12:00:00Z",
      evaluationEndAt: "2026-09-13T12:05:00Z",
    },
    {
      observationId: "o2",
      providerId: "p2",
      sensorFamily: "breadth",
      horizon: "300s",
      direction: "up",
      observedAt: "2026-09-13T12:01:00Z",
      cadenceSeconds: 300,
      evaluationStartAt: "2026-09-13T12:01:00Z",
      evaluationEndAt: "2026-09-13T12:06:00Z",
    },
  ],
  reliabilitySnapshots: [
    {
      observationId: "o1",
      groupId: "g1",
      horizon: "300s",
      cadenceSeconds: 300,
      provenance: "reliability-a",
      snapshotAt: "2026-09-13T12:30:00Z",
      expectedMoveBps: 100,
      reliability: .8,
      uncertaintyBps: 5,
      mature: true,
    },
    {
      observationId: "o2",
      groupId: "g2",
      horizon: "300s",
      cadenceSeconds: 300,
      provenance: "reliability-b",
      snapshotAt: "2026-09-13T12:30:00Z",
      expectedMoveBps: 100,
      reliability: .8,
      uncertaintyBps: 5,
      mature: true,
    },
  ],
  cost: {
    asOf: "2026-09-13T12:45:00Z",
    spreadBps: 10,
    feeBps: 5,
    slippageBps: 5,
    fillability: 1,
    sourceId: "book-a",
    cadenceSeconds: 300,
  },
};

// This projection is intentionally hand-authored; it is not generated by the
// candidate compiler and is the replay contract for this immutable envelope.
const expectedProjection = {
  recommendation: "ALLOW_EDGE",
  eligible: true,
  expectedGrossMoveBps: 160,
  estimatedRoundTripCostBps: 20,
  uncertaintyPenaltyBps: 10,
  matureIndependentGroupCount: 2,
  supportingObservationIds: ["o1", "o2"],
  safety: {
    shadow_only: true,
    live_execution: false,
    canonical_mutation: false,
    promotionReady: false,
  },
} as const;

Deno.test("replay projection is unchanged by future evidence permutations", () => {
  const options = { decisionAt: "2026-09-13T13:00:00Z" };
  const baseline = compileExpectedEdgeAlphaCandidate(envelope, options);
  const projection = {
    recommendation: baseline.recommendation,
    eligible: baseline.eligible,
    expectedGrossMoveBps: baseline.expectedGrossMoveBps,
    estimatedRoundTripCostBps: baseline.estimatedRoundTripCostBps,
    uncertaintyPenaltyBps: baseline.uncertaintyPenaltyBps,
    matureIndependentGroupCount: baseline.matureIndependentGroupCount,
    supportingObservationIds: baseline.provenance.supportingObservationIds,
    safety: {
      shadow_only: baseline.shadow_only,
      live_execution: baseline.live_execution,
      canonical_mutation: baseline.canonical_mutation,
      promotionReady: baseline.promotionReady,
    },
  };
  if (JSON.stringify(projection) !== JSON.stringify(expectedProjection)) {
    throw new Error(`immutable replay mismatch: ${JSON.stringify(projection)}`);
  }
  const futures = [
    {
      observationId: "future",
      providerId: "p9",
      sensorFamily: "x",
      horizon: "300s",
      direction: "up",
      observedAt: "2026-09-14T00:00:00Z",
    },
    {
      observationId: "future-2",
      providerId: "p9",
      sensorFamily: "x",
      horizon: "300s",
      direction: "up",
      observedAt: "2026-09-15T00:00:00Z",
    },
  ];
  for (const sourceObservations of [futures, [...futures].reverse()]) {
    const result = compileExpectedEdgeAlphaCandidate({
      ...envelope,
      sourceObservations: [
        ...envelope.sourceObservations,
        ...sourceObservations,
      ],
    }, options);
    const project = (
      value: ReturnType<typeof compileExpectedEdgeAlphaCandidate>,
    ) => JSON.stringify({ ...value, futureTelemetry: undefined });
    if (
      project(result) !== project(baseline) ||
      result.futureTelemetry.futureEvidenceCount !== 2
    ) {
      throw new Error("future evidence contaminated replay");
    }
  }
});
