const API='https://qbcjuxhvhwagvqbjyemo.supabase.co/functions/v1/brian-control-center';
const KEY_STORAGE='mcp-dashboard-key-v1';
const REPORT_SEEN='mcp-last-report-id';
const TRADE_SEEN='mcp-last-trade-id';
let selectedCapital=1000;
let statusData=null;
let refreshTimer=null;

const $=id=>document.getElementById(id);
const money=(v,d=2)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+$':'-$'}${Math.abs(Number(v)).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d})}`:'—';
const moneyPlain=(v,d=2)=>Number.isFinite(Number(v))?`$${Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d})}`:'—';
const pct=v=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}%`:'—';
const fmtTime=value=>value?new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';
const fmtClock=value=>value?new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(value)):'—';
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),3200)}
function controlKey(){return localStorage.getItem(KEY_STORAGE)||''}
function setUnlocked(show){$('unlock').classList.toggle('show',show)}
function consumeSetupKey(){const hash=new URLSearchParams(location.hash.replace(/^#/,''));const key=hash.get('key');if(key&&key.startsWith('MCP-')){localStorage.setItem(KEY_STORAGE,key);history.replaceState(null,'',location.pathname+location.search);toast('Kontrol anahtarı bu cihazda kaydedildi.')}}

async function api(action,body={}){
  const key=controlKey();
  if(!key){setUnlocked(true);throw new Error('Kontrol anahtarı gerekli.');}
  const response=await fetch(API,{method:'POST',headers:{'content-type':'application/json','x-brian-dashboard-key':key},body:JSON.stringify({action,...body})});
  const data=await response.json().catch(()=>({status:'INVALID_RESPONSE'}));
  if(response.status===401){localStorage.removeItem(KEY_STORAGE);setUnlocked(true);throw new Error('Kontrol anahtarı geçersiz.');}
  if(!response.ok)throw new Error(data.error||data.status||`HTTP ${response.status}`);
  return data;
}

function normalizeCapital(value){const n=Number(value);if(!Number.isFinite(n)||n<=0||n>1000000)throw new Error('Bakiye 1 ile 1.000.000 USD arasında olmalı.');return Math.round(n*100)/100}
function setCapital(value){const n=normalizeCapital(value);selectedCapital=n;for(const id of ['capitalInput','settingsCapitalInput'])if($(id))$(id).value=String(n);document.querySelectorAll('.capital,.capitalSettings').forEach(btn=>btn.classList.toggle('active',Number(btn.dataset.capital)===n));}
function setPolicy(value){const policy=['BOTH','NATIVE','PROFIT'].includes(String(value))?String(value):'BOTH';for(const id of ['policyScope','settingsPolicyScope'])if($(id))$(id).value=policy;}
function selectedPolicy(){return $('settingsPolicyScope')?.value||$('policyScope')?.value||'BOTH'}
function currentPolicy(){return $('policyView').value||'PROFIT'}
function setPnlClass(el,value){el.classList.remove('pos','neg');if(Number(value)>0)el.classList.add('pos');if(Number(value)<0)el.classList.add('neg')}

function renderChart(points){const root=$('chart');if(!points?.length){root.innerHTML='<div class="chartEmpty">Session başladı; ilk yeni 5m tick bekleniyor.</div>';return;}const values=points.map(p=>Number(p.equity));let min=Math.min(...values),max=Math.max(...values);if(Math.abs(max-min)<1e-9){min-=1;max+=1;}const width=800,height=260,pad=14;const coords=values.map((v,i)=>{const x=points.length===1?width/2:pad+(width-2*pad)*i/(points.length-1);const y=height-pad-(height-2*pad)*(v-min)/(max-min);return [x,y]});const path=coords.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' ');const area=`${path} L${coords.at(-1)[0].toFixed(1)} ${height-pad} L${coords[0][0].toFixed(1)} ${height-pad} Z`;root.innerHTML=`<svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none"><defs><linearGradient id="equityGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2af0a3" stop-opacity=".28"/><stop offset="1" stop-color="#2af0a3" stop-opacity="0"/></linearGradient></defs>${[.2,.4,.6,.8].map(k=>`<line class="gridLine" x1="0" y1="${height*k}" x2="${width}" y2="${height*k}"/>`).join('')}<path class="equityFill" d="${area}"/><path class="equityLine" d="${path}"/></svg>`;$('chartNote').textContent=`${moneyPlain(values.at(-1))} · min ${moneyPlain(Math.min(...values))} · max ${moneyPlain(Math.max(...values))}`}

function renderTrades(trades){const tbody=$('tradeRows');if(!trades?.length){tbody.innerHTML='<tr><td colspan="9">Henüz allocation değişimi yok; Brian WAIT durumunda olabilir.</td></tr>';return;}tbody.innerHTML=trades.slice(0,40).map(t=>{const longish=t.action.includes('LONG')||t.action==='ADD';const cls=t.action==='CLOSE'||t.action.includes('SHORT')?'sell':longish?'buy':'neutral';const realized=t.realized_pnl==null?'—':money(t.realized_pnl);return `<tr><td>${fmtClock(t.observed_at)}</td><td><span class="tag ${cls}">${esc(t.action)}</span></td><td><b>${esc(t.symbol)}</b></td><td>${Number(t.price).toLocaleString('en-US',{maximumFractionDigits:8})}</td><td>${(Number(t.before_weight)*100).toFixed(1)}%</td><td>${(Number(t.after_weight)*100).toFixed(1)}%</td><td>${moneyPlain(t.notional_change)}</td><td>${moneyPlain(t.estimated_cost,3)}</td><td class="${Number(t.realized_pnl)>0?'pos':Number(t.realized_pnl)<0?'neg':''}">${realized}</td></tr>`}).join('')}
function renderPositions(positions){const root=$('positionList');if(!positions?.length){root.innerHTML='<div class="row"><div><div class="rtitle">Pozisyon yok</div><div class="rmeta">Brian şartlar oluşmadığı için WAIT ediyor olabilir.</div></div><span>—</span></div>';return;}root.innerHTML=positions.map(p=>`<div class="row"><div><div class="rtitle">${esc(p.symbol)} · ${esc(p.side)}</div><div class="rmeta">Weight ${(Number(p.weight)*100).toFixed(1)}% · Mark ${Number(p.mark_price).toLocaleString('en-US',{maximumFractionDigits:8})}</div></div><div class="amount">${moneyPlain(p.notional)}<div class="${Number(p.attributed_unrealized_pnl)>=0?'pos':'neg'}">${money(p.attributed_unrealized_pnl)}</div></div></div>`).join('')}
function renderCoins(coins){const root=$('coinList');if(!coins?.length){root.innerHTML='<div class="row"><div><div class="rtitle">Henüz attribution yok</div><div class="rmeta">Aktif pozisyon oluştuğunda coin bazında ayrışacak.</div></div><span>—</span></div>';return;}root.innerHTML=coins.slice(0,8).map(c=>`<div class="row"><div><div class="rtitle">${esc(c.symbol)}</div><div class="rmeta">Gross ${money(c.gross_pnl)} · Cost ${moneyPlain(c.allocated_cost,3)} · ${c.action_count} aksiyon</div></div><b class="${Number(c.net_pnl)>=0?'pos':'neg'}">${money(c.net_pnl)}</b></div>`).join('')}
function renderDecisions(decisions){const root=$('decisionList');if(!decisions?.length){root.innerHTML='<div class="row"><div><div class="rtitle">Yeni tick bekleniyor</div><div class="rmeta">Decision diagnostics burada görünecek.</div></div><span>—</span></div>';return;}root.innerHTML=decisions.slice(0,8).map(d=>{const top=d.top_candidates?.[0];const weights=Object.entries(d.target_weights||{}).filter(([,v])=>Math.abs(Number(v))>1e-12).map(([s,v])=>`${s} ${(Number(v)*100).toFixed(1)}%`).join(', ');return `<div class="row decision ${d.active?'active':''}"><div><div class="rtitle">${fmtClock(d.observed_at)} · ${d.active?'ACTIVE':'WAIT'}</div><div class="rmeta">${weights||'Target weight yok'}${top?`<br>Top edge: ${esc(top.symbol)} · raw ${Number(top.raw_edge).toFixed(5)} · uncertainty ${Number(top.uncertainty).toFixed(5)}`:''}</div></div><b class="${d.active?'pos':'amber'}">${d.active?'GO':'WAIT'}</b></div>`}).join('')}
function renderReports(reports){const root=$('reportList');if(!reports?.length){root.innerHTML='<div class="reportCard"><div class="rmeta">İlk otomatik rapor session başlangıcından yaklaşık 1 saat sonra burada oluşur. “Rapor Şimdi” ile anlık snapshot da alabilirsin.</div></div>';return;}root.innerHTML=reports.slice(0,12).map(r=>{const p=r.payload||{};return `<div class="reportCard"><div class="reportTop"><div><div class="rtitle">${esc(r.policy_kind)} · ${fmtTime(r.window_start)} → ${fmtTime(r.window_end)}</div><div class="rmeta">${r.telegram_sent?'Telegram ✓':r.telegram_attempted?'Telegram hata':'Telegram yapılandırılmadı'}</div></div><b class="${Number(p.net_pnl)>=0?'pos':'neg'}">${money(p.net_pnl)}</b></div><div class="reportGrid"><div class="reportMetric"><span class="mini">Gross</span><b>${money(p.gross_pnl)}</b></div><div class="reportMetric"><span class="mini">Cost</span><b>${moneyPlain(p.trading_cost)}</b></div><div class="reportMetric"><span class="mini">Win Rate</span><b>${Number(p.win_rate_pct||0).toFixed(1)}%</b></div><div class="reportMetric"><span class="mini">Actions</span><b>${p.action_count||0}</b></div><div class="reportMetric"><span class="mini">Max DD</span><b>${Number(p.max_drawdown_pct||0).toFixed(2)}%</b></div><div class="reportMetric"><span class="mini">Open</span><b>${p.open_positions?.length||0}</b></div></div></div>`}).join('')}

async function maybeNotify(data,snapshot){if(Notification.permission!=='granted'||!navigator.serviceWorker?.controller)return;const report=data.reports?.[0];const previousReport=localStorage.getItem(REPORT_SEEN);if(report?.report_id&&previousReport&&previousReport!==report.report_id){navigator.serviceWorker.controller.postMessage({type:'NOTIFY',title:'Monster Coins Pro · Saatlik Rapor',body:`${report.policy_kind}: ${money(report.payload?.net_pnl)} · ${report.payload?.action_count||0} aksiyon`,tag:`report-${report.report_id}`});}if(report?.report_id)localStorage.setItem(REPORT_SEEN,report.report_id);const trade=snapshot?.trades?.[0];const previousTrade=localStorage.getItem(TRADE_SEEN);if(trade?.id&&previousTrade&&previousTrade!==trade.id){navigator.serviceWorker.controller.postMessage({type:'NOTIFY',title:`${trade.symbol} · ${trade.action}`,body:`Notional ${moneyPlain(trade.notional_change)} · fiyat ${trade.price}`,tag:`trade-${trade.id}`});}if(trade?.id)localStorage.setItem(TRADE_SEEN,trade.id)}

function render(data){statusData=data;const session=data.session;const snap=data.policies?.[currentPolicy()]||null;const engine=data.engine||{};$('onlineText').textContent=engine.online?'ONLINE':'STALE';$('onlinePill').querySelector('.dot').classList.toggle('off',!engine.online);$('engineDotSide').classList.toggle('off',!engine.online);$('engineTextSide').textContent=engine.online?'Brian engine online':'Brian data stale';$('healthEngine').textContent=engine.online?'ONLINE':'STALE';$('healthEngine').className=engine.online?'pos':'neg';$('healthEngineMeta').textContent=engine.last_tick_at?`Son tick ${fmtTime(engine.last_tick_at)}`:'Tick yok';$('healthTick').textContent=engine.tick_age_seconds==null?'—':`${engine.tick_age_seconds}s`;$('healthTelegram').textContent=data.telegram?.configured?'READY':'PENDING';$('healthTelegram').className=data.telegram?.configured?'pos':'amber';
  if(!session){$('sessionBanner').textContent='SESSION YOK';$('sessionState').textContent='IDLE';$('sessionState').className='amber';$('sessionTimes').textContent='Start Shadow ile başlat';$('sessionPolicy').textContent='—';$('startBtn').disabled=false;$('restartBtn').disabled=false;$('pauseBtn').disabled=true;$('reportBtn').disabled=true;$('settingsStartBtn').disabled=false;$('settingsRestartBtn').disabled=false;$('settingsPauseBtn').disabled=true;['kpiEquity','kpiPnl','kpiWin','kpiBest'].forEach(id=>$(id).textContent='—');$('kpiPositions').textContent='0';$('kpiActions').textContent='0';renderChart([]);renderTrades([]);renderPositions([]);renderCoins([]);renderDecisions([]);renderReports([]);return;}
  if(session.policy_scope!=='BOTH'&&$('policyView').value!==session.policy_scope)$('policyView').value=session.policy_scope;const current=data.policies?.[currentPolicy()]||snap;$('sessionBanner').textContent=`${session.status} · $${Number(session.starting_equity).toLocaleString('en-US')}`;$('sessionState').textContent=session.status;$('sessionState').className=session.status==='RUNNING'?'pos':'amber';$('sessionTimes').textContent=`Başlangıç ${fmtTime(session.started_at)}${session.ended_at?` · Durdu ${fmtTime(session.ended_at)}`:''}`;$('sessionPolicy').textContent=session.policy_scope;$('startBtn').disabled=session.status==='RUNNING';$('restartBtn').disabled=false;$('pauseBtn').disabled=session.status!=='RUNNING';$('reportBtn').disabled=false;$('settingsStartBtn').disabled=session.status==='RUNNING';$('settingsRestartBtn').disabled=false;$('settingsPauseBtn').disabled=session.status!=='RUNNING';
  if(!current)return;$('kpiEquity').textContent=moneyPlain(current.current_equity);$('kpiEquityMeta').textContent=`Başlangıç ${moneyPlain(current.starting_equity)} · ${current.last_tick_at?fmtTime(current.last_tick_at):'yeni tick bekleniyor'}`;$('kpiPnl').textContent=money(current.session_pnl);setPnlClass($('kpiPnl'),current.session_pnl);$('kpiPnlMeta').textContent=`${pct(current.session_return_pct)} · gross ${money(current.gross_pnl)}`;$('kpiPositions').textContent=String(current.open_positions?.length||0);$('kpiPositionsMeta').textContent=(current.open_positions||[]).map(p=>p.symbol).join(' · ')||'WAIT';$('kpiWin').textContent=`${Number(current.win_rate_pct||0).toFixed(1)}%`;$('kpiWinMeta').textContent=`${current.wins||0} win / ${current.closed_action_count||0} kapanış`;$('kpiActions').textContent=String(current.action_count||0);const best=current.coin_attribution?.[0];$('kpiBest').textContent=best?.symbol||'—';$('kpiBestMeta').textContent=best?money(best.net_pnl):'attribution bekleniyor';setPnlClass($('kpiBestMeta'),best?.net_pnl||0);$('costTotal').textContent=moneyPlain(current.trading_cost);renderChart(current.equity_curve);renderTrades(current.trades);renderPositions(current.open_positions);renderCoins(current.coin_attribution);renderDecisions(current.decisions);renderReports(data.reports);maybeNotify(data,current).catch(()=>{});
}

async function refresh(silent=false){try{if(!silent)$('onlineText').innerHTML='<span class="spinner"></span>';const data=await api('status');render(data)}catch(error){$('healthApi').textContent='ERROR';$('healthApi').className='neg';if(!silent)toast(error.message)}finally{if(!$('onlineText').textContent)$('onlineText').textContent='CONNECTING'}}
async function start(){try{setCapital($('settingsCapitalInput')?.value||$('capitalInput').value);setPolicy(selectedPolicy());$('startBtn').disabled=true;$('settingsStartBtn').disabled=true;const result=await api('start',{starting_equity:selectedCapital,policy_scope:selectedPolicy()});toast(`Shadow session başladı · $${selectedCapital.toLocaleString('en-US')}`);await refresh(true);return result}catch(error){toast(error.message);$('startBtn').disabled=false;$('settingsStartBtn').disabled=false}}
async function restart(){try{setCapital($('settingsCapitalInput')?.value||$('capitalInput').value);setPolicy(selectedPolicy());if(!confirm(`Aktif/son session kapatılıp $${selectedCapital.toLocaleString('en-US')} ile yeni SHADOW session başlatılsın mı?`))return;$('restartBtn').disabled=true;$('settingsRestartBtn').disabled=true;const result=await api('restart',{starting_equity:selectedCapital,policy_scope:selectedPolicy()});toast(`Yeni SHADOW session · $${selectedCapital.toLocaleString('en-US')}`);await refresh(true);return result}catch(error){toast(error.message)}finally{$('restartBtn').disabled=false;$('settingsRestartBtn').disabled=false}}
async function pause(){try{$('pauseBtn').disabled=true;$('settingsPauseBtn').disabled=true;await api('pause');toast('Shadow session duraklatıldı.');await refresh(true)}catch(error){toast(error.message);$('pauseBtn').disabled=false;$('settingsPauseBtn').disabled=false}}
async function reportNow(){try{$('reportBtn').disabled=true;const r=await api('report_now');toast(r.status==='GENERATED'?'Rapor oluşturuldu.':'Rapor için veri yok.');await refresh(true)}catch(error){toast(error.message)}finally{$('reportBtn').disabled=false}}
async function enableNotifications(){if(!('Notification'in window)){toast('Bu cihaz bildirim API desteklemiyor.');return;}const permission=await Notification.requestPermission();toast(permission==='granted'?'Bildirimler açık.':'Bildirim izni verilmedi.');}

function bind(){
  document.querySelectorAll('.capital,.capitalSettings').forEach(btn=>btn.addEventListener('click',()=>{try{setCapital(btn.dataset.capital)}catch(error){toast(error.message)}}));
  for(const id of ['capitalInput','settingsCapitalInput'])$(id)?.addEventListener('change',e=>{try{setCapital(e.target.value)}catch(error){toast(error.message);setCapital(selectedCapital)}});
  $('policyScope').addEventListener('change',e=>setPolicy(e.target.value));$('settingsPolicyScope').addEventListener('change',e=>setPolicy(e.target.value));
  $('startBtn').addEventListener('click',start);$('settingsStartBtn').addEventListener('click',start);$('restartBtn').addEventListener('click',restart);$('settingsRestartBtn').addEventListener('click',restart);$('pauseBtn').addEventListener('click',pause);$('settingsPauseBtn').addEventListener('click',pause);$('reportBtn').addEventListener('click',reportNow);$('notifyBtn').addEventListener('click',enableNotifications);$('policyView').addEventListener('change',()=>statusData&&render(statusData));
  $('lockBtn').addEventListener('click',()=>{localStorage.removeItem(KEY_STORAGE);setUnlocked(true);toast('Kontrol anahtarı cihazdan silindi.');});
  $('unlockBtn').addEventListener('click',async()=>{const key=$('unlockKey').value.trim();if(!key)return;localStorage.setItem(KEY_STORAGE,key);setUnlocked(false);try{await refresh();$('unlockKey').value=''}catch{setUnlocked(true)}});$('unlockKey').addEventListener('keydown',e=>{if(e.key==='Enter')$('unlockBtn').click()});
  setCapital(selectedCapital);setPolicy('BOTH');
}
async function boot(){consumeSetupKey();bind();if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('/sw.js')}catch{}}if(!controlKey())setUnlocked(true);else{setUnlocked(false);await refresh();refreshTimer=setInterval(()=>refresh(true),30000)}}
boot();
