'use strict';
(()=>{
 const hero=document.getElementById('command');if(!hero||hero.querySelector('.nc'))return;
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const $=s=>hero.querySelector(s),state={selected:'world',paused:false,seen:{},view:null,inView:true};
 const labels={live:'Güncel',waiting:'Bekliyor',error:'Hata',unknown:'Veri yok',off:'Durduruldu'};
 const positions=[[14,17],[86,17],[14,49],[86,49],[14,81],[86,81]];
 const shapes='M146 32C129 10 104 15 91 30C67 24 44 40 44 60C23 66 17 85 25 105C11 124 21 149 38 157C36 178 57 192 76 187C89 209 118 211 145 188Z M154 32C171 10 196 15 209 30C233 24 256 40 256 60C277 66 283 85 275 105C289 124 279 149 262 157C264 178 243 192 224 187C211 209 182 211 155 188Z';
 function brain(){let mesh='',dots='';for(let y=26,row=0;y<206;y+=18,row++){for(let x=24,col=0;x<280;x+=20,col++){const xx=x+(row%2)*9,yy=y+Math.sin(col*1.7+row)*4;mesh+=`<path d="M${xx} ${yy}l20 ${Math.sin(col+row)*8}m-20 ${-Math.sin(col+row)*8}l${row%2?-9:9} 18"/>`;if((row+col)%3===0)dots+=`<circle cx="${xx}" cy="${yy}" r="${(row+col)%5===0?2.1:1.1}"/>`}}
 return `<svg class="nc-brain" viewBox="0 0 300 230" role="img" aria-label="Brian dijital sinir ağı görselleştirmesi"><defs><radialGradient id="ncBrainFill" cx="50%" cy="40%" r="70%"><stop stop-color="#354769"/><stop offset=".6" stop-color="#11273c"/><stop offset="1" stop-color="#0d172a"/></radialGradient><clipPath id="ncBrainClip"><path d="${shapes}"/></clipPath></defs><path class="nc-shell" d="${shapes}"/><g clip-path="url(#ncBrainClip)"><g class="nc-mesh">${mesh}</g><g class="nc-dot">${dots}</g><path d="M38 79L73 79 89 96 121 96 140 115M263 70L229 70 210 96 176 96 156 118M38 153L73 153 96 130 130 130M260 161L223 161 202 136 175 136" fill="none" stroke="#a0e9e1" stroke-width="1.5" opacity=".8"/></g><path d="M147 57V190M153 57V190" stroke="#b8b1ef" stroke-width="1" opacity=".7"/><circle cx="150" cy="115" r="5" fill="#cfedea"/><path d="M140 194L141 212H159L160 194" stroke="#9bc9db" fill="#122338"/></svg>`;
 }
 const css=document.createElement('link');css.rel='stylesheet';css.href='/brian-command.css?v=20260916-1';document.head.appendChild(css);
 const initial=BrianCommandModel.project(null).modules;
 const wrap=document.createElement('div');wrap.className='nc';wrap.innerHTML=`<header class="nc-head"><div><div class="nc-kicker">BRIAN / NEURAL COMMAND</div><h2>Brian çekirdeği</h2><div class="nc-mode" id="ncMode">Veri doğrulanıyor</div></div><button class="nc-motion" id="ncMotion" aria-label="Görsel hareketi durdur" aria-pressed="false">Ⅱ Hareket</button></header><div class="nc-stage"><div class="nc-floor" aria-hidden="true"></div><svg class="nc-lines" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-hidden="true">${initial.map((m,i)=>{const [x,y]=positions[i],d=`M${x*10} ${y*6} Q500 ${y*6} 500 276`;return `<path class="nc-wire" d="${d}"/><path class="nc-packet" data-packet="${m.key}" pathLength="1000" d="${d}"/>`}).join('')}</svg><div class="nc-ring" aria-hidden="true"></div><div class="nc-core">${brain()}<div class="nc-center-label">BRIAN</div><div class="nc-center-sub">DİJİTAL SİNİR AĞI</div></div>${initial.map((m,i)=>`<button class="nc-member" data-module="${m.key}" data-state="unknown" style="left:${positions[i][0]}%;top:${positions[i][1]}%" aria-pressed="${m.key===state.selected}"><i aria-hidden="true">${m.icon}</i><b>${m.name}</b><small>Veri yok</small></button>`).join('')}</div><section class="nc-detail" aria-label="Seçilen sistemin kanıtı"><div><b id="ncDetailName"></b><p id="ncDetailText"></p><small id="ncDetailStamp"></small></div><button id="ncOpen">Ayrıntıya git ↗</button></section><div class="nc-strip"><div class="nc-stat"><span id="ncCashLabel">Son kasa · SHADOW</span><b id="ncCash">—</b></div><div class="nc-stat"><span>Güncel bağlantı</span><b id="ncCount">— / 6</b></div><div class="nc-stat"><span id="ncAlphaLabel">Son ALPHA kararı</span><b id="ncAlpha">—</b></div></div><p class="nc-note">Halkalar ve zemin görsel atmosferdir. Hat üzerinde ışık yalnız yeni, güncel kayıtta akar. “Güncel”, sistemin çalışma kanıtıdır; kârlılık veya karar doğruluğu değildir.</p>`;hero.appendChild(wrap);hero.classList.add('nc-ready');
 // Preserve legacy render targets; stop their hidden SVG timelines.
 hero.querySelector('.flow-map')?.pauseAnimations?.();
 const hb=()=>{try{return typeof STABILITY!=='undefined'?STABILITY.heartbeat:null}catch{return null}};
 function update(){if(document.hidden||!state.inView)return;let rows=[],error=null;try{if(typeof moduleRows==='function')rows=moduleRows();if(typeof STABILITY!=='undefined')error=STABILITY.error}catch{error='STATE_UNAVAILABLE'}
 const v=BrianCommandModel.project(hb(),rows,error);state.view=v;
 $('#ncMode').textContent=!v.evidenceFresh?'Güncel heartbeat bekleniyor':!v.enabled?'Sistem durduruldu':v.transportDegraded?`Bağlantı yenileniyor · ${v.live} / 6 son sağlam kanıt`:`${v.live} / 6 bağlantıda güncel kanıt · ${new Date(v.heartbeatAt).toLocaleTimeString('tr-TR')}`;
 for(const m of v.modules){const b=$(`[data-module="${m.key}"]`);b.dataset.state=m.state;b.setAttribute('aria-pressed',String(m.key===state.selected));b.setAttribute('aria-label',`${m.name}: ${labels[m.state]}. Kanıt ayrıntısını göster`);b.querySelector('small').textContent=labels[m.state];const signature=m.stamp;const old=state.seen[m.key];if(old&&signature&&old!==signature&&m.state==='live'&&!state.paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches){for(const el of [b,$(`[data-packet="${m.key}"]`)]){el.classList.remove('arrival');void el.getBoundingClientRect();el.classList.add('arrival')}}state.seen[m.key]=signature;
 }
 const m=v.modules.find(x=>x.key===state.selected);$('#ncDetailName').textContent=m.name+' · '+labels[m.state];$('#ncDetailText').textContent=m.meta+(m.key==='behavior'?' Bu gösterge Dünya ve ALPHA kanıtlarından türetilir.':'');$('#ncDetailStamp').textContent='Son modül kaydı: '+(m.stamp&&Number.isFinite(Date.parse(m.stamp))?new Date(m.stamp).toLocaleString('tr-TR'):'bilinmiyor');
 $('#ncCashLabel').textContent=v.treasuryFresh?'Kasa · SHADOW':'Son kasa · güncel değil';$('#ncCash').textContent=v.equity===null?'—':new Intl.NumberFormat('tr-TR',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v.equity);$('#ncCount').textContent=(v.evidenceFresh?v.live:'—')+' / 6';
 $('#ncAlpha').textContent=({OPEN_LONG:'LONG adayı',OPEN_SHORT:'SHORT adayı',WAIT:'Bekle',VETO:'Veto',HOLD:'Tut'})[v.action]||v.action||'—';$('#ncAlphaLabel').textContent=v.modules.find(m=>m.key==='alpha').state==='live'?'ALPHA · son karar':'ALPHA · son kayıt';
 }
 wrap.addEventListener('click',e=>{const b=e.target.closest('[data-module]');if(b){state.selected=b.dataset.module;update()}});
 $('#ncMotion').onclick=()=>{state.paused=!state.paused;hero.classList.toggle('nc-paused',state.paused);$('#ncMotion').textContent=state.paused?'▶ Hareket':'Ⅱ Hareket';$('#ncMotion').setAttribute('aria-pressed',String(state.paused));$('#ncMotion').setAttribute('aria-label',state.paused?'Görsel hareketi aç':'Görsel hareketi durdur')};
 $('#ncOpen').onclick=()=>{if(state.selected==='treasury'&&typeof window.openTreasuryAccounting==='function'){window.openTreasuryAccounting();return}const targets={world:'worldPanel',behavior:'behaviorText',alpha:'alphaFeed',treasury:'treasuryLedger',research:'researchFeed',ocean:'moduleList'};const target=document.getElementById(targets[state.selected]);if(target){target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});target.setAttribute('tabindex','-1');target.focus({preventScroll:true})}};
 new IntersectionObserver(entries=>{state.inView=entries[0].isIntersecting;hero.classList.toggle('nc-away',!state.inView||document.hidden);if(state.inView)update()},{threshold:0}).observe(hero);
 document.addEventListener('visibilitychange',()=>{hero.classList.toggle('nc-away',document.hidden||!state.inView);if(!document.hidden)update()});
 update();setInterval(update,3000);
})();
