const API='https://qbcjuxhvhwagvqbjyemo.supabase.co/functions/v1/brian-control-center';
const KEY_STORAGE='mcp-dashboard-key-v1';
const REPORT_SEEN='mcp-report-seen-v2';
const TRADE_SEEN='mcp-trade-seen-v2';
const VIEW_STORAGE='mcp-dashboard-view-v4';
const $=id=>document.getElementById(id);
const $$=sel=>[...document.querySelectorAll(sel)];
let statusData=null;
let refreshTimer=null;
let deferredInstall=null;
let selectedCapital=Number(localStorage.getItem('mcp-shadow-capital-v2')||500);
let selectedPolicy=localStorage.getItem('mcp-shadow-policy-v2')||'BOTH';

const actionNames={OPEN_LONG:'LONG AÇ',OPEN_SHORT:'SHORT AÇ',WAIT:'BEKLE',VETO:'VETO',BUY:'AL',SELL:'SAT',HOLD:'TUT'};
const statusNames={RUNNING:'AKTİF',PAUSED:'DURAKLATILDI',ONLINE:'ÇEVRİMİÇİ',DEGRADED:'KISMİ',ERROR:'HATA',STALE:'GECİKMİŞ',SUCCESS:'SAĞLIKLI',FAILED:'HATA',IDLE:'BOŞTA',NO_DATA:'VERİ YOK',BROWSER_ACTIVE:'TARAYICI AKTİF',BROWSER_STOPPED:'TARAYICI DURDU'};
const groupNames={
  micro_velocity:'Mikro Hız',micro_volume:'Mikro Hacim',micro_breakout:'Mikro Kırılım',micro_reclaim:'Mikro Geri Alım',micro_taker_flow:'Mikro Taker Akışı',
  price_structure:'Fiyat Yapısı',price_momentum:'Fiyat Momentumu',price_mean_reversion:'Ortalamaya Dönüş',derivatives_taker:'Türev Taker Akışı',derivatives_oi:'Açık Pozisyon',derivatives_funding:'Funding',phase37_frozen_model:'Phase 3.7 Kontrol',intrabar_tape:'Intrabar Tape'
};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function num(v,d=2){const n=finite(v);return n==null?'—':n.toLocaleString('tr-TR',{maximumFractionDigits:d});}
function money(v){const n=finite(v);return n==null?'—':new Intl.NumberFormat('tr-TR',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);}
function signedMoney(v){const n=finite(v);if(n==null)return'—';return `${n>=0?'+':''}${money(n)}`;}
function pct(v,d=2){const n=finite(v);return n==null?'—':`${n>=0?'+':''}${n.toFixed(d)}%`;}
function bps(v,d=2){const n=finite(v);return n==null?'—':`${n>=0?'+':''}${n.toFixed(d)} bps`;}
function clock(v){if(!v)return'—';try{return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v));}catch{return'—';}}
function dateTime(v){if(!v)return'—';try{return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Berlin',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v));}catch{return'—';}}
function age(sec){const n=finite(sec);if(n==null)return'—';if(n<60)return`${Math.round(n)} sn`;if(n<3600)return`${Math.round(n/60)} dk`;return`${(n/3600).toFixed(n<7200?1:0)} sa`}
function sym(v){return String(v??'').replace(/^crypto:/,'');}
function actionTr(v){return actionNames[String(v)]||String(v||'—').replaceAll('_',' ');}
function statusTr(v){return statusNames[String(v)]||String(v||'—').replaceAll('_',' ');}
function policyTr(v){return v==='PROFIT'?'Kâr Modu':v==='NATIVE'?'Native Kontrol':'İkisi Birlikte';}
function groupTr(v){return groupNames[String(v)]||String(v||'—').replaceAll('_',' ');}
function actionClass(v){return v==='OPEN_LONG'||v==='BUY'?'long':v==='OPEN_SHORT'||v==='SELL'?'short':v==='VETO'?'veto':'wait';}
function stateTone(v){return ['ONLINE','SUCCESS','RUNNING','BROWSER_ACTIVE'].includes(v)?'ok':['DEGRADED','PAUSED','STALE','IDLE','NO_DATA'].includes(v)?'warn':'bad';}
function toast(message){const el=$('toast');if(!el)return;el.textContent=String(message);el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3200);}
function controlKey(){return(localStorage.getItem(KEY_STORAGE)||'').trim();}
function consumeSetupKey(){const h=location.hash||'';const m=h.match(/(?:^#|&)key=([^&]+)/);if(!m)return;try{const key=decodeURIComponent(m[1]);if(key)localStorage.setItem(KEY_STORAGE,key);}catch{}history.replaceState(null,'',location.pathname+location.search);}
function setUnlocked(show){$('unlock')?.classList.toggle('show',show);}
async function api(action,body={}){const key=controlKey();if(!key)throw Error('Kontrol anahtarı bulunamadı.');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','x-brian-dashboard-key':key},body:JSON.stringify({action,...body}),cache:'no-store'});let data={};try{data=await r.json();}catch{}if(!r.ok){if(r.status===401){localStorage.removeItem(KEY_STORAGE);setUnlocked(true);}throw Error(data.error||data.status||`HTTP ${r.status}`);}return data;}

function activateView(name,push=false){const allowed=new Set(['overview','alpha','learning','dip','system']);if(!allowed.has(name))name='overview';$$('[data-view-panel]').forEach(el=>el.classList.toggle('active',el.dataset.viewPanel===name));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===name));localStorage.setItem(VIEW_STORAGE,name);if(push){const u=new URL(location.href);if(name==='overview')u.searchParams.delete('view');else u.searchParams.set('view',name);history.replaceState(null,'',u);}window.scrollTo({top:0,behavior:'instant'});}
function bindNavigation(){$$('[data-view]').forEach(el=>el.addEventListener('click',()=>activateView(el.dataset.view,true)));}

function renderCloud(data){const bg=data.system?.background||{};const engine=data.engine||{};const alpha=data.alpha_v2||{};const mainOk=Boolean(bg.browser_independent&&bg.continues_when_page_closed&&(bg.overall==='ONLINE'||bg.overall==='DEGRADED')&&alpha.online);
  $('cloudStateText').textContent=mainOk?'BULUT AKTİF':statusTr(bg.overall||'STALE');
  $('cloudStateDot').className=`cc-dot ${mainOk?'ok':bg.overall==='DEGRADED'?'':'bad'}`;
  $('cloudStatePill').title=`MAIN/ALPHA tarayıcıdan bağımsız · ${bg.healthy_components??0}/${bg.total_components??0} bileşen`;
  $('backgroundTitle').textContent=mainOk?'Brian arka planda çalışıyor':'Brian bulut durumunu kontrol et';
  $('backgroundMeta').textContent=mainOk?'Bu sayfayı veya telefonu kapatsan da MAIN / ALPHA sunucu cronları çalışmaya devam eder. Dashboard yalnız izleme ve shadow oturum penceresidir.':`Cloud ${statusTr(bg.overall)} · ALPHA ${statusTr(alpha.status)} · son karar ${age(alpha.decision_age_seconds)} önce`;
  $('backgroundBadge').textContent=mainOk?'SUNUCU TARAFI':'KONTROL';$('backgroundBadge').className=`cc-badge ${mainOk?'ok':'warn'}`;
  $('bgComponentChip').textContent=`☁ ${bg.healthy_components??0}/${bg.total_components??0} servis sağlıklı`;
  $('bgAlphaChip').textContent=`α ALPHA: ${alpha.online?'canlı':'gecikmiş'}`;
  $('bgEngineChip').textContent=`◉ Phase 3.7: ${engine.online?'canlı':'gecikmiş'}`;
}
function setControlValues(){if($('capitalInput'))$('capitalInput').value=String(selectedCapital);if($('policyScope'))$('policyScope').value=selectedPolicy;}
function renderSession(data){const s=data.session;const running=s?.status==='RUNNING';$('startBtn').disabled=running;$('pauseBtn').disabled=!running;$('reportBtn').disabled=!s;$('restartBtn').disabled=false;
  if(!s){$('sessionState').textContent='Takip oturumu yok';$('sessionMeta').innerHTML='Brian cloud motoru yine de <b>arka planda çalışıyor</b>. İstersen performansı belirli bir sanal bakiye ile izlemek için oturum başlat.';return;}
  $('sessionState').textContent=`${statusTr(s.status)} · ${money(s.starting_equity)} · ${policyTr(s.policy_scope)}`;
  $('sessionMeta').innerHTML=`Başlangıç ${dateTime(s.started_at)}${s.ended_at?` · Duraklatma ${dateTime(s.ended_at)}`:''}<br><b>Not:</b> Bu yalnız takip penceresidir; duraklatmak MAIN/ALPHA cloud motorunu kapatmaz.`;
  if(s.policy_scope!=='BOTH'&&$('policyView'))$('policyView').value=s.policy_scope;
}
function currentPolicy(){const v=$('policyView')?.value||'ALPHA';return v==='NATIVE'?'NATIVE':v==='PROFIT'?'PROFIT':'ALPHA';}
function setOverviewLabels(alphaMode){
  const labels=['kpiEquity','kpiPnl','kpiPositions','kpiWin','kpiActions','kpiCost'];
  const alpha=['ALPHA Durumu','Yön Dağılımı','Açık Shadow Yön','Outcome Pozitif','ALPHA Aksiyon','Ort. Maliyet'];
  const legacy=['Shadow Bakiye','Oturum K/Z','Açık Pozisyon','Başarı Oranı','Shadow Aksiyon','İşlem Maliyeti'];
  labels.forEach((id,i)=>{const el=$(id)?.previousElementSibling;if(el)el.textContent=(alphaMode?alpha:legacy)[i];});
  const chart=$('equityChart')?.closest('.cc-card');if(chart){const title=chart.querySelector('.cc-card-title'),sub=chart.querySelector('.cc-card-sub');if(title)title.textContent=alphaMode?'ALPHA Karar Aktivitesi':'Shadow Equity';if(sub)sub.textContent=alphaMode?'Gerçek ALPHA directional-shadow state ve son karar akışı · direction-only/no notional':'Seçili takip modunun sanal bakiye eğrisi';}
  const pos=$('positionList')?.closest('.cc-card');if(pos){const sub=pos.querySelector('.cc-card-sub');if(sub)sub.textContent=alphaMode?'ALPHA position book · LONG/SHORT yön state':'Seçili takip modunun mevcut shadow pozisyonları';}
  const trades=$('tradeList')?.closest('.cc-card');if(trades){const sub=trades.querySelector('.cc-card-sub');if(sub)sub.textContent=alphaMode?'Son OPEN_LONG / OPEN_SHORT ALPHA kararları':'Telefon için yatay tablo yerine okunabilir kart akışı';}
}
function renderAlphaActivity(decisions,active){
  const root=$('equityChart');if(!root)return;const rows=(decisions||[]).slice(0,24).reverse();
  if(!rows.length){root.innerHTML='<div class="cc-chart-empty">ALPHA karar akışı bekleniyor.</div>';return;}
  const vals=rows.map(x=>Math.max(0,Number(x.evidence_score||0))),max=Math.max(.01,...vals),w=900,h=280,pad=18;
  const pts=vals.map((v,i)=>`${pad+(w-2*pad)*(vals.length===1?0:i/(vals.length-1))},${h-pad-(h-2*pad)*(v/max)}`).join(' ');
  root.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="ALPHA karar aktivitesi">${[.25,.5,.75].map(k=>`<line class="cc-gridline" x1="${pad}" x2="${w-pad}" y1="${h*k}" y2="${h*k}"/>`).join('')}<polyline class="cc-line" points="${pts}"/></svg><div class="cc-card-sub" style="padding-top:8px">${active.length} açık yön · ${rows.filter(d=>d.action==='OPEN_LONG'||d.action==='OPEN_SHORT').length} açma kararı / son ${rows.length}</div>`;
}
function renderAlphaOverview(data){
  setOverviewLabels(true);const a=data.alpha_v2||{},ds=a.decisions||[],ps=(a.positions||[]).filter(p=>Number(p.position)!==0),os=a.outcomes||[];
  const opens=ds.filter(d=>d.action==='OPEN_LONG'||d.action==='OPEN_SHORT'),longs=ps.filter(p=>Number(p.position)>0).length,shorts=ps.filter(p=>Number(p.position)<0).length;
  const resolved=os.filter(o=>Number.isFinite(Number(o.direction_adjusted_return))),positive=resolved.filter(o=>Number(o.direction_adjusted_return)>0).length,hit=resolved.length?100*positive/resolved.length:0;
  const costs=ds.map(d=>Number(d.estimated_round_trip_cost_bps)).filter(Number.isFinite),avgCost=costs.length?costs.reduce((s,x)=>s+x,0)/costs.length:null;
  $('kpiEquity').textContent=a.online?'ALPHA LIVE':statusTr(a.status||'STALE');$('kpiEquity').className=`cc-kpi-value ${a.online?'ok':'warn'}`;$('kpiEquityMeta').textContent=`Son karar ${age(a.decision_age_seconds)} önce · ${a.compiler_version||'compiler'}`;
  $('kpiPnl').textContent=`${longs} LONG / ${shorts} SHORT`;$('kpiPnl').className='cc-kpi-value';$('kpiPnlMeta').textContent='Direction-only shadow state · gerçek emir yok';
  $('kpiPositions').textContent=String(ps.length);$('kpiPositionsMeta').textContent=ps.slice(0,8).map(p=>sym(p.asset_id)).join(' · ')||'Açık yön yok';
  $('kpiWin').textContent=resolved.length?`${hit.toFixed(1)}%`:'—';$('kpiWinMeta').textContent=`${positive} pozitif / ${resolved.length} resolved prospective outcome`;
  $('kpiActions').textContent=String(opens.length);$('kpiActionsMeta').textContent=`OPEN_LONG/SHORT · son ${ds.length} ALPHA kararı`;
  $('kpiCost').textContent=avgCost==null?'—':`${avgCost.toFixed(1)} bps`;$('kpiCostMeta').textContent='Son kararların ortalama round-trip cost tahmini';
  renderAlphaActivity(ds,ps);
  $('positionList').innerHTML=ps.slice(0,16).map(p=>{const side=Number(p.position)>0?'LONG':'SHORT',entry=Number(p.entry_price),last=Number(p.last_reference_price),move=entry>0&&last>0?((last/entry-1)*10000*(Number(p.position)>0?1:-1)):null;return`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(sym(p.asset_id))} · ${side}</div><div class="cc-row-meta">Giriş ${num(p.entry_price,8)} · son ${num(p.last_reference_price,8)} · ${clock(p.last_action_at)}</div></div><div class="cc-row-side ${move==null?'':move>=0?'ok':'bad'}">${move==null?'—':bps(move)}</div></div>`}).join('')||'<div class="cc-row">ALPHA açık yön bekliyor.</div>';
  $('tradeList').innerHTML=opens.slice(0,18).map(d=>`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(sym(d.asset_id))} · <span class="cc-action ${actionClass(d.action)}">${esc(actionTr(d.action))}</span></div><div class="cc-row-meta">${clock(d.observed_at)} · fiyat ${num(d.observed_reference_price,8)} · skor ${num(d.evidence_score,4)}</div></div><div class="cc-row-side">${d.estimated_round_trip_cost_bps==null?'—':num(d.estimated_round_trip_cost_bps,1)+' bps'}</div></div>`).join('')||'<div class="cc-row">Son ALPHA penceresinde OPEN aksiyonu yok.</div>';
  renderReports(data.reports||[]);
}

function renderOverview(data){if(currentPolicy()==='ALPHA')return renderAlphaOverview(data);setOverviewLabels(false);const s=data.session;const snap=s?data.policies?.[currentPolicy()]||null:null;
  if(!snap){['kpiEquity','kpiPnl','kpiPositions','kpiWin','kpiActions','kpiCost'].forEach(id=>$(id).textContent='—');$('kpiEquityMeta').textContent='Takip oturumu başlatılmadı';$('kpiPnlMeta').textContent='—';$('kpiPositionsMeta').textContent='—';$('kpiWinMeta').textContent='—';$('kpiActionsMeta').textContent='—';$('kpiCostMeta').textContent='—';renderEquity([]);renderPositionList([]);renderTradeList([]);renderReports([]);return;}
  $('kpiEquity').textContent=money(snap.current_equity);$('kpiEquityMeta').textContent=`Başlangıç ${money(snap.starting_equity)} · ${snap.last_tick_at?clock(snap.last_tick_at):'tick bekleniyor'}`;
  $('kpiPnl').textContent=signedMoney(snap.session_pnl);$('kpiPnl').className=`cc-kpi-value ${Number(snap.session_pnl)>=0?'ok':'bad'}`;$('kpiPnlMeta').textContent=`Getiri ${pct(snap.session_return_pct)} · brüt ${signedMoney(snap.gross_pnl)}`;
  $('kpiPositions').textContent=String(snap.open_positions?.length||0);$('kpiPositionsMeta').textContent=(snap.open_positions||[]).map(p=>p.symbol).join(' · ')||'Açık pozisyon yok';
  $('kpiWin').textContent=`${Number(snap.win_rate_pct||0).toFixed(1)}%`;$('kpiWinMeta').textContent=`${snap.wins||0} kazanç / ${snap.closed_action_count||0} kapanış`;
  $('kpiActions').textContent=String(snap.action_count||0);$('kpiActionsMeta').textContent=`${policyTr(currentPolicy())} · shadow aksiyon`;
  $('kpiCost').textContent=money(snap.trading_cost);$('kpiCostMeta').textContent='Toplam model işlem maliyeti';
  renderEquity(snap.equity_curve||[]);renderPositionList(snap.open_positions||[]);renderTradeList(snap.trades||[]);renderReports(data.reports||[]);
}
function renderEquity(curve){const root=$('equityChart');if(!root)return;if(!curve?.length){root.innerHTML='<div class="cc-chart-empty">Takip oturumu başladıktan sonra equity eğrisi burada oluşur.</div>';return;}const pts=curve.map((p,i)=>({x:i,y:Number(p.equity??p.value??0)})).filter(p=>Number.isFinite(p.y));if(!pts.length){root.innerHTML='<div class="cc-chart-empty">Geçerli equity verisi yok.</div>';return;}const w=900,h=280,pad=18,min=Math.min(...pts.map(p=>p.y)),max=Math.max(...pts.map(p=>p.y)),span=Math.max(1e-9,max-min);const xy=pts.map((p,i)=>`${pad+(w-2*pad)*(pts.length===1?0:i/(pts.length-1))},${h-pad-(h-2*pad)*(p.y-min)/span}`).join(' ');const area=`${pad},${h-pad} ${xy} ${w-pad},${h-pad}`;root.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="Shadow equity grafiği"><defs><linearGradient id="ccEquityGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#31e6a0" stop-opacity=".25"/><stop offset="1" stop-color="#31e6a0" stop-opacity="0"/></linearGradient></defs>${[.25,.5,.75].map(k=>`<line class="cc-gridline" x1="${pad}" x2="${w-pad}" y1="${h*k}" y2="${h*k}"/>`).join('')}<polygon class="cc-area" points="${area}"/><polyline class="cc-line" points="${xy}"/></svg>`;}
function renderPositionList(rows){const root=$('positionList');if(!root)return;root.innerHTML=rows.length?rows.slice(0,12).map(p=>`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(p.symbol||sym(p.asset_id))} · ${esc(p.side||p.position_side||'AÇIK')}</div><div class="cc-row-meta">Giriş ${num(p.entry_price,8)} · Son ${num(p.current_price??p.last_price,8)}${p.opened_at?` · ${clock(p.opened_at)}`:''}</div></div><div class="cc-row-side ${Number(p.unrealized_pnl??0)>=0?'ok':'bad'}">${p.unrealized_pnl==null?'AÇIK':signedMoney(p.unrealized_pnl)}</div></div>`).join(''):'<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">Açık pozisyon yok</div><div class="cc-row-meta">Brian uygun sinyal gelene kadar bekliyor.</div></div></div>';}
function renderTradeList(rows){const root=$('tradeList');if(!root)return;root.innerHTML=rows.length?rows.slice(0,18).map(t=>`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(t.symbol||'—')} · <span class="cc-action ${actionClass(t.action)}">${esc(actionTr(t.action))}</span></div><div class="cc-row-meta">${clock(t.observed_at||t.ts)} · fiyat ${num(t.price,8)}${t.notional_change!=null?` · değişim ${money(t.notional_change)}`:''}</div></div><div class="cc-row-side ${Number(t.period_pnl??t.pnl??0)>=0?'ok':'bad'}">${t.period_pnl==null&&t.pnl==null?'—':signedMoney(t.period_pnl??t.pnl)}</div></div>`).join(''):'<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">Henüz shadow işlem yok</div><div class="cc-row-meta">İlk aksiyon burada görünecek.</div></div></div>';}
function renderReports(rows){const root=$('reportList');if(!root)return;root.innerHTML=rows.length?rows.slice(0,10).map(r=>{const p=r.payload||{};return`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${policyTr(r.policy_kind)} · ${clock(r.window_start)} → ${clock(r.window_end)}</div><div class="cc-row-meta">Brüt ${signedMoney(p.gross_pnl)} · maliyet ${money(p.trading_cost)} · başarı ${Number(p.win_rate_pct||0).toFixed(1)}% · ${r.telegram_sent?'Telegram gönderildi':'Dashboard raporu'}</div></div><div class="cc-row-side ${Number(p.net_pnl)>=0?'ok':'bad'}">${signedMoney(p.net_pnl)}</div></div>`}).join(''):'<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">Henüz rapor yok</div><div class="cc-row-meta">Otomatik saatlik raporlar veya “Rapor Oluştur” çıktısı burada görünür.</div></div></div>';}

function renderAlpha(data){const a=data.alpha_v2||{},ds=a.decisions||[],ps=a.positions||[],os=a.outcomes||[],cmp=a.phase37_comparisons||[];const active=ps.filter(p=>Number(p.position)!==0);const mix=ds.reduce((m,d)=>(m[d.action]=(m[d.action]||0)+1,m),{});
  $('alphaState').textContent=statusTr(a.status);$('alphaState').className=`cc-kpi-value ${a.online?'ok':'bad'}`;$('alphaStateMeta').textContent=`Son karar ${age(a.decision_age_seconds)} önce · ${a.compiler_version||'compiler'}`;
  $('alphaLastAction').textContent=actionTr(ds[0]?.action);$('alphaLastMeta').textContent=ds[0]?`${sym(ds[0].asset_id)} · score ${num(ds[0].evidence_score,4)} · ${clock(ds[0].observed_at)}`:'Karar yok';
  $('alphaPositions').textContent=String(active.length);$('alphaPositionsMeta').textContent=active.map(p=>sym(p.asset_id)).join(' · ')||'Yön açık değil';
  $('alphaMix').textContent=`${(mix.OPEN_LONG||0)+(mix.OPEN_SHORT||0)} / ${mix.WAIT||0} / ${mix.VETO||0}`;$('alphaMixMeta').textContent='AÇ / BEKLE / VETO · son 80 karar';
  $('alphaDecisionList').innerHTML=ds.slice(0,28).map(d=>`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(sym(d.asset_id))} · <span class="cc-action ${actionClass(d.action)}">${esc(actionTr(d.action))}</span></div><div class="cc-row-meta">${clock(d.observed_at)} · skor ${num(d.evidence_score,4)} · destek ${esc((d.support_groups||[]).map(groupTr).join(' + ')||'—')}<br>${esc(d.reason||d.veto_reason||'—')}</div></div><div class="cc-row-side">${d.estimated_round_trip_cost_bps==null?'maliyet —':num(d.estimated_round_trip_cost_bps,2)+' bps'}</div></div>`).join('')||'<div class="cc-row">ALPHA kararı yok.</div>';
  $('alphaPositionList').innerHTML=ps.slice(0,20).map(p=>{const side=Number(p.position)>0?'LONG':Number(p.position)<0?'SHORT':'FLAT';const move=Number(p.entry_price)>0&&Number(p.last_reference_price)>0?((Number(p.last_reference_price)/Number(p.entry_price)-1)*10000*(Number(p.position)||1)):null;return`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(sym(p.asset_id))} · ${side}</div><div class="cc-row-meta">Giriş ${num(p.entry_price,8)} · son ${num(p.last_reference_price,8)} · ${clock(p.last_action_at)}</div></div><div class="cc-row-side ${move==null?'':move>=0?'ok':'bad'}">${move==null?'—':bps(move)}</div></div>`}).join('')||'<div class="cc-row">ALPHA shadow position yok.</div>';
  $('alphaOutcomeList').innerHTML=os.slice(0,24).map(o=>`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(sym(o.asset_id))} · ${Number(o.horizon_seconds)/60} dk · ${esc(o.classification||'—')}</div><div class="cc-row-meta">Çözüldü ${clock(o.resolved_at)} · MFE ${bps(Number(o.mfe)*10000)} · MAE ${bps(Number(o.mae)*10000)}</div></div><div class="cc-row-side ${Number(o.direction_adjusted_return)>=0?'ok':'bad'}">${bps(Number(o.direction_adjusted_return)*10000)}</div></div>`).join('')||'<div class="cc-row">Outcome bekleniyor.</div>';
  $('phase37List').innerHTML=cmp.slice(0,16).map(c=>`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(sym(c.asset_id))} · ALPHA ${esc(actionTr(c.alpha_action))}</div><div class="cc-row-meta">Frozen ${esc(c.phase37_policy_kind||'—')} · yön ${num(c.phase37_direction,0)} · yaş ${age(c.phase37_age_seconds)} · ${esc(c.relationship||'—')}</div></div><div class="cc-row-side">${c.phase37_target_weight==null?'—':num(c.phase37_target_weight,4)}</div></div>`).join('')||'<div class="cc-row">Phase 3.7 karşılaştırma verisi yok.</div>';
}

function renderLearning(data){const l=data.system?.learning;if(!l){$('learningState').textContent='VERİ YOK';$('learningGroups').innerHTML='<div class="cc-row">Öğrenme durumu alınamadı.</div>';return;}const s=l.reliability_snapshot||{},f=l.feature_freeze||{},c=l.calibration||{};
  $('learningState').textContent='ÖLÇÜM MODU';$('learningStateMeta').textContent='Ağırlıklar hâlâ sabit 0.5 · ALPHA kararını değiştirmiyor';
  $('learnSnapshot').textContent=s.generated_at?dateTime(s.generated_at):'—';$('learnSnapshotMeta').textContent=`Pencere sonu ${dateTime(s.window_end)} · ${s.rows?.length||0} matris satırı`;
  $('learnCoverage').textContent=f.feature_coverage_pct==null?'—':`${f.feature_coverage_pct.toFixed(1)}%`;$('learnCoverageMeta').textContent=`Kaynak eşleşme ${f.source_match_pct==null?'—':f.source_match_pct.toFixed(1)+'%'} · son ${f.sampled_decisions||0} karar`;
  const hc=c.horizon_counts||{};$('learnCalibration').textContent=`${hc['300']||0} / ${hc['900']||0} / ${hc['3600']||0}`;$('learnCalibrationMeta').textContent='5 dk / 15 dk / 60 dk · son örneklem';
  const rows=s.rows||[];const byGroup=new Map();for(const r of rows){const key=r.independent_group;const prior=byGroup.get(key);if(Number(r.outcome_horizon_seconds)===900||!prior)byGroup.set(key,r);}const groups=[...byGroup.values()].sort((a,b)=>Number(b.sample_count)-Number(a.sample_count));
  $('learningGroups').innerHTML=groups.map(r=>{const hr=finite(r.bayesian_hit_rate_beta10_10);const width=hr==null?0:Math.max(2,Math.min(100,hr*100));return`<div class="cc-learning-row cc-card"><div class="cc-learning-top"><div><div class="cc-learning-name">${esc(groupTr(r.independent_group))}</div><div class="cc-card-sub">${esc(r.sensor_horizon)} · ${Number(r.outcome_horizon_seconds)/60} dk sonuç</div></div><span class="cc-badge">n=${r.sample_count}</span></div><div class="cc-progress"><i style="width:${width}%"></i></div><div class="cc-learning-metrics"><div class="cc-mini"><span>Bayes başarı</span><b>${hr==null?'—':(hr*100).toFixed(1)+'%'}</b></div><div class="cc-mini"><span>Medyan yön</span><b>${bps(r.median_signed_bps)}</b></div><div class="cc-mini"><span>Ort. yön</span><b>${bps(r.avg_signed_bps)}</b></div><div class="cc-mini"><span>Maliyet sonrası</span><b>${bps(r.avg_cost_adjusted_signed_bps)}</b></div></div></div>`}).join('')||'<div class="cc-row">Reliability snapshot bekleniyor.</div>';
  const cal=c.rows||[];const agg=new Map();for(const r of cal){const k=`${r.independent_group}|${r.outcome_horizon_seconds}`;const x=agg.get(k)||{g:r.independent_group,h:r.outcome_horizon_seconds,n:0,hits:0,sum:0};x.n++;if(r.realized_hit===true)x.hits++;x.sum+=Number(r.realized_sensor_signed_bps||0);agg.set(k,x);}const calRows=[...agg.values()].sort((a,b)=>b.n-a.n).slice(0,14);
  $('calibrationList').innerHTML=calRows.map(x=>`<div class="cc-row"><div class="cc-row-main"><div class="cc-row-title">${esc(groupTr(x.g))} · ${x.h/60} dk</div><div class="cc-row-meta">Prospective kalibrasyon · ${x.n} bağımsız observation</div></div><div class="cc-row-side">${x.n?((100*x.hits/x.n).toFixed(1)+'%'): '—'}<br><span class="${x.sum>=0?'ok':'bad'}">${bps(x.n?x.sum/x.n:null)}</span></div></div>`).join('')||'<div class="cc-row">Prospective outcome birikiyor.</div>';
}

function renderDip(data){const d=data.system?.dip||{};const state=d.status||'IDLE';$('dipState').textContent=statusTr(state);$('dipState').className=`cc-kpi-value ${state==='BROWSER_ACTIVE'?'ok':state==='PAUSED'||state==='IDLE'?'warn':'bad'}`;$('dipStateMeta').textContent=d.session_id?`Session ${d.session_id} · ${d.engine_version||'DIP'}`:'Aktif DIP session yok';
  $('dipEquity').textContent=d.snapshot?.equity==null?'—':money(d.snapshot.equity);$('dipEquityMeta').textContent=d.latest_snapshot_at?`Son snapshot ${dateTime(d.latest_snapshot_at)}`:'Snapshot yok';
  $('dipHeartbeat').textContent=d.heartbeat_age_seconds==null?'—':age(d.heartbeat_age_seconds);$('dipHeartbeatMeta').textContent=d.heartbeat_at?`Son tarayıcı heartbeat ${clock(d.heartbeat_at)}`:'Heartbeat yok';
  const box=$('dipBackgroundNote');if(d.browser_engine_required){box.className='cc-warning-box';box.innerHTML='<b>DIP ayrı bir motor:</b> mevcut V4/V5 piyasa streamleri tarayıcıya bağlı. Sayfayı kapatırsan DIP taraması durur; MAIN / ALPHA ise durmaz. Bu durum dashboardda artık gizlenmiyor.';}else{box.className='cc-safe-box';box.innerHTML='<b>DIP cloud runner aktif:</b> sayfa kapalıyken de çalışır.';}
}
function renderSystem(data){const bg=data.system?.background||{};const rows=bg.components||[];$('systemState').textContent=statusTr(bg.overall);$('systemState').className=`cc-kpi-value ${bg.overall==='ONLINE'?'ok':bg.overall==='DEGRADED'?'warn':'bad'}`;$('systemStateMeta').textContent=`${bg.healthy_components??0}/${bg.total_components??0} cloud bileşen · tarayıcıdan bağımsız`;
  $('apiState').textContent='BAĞLI';$('apiState').className='cc-kpi-value ok';$('apiStateMeta').textContent=`Control Center ${data.schema_version||'v3'} · ${dateTime(data.generated_at)}`;
  $('telegramState').textContent=data.telegram?.configured?'HAZIR':'KAPALI';$('telegramState').className=`cc-kpi-value ${data.telegram?.configured?'ok':'warn'}`;$('telegramStateMeta').textContent=data.telegram?.configured?'Saatlik rapor gönderimi yapılandırılmış':'Telegram secret yapılandırılmamış';
  $('safetyState').textContent=data.shadow_only&&!data.live_execution?'SHADOW':'KONTROL';$('safetyState').className=`cc-kpi-value ${data.shadow_only&&!data.live_execution?'ok':'bad'}`;$('safetyStateMeta').textContent='Gerçek emir yüzeyi yok · live_execution=false';
  $('componentList').innerHTML=rows.map(r=>{const tone=stateTone(r.state);return`<div class="cc-component"><span class="cc-dot ${tone==='ok'?'ok':tone==='bad'?'bad':''}"></span><div><div class="cc-component-name">${esc(r.label)}</div><div class="cc-component-meta">${esc(r.id)} · son ${age(r.age_seconds)} önce${r.error_message?` · ${esc(r.error_message).slice(0,90)}`:''}</div></div><div class="cc-component-state ${tone}">${esc(statusTr(r.state))}</div></div>`}).join('')||'<div class="cc-row">Collector heartbeat alınamadı.</div>';
}

async function maybeNotify(data,snapshot){if(!('Notification'in window)||Notification.permission!=='granted'||!navigator.serviceWorker?.controller)return;const report=data.reports?.[0],prevReport=localStorage.getItem(REPORT_SEEN);if(report?.report_id&&prevReport&&prevReport!==report.report_id){navigator.serviceWorker.controller.postMessage({type:'NOTIFY',title:'Brian · Saatlik Shadow Rapor',body:`${policyTr(report.policy_kind)}: ${signedMoney(report.payload?.net_pnl)} · ${report.payload?.action_count||0} aksiyon`,tag:`report-${report.report_id}`});}if(report?.report_id)localStorage.setItem(REPORT_SEEN,report.report_id);const trade=snapshot?.trades?.[0],prevTrade=localStorage.getItem(TRADE_SEEN);if(trade?.id&&prevTrade&&prevTrade!==trade.id){navigator.serviceWorker.controller.postMessage({type:'NOTIFY',title:`${trade.symbol} · ${actionTr(trade.action)}`,body:`Fiyat ${num(trade.price,8)} · shadow`,tag:`trade-${trade.id}`});}if(trade?.id)localStorage.setItem(TRADE_SEEN,trade.id);}
function render(data){statusData=data;renderCloud(data);renderSession(data);renderOverview(data);renderAlpha(data);renderLearning(data);renderDip(data);renderSystem(data);const snap=data.session?data.policies?.[currentPolicy()]||null:null;maybeNotify(data,snap).catch(()=>{});}
async function refresh(silent=false){try{if(!silent){$('cloudStateText').innerHTML='<span class="cc-spinner"></span>';}const data=await api('status');render(data);$('lastSync').textContent=`Son yenileme ${clock(data.generated_at)}`;}catch(e){$('cloudStateText').textContent='BAĞLANTI HATASI';$('cloudStateDot').className='cc-dot bad';$('apiState')&&($('apiState').textContent='HATA');if(!silent)toast(e.message||e);}}

function syncCapital(v){const n=Number(v);if(!Number.isFinite(n)||n<=0||n>1_000_000)throw Error('Sanal bakiye 0 ile 1.000.000 USD arasında olmalı.');selectedCapital=n;localStorage.setItem('mcp-shadow-capital-v2',String(n));setControlValues();}
function syncPolicy(v){if(!['BOTH','NATIVE','PROFIT'].includes(v))v='BOTH';selectedPolicy=v;localStorage.setItem('mcp-shadow-policy-v2',v);setControlValues();}
async function startTracking(){try{syncCapital($('capitalInput').value);syncPolicy($('policyScope').value);$('startBtn').disabled=true;await api('start',{starting_equity:selectedCapital,policy_scope:selectedPolicy});toast('Shadow takip oturumu başladı. Brian cloud motoru sayfa kapansa da çalışır.');await refresh(true);}catch(e){toast(e.message||e);$('startBtn').disabled=false;}}
async function restartTracking(){try{syncCapital($('capitalInput').value);syncPolicy($('policyScope').value);if(!confirm(`${money(selectedCapital)} ile yeni shadow takip oturumu başlatılsın mı? Cloud motor kapanmayacak; yalnız takip penceresi sıfırlanacak.`))return;$('restartBtn').disabled=true;await api('restart',{starting_equity:selectedCapital,policy_scope:selectedPolicy});toast('Yeni takip oturumu başladı.');await refresh(true);}catch(e){toast(e.message||e);}finally{$('restartBtn').disabled=false;}}
async function pauseTracking(){try{$('pauseBtn').disabled=true;await api('pause');toast('Takip oturumu duraklatıldı. MAIN / ALPHA arka planda çalışmaya devam ediyor.');await refresh(true);}catch(e){toast(e.message||e);$('pauseBtn').disabled=false;}}
async function reportNow(){try{$('reportBtn').disabled=true;const r=await api('report_now');toast(r.status==='GENERATED'?'Anlık shadow raporu oluşturuldu.':'Rapor için yeni veri yok.');await refresh(true);}catch(e){toast(e.message||e);}finally{$('reportBtn').disabled=false;}}
async function enableNotifications(){if(!('Notification'in window)){toast('Bu cihaz tarayıcı bildirimi desteklemiyor.');return;}const p=await Notification.requestPermission();toast(p==='granted'?'Cihaz bildirimleri açıldı.':'Bildirim izni verilmedi.');}
async function installApp(){if(!deferredInstall){toast('Ana ekrana eklemek için tarayıcı paylaş/menü seçeneklerini kullanabilirsin.');return;}deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('installBtn').classList.add('hidden');}
function bind(){bindNavigation();$('capitalInput').addEventListener('change',e=>{try{syncCapital(e.target.value)}catch(err){toast(err.message);setControlValues();}});$('policyScope').addEventListener('change',e=>syncPolicy(e.target.value));$('policyView').addEventListener('change',()=>statusData&&renderOverview(statusData));$('startBtn').addEventListener('click',startTracking);$('restartBtn').addEventListener('click',restartTracking);$('pauseBtn').addEventListener('click',pauseTracking);$('reportBtn').addEventListener('click',reportNow);$('notifyBtn').addEventListener('click',enableNotifications);$('installBtn').addEventListener('click',installApp);$('reloadBtn').addEventListener('click',()=>refresh(false));$('lockBtn').addEventListener('click',()=>{localStorage.removeItem(KEY_STORAGE);setUnlocked(true);toast('Kontrol anahtarı bu cihazdan silindi.');});$('unlockBtn').addEventListener('click',async()=>{const key=$('unlockKey').value.trim();if(!key)return;localStorage.setItem(KEY_STORAGE,key);setUnlocked(false);try{await refresh();$('unlockKey').value='';}catch{setUnlocked(true);}});$('unlockKey').addEventListener('keydown',e=>{if(e.key==='Enter')$('unlockBtn').click();});setControlValues();window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').classList.remove('hidden');});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&controlKey())refresh(true);});window.addEventListener('online',()=>controlKey()&&refresh(true));}
async function boot(){consumeSetupKey();bind();if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('/sw.js')}catch{}}const queryView=new URL(location.href).searchParams.get('view');activateView(queryView||localStorage.getItem(VIEW_STORAGE)||'overview',false);if(!controlKey()){setUnlocked(true);return;}setUnlocked(false);await refresh();refreshTimer=setInterval(()=>refresh(true),30000);}
boot();
