const API='https://qbcjuxhvhwagvqbjyemo.supabase.co/functions/v1/brian-dip-trader';
const KEY='mcp-dashboard-key-v1', ET='mcp-dip-engine-token-v1';
const COINS=['ETHUSDT','XRPUSDT','SOLUSDT','BNBUSDT','DOGEUSDT','ADAUSDT'];
const $=id=>document.getElementById(id), N=v=>Number(v), iso=()=>new Date().toISOString();
const price=v=>{v=N(v);if(!Number.isFinite(v))return'—';let d=v>=1000?2:v>=100?3:v>=1?4:v>=.1?5:7;return v.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d})};
const cash=v=>Number.isFinite(N(v))?`$${N(v).toFixed(2)}`:'—', pnl=v=>Number.isFinite(N(v))?`${N(v)>=0?'+':''}$${N(v).toFixed(3)}`:'—';
const clock=v=>v?new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v)):'—';
let session=null, running=false, sid=null, history=[], selected='ETHUSDT', ws=null, lastWs=0, persist=Promise.resolve();
const candles={}, live={}, states={};
let book={start:500,cash:500,realized:0,trades:0,wins:0,losses:0,cfg:null};
const fresh=s=>({symbol:s,peak:null,dip:null,armed:false,pos:null,last:null,lastAction:'FLAT',realized:0,drop:0,rebound:0,score:0,lastDipLog:null});
COINS.forEach(s=>states[s]=fresh(s));
function toast(t){let e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),3200)}
function token(){let t=localStorage.getItem(ET);if(!t){t=`dip-${crypto.randomUUID()}-${crypto.randomUUID()}`;localStorage.setItem(ET,t)}return t}
function unlock(show){$('unlock').classList.toggle('show',show)}
function dashboardKey(){return localStorage.getItem(KEY)||''}
async function api(action,body={}){let k=dashboardKey();if(!k){unlock(true);throw Error('Dashboard anahtarı gerekli.')}let r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','x-brian-dashboard-key':k},body:JSON.stringify({action,...body})}),d=await r.json().catch(()=>({}));if(r.status===401&&String(d.error||'').includes('UNAUTHORIZED_DASHBOARD')){localStorage.removeItem(KEY);unlock(true)}if(!r.ok)throw Error(d.error||d.status||`HTTP ${r.status}`);return d}
function cfgUi(){let sy=[...document.querySelectorAll('.symbolToggle.active')].map(x=>x.dataset.symbol);if(!sy.length)throw Error('En az bir coin seç.');let c={symbols:sy,interval:'1m',step_pct:N($('stepPctInput').value),dip_trigger_steps:N($('dipTriggerInput').value),rebound_steps:N($('reboundInput').value),take_profit_steps:N($('takeProfitInput').value),max_chase_steps:N($('maxChaseInput').value),fee_bps:N($('feeInput').value),slippage_bps:N($('slippageInput').value),engine_version:'aggressive-dip-v1'};if(c.step_pct<=0||c.rebound_steps<=0||c.take_profit_steps<=0)throw Error('Kademe değerleri 0’dan büyük olmalı.');if(c.max_chase_steps<=c.rebound_steps)throw Error('Ani sıçrama limiti alış reboundundan büyük olmalı.');return c}
function params(){let starting_equity=N($('capitalInput').value),trade_notional=N($('tradeInput').value);if(!(starting_equity>0)||trade_notional<=0||trade_notional>starting_equity)throw Error('Kasa / işlem limiti geçersiz.');return{starting_equity,trade_notional,config:cfgUi(),engine_token:token()}}
function reset(start,cfg){book={start,cash:start,realized:0,trades:0,wins:0,losses:0,cfg};COINS.forEach(s=>states[s]=fresh(s))}
function metrics(){let eq=book.cash,un=0,open=0,c=book.cfg||cfgUi(),fee=N(c.fee_bps||0)/1e4,slip=N(c.slippage_bps||0)/1e4;for(let s of COINS){let st=states[s];if(!st.pos)continue;open++;let m=N(st.last||live[s]||st.pos.entry),pro=st.pos.qty*m*(1-slip),net=pro-pro*fee;eq+=net;un+=net-(st.pos.notional+st.pos.entryFee)}return{equity:eq,unrealized:un,open,returnPct:book.start?100*(eq/book.start-1):0}}
function score(st){if(!st.armed&&!st.pos)return 0;return Math.min(100,Math.round(8+Math.min(45,st.drop*9)+Math.min(35,Math.max(0,st.rebound)*12)))}
function event(kind,sym,p,extra={}){let st=sym?states[sym]:null,m=metrics(),e={event_id:`dip-${crypto.randomUUID()}`,session_id:sid,observed_at:iso(),event_kind:kind,symbol:sym||null,price:Number.isFinite(N(p))?N(p):null,dip_low:st?.dip??null,entry_price:extra.entry_price??st?.pos?.entry??null,exit_price:extra.exit_price??null,quantity:extra.quantity??st?.pos?.qty??null,notional:extra.notional??st?.pos?.notional??null,fees:extra.fees??null,realized_pnl:extra.realized_pnl??null,cash_after:book.cash,equity_after:m.equity,metadata:extra.metadata||{}};history=[e,...history].slice(0,160);renderLog();draw();if(running&&sid)persist=persist.then(()=>api('event',{session_id:sid,engine_token:token(),...e}).catch(engineErr));return e}
function engineErr(e){let t=String(e?.message||e);if(/UNAUTHORIZED_DIP_ENGINE|STALE_DIP_SESSION|DIP_SESSION_PAUSED/.test(t)){running=false;toast('Dip motoru bu cihazda durdu.')}else{$('cloudState').textContent='ERROR';$('cloudState').className='neg';$('cloudMeta').textContent=t.slice(0,90)}render()}
function buy(st,p){let c=book.cfg,not=N(session?.trade_notional||$('tradeInput').value),fee=N(c.fee_bps)/1e4,slip=N(c.slippage_bps)/1e4,fill=p*(1+slip),entryFee=not*fee,total=not+entryFee;if(book.cash<total){event('NO_CASH',st.symbol,p,{metadata:{available:book.cash,required:total}});st.armed=false;st.peak=p;return}let qty=not/fill;book.cash-=total;st.pos={entry:fill,qty,notional:not,entryFee,at:iso(),dip:st.dip,target:fill*(1+N(c.take_profit_steps)*N(c.step_pct)/100)};st.lastAction='LONG';st.score=score(st);event('BUY',st.symbol,p,{entry_price:fill,quantity:qty,notional:not,fees:entryFee,metadata:{dip_low:st.dip,rebound_steps:st.rebound,target_price:st.pos.target,dip_score:st.score}});render()}
function sell(st,p){let q=st.pos;if(!q)return;let c=book.cfg,fee=N(c.fee_bps)/1e4,slip=N(c.slippage_bps)/1e4,fill=p*(1-slip),gross=q.qty*fill,exitFee=gross*fee,net=gross-exitFee,r=net-(q.notional+q.entryFee);book.cash+=net;book.realized+=r;book.trades++;r>=0?book.wins++:book.losses++;st.realized+=r;st.pos=null;st.armed=false;st.peak=p;st.dip=p;st.drop=st.rebound=st.score=0;st.lastAction='SOLD';event('SELL',st.symbol,p,{entry_price:q.entry,exit_price:fill,quantity:q.qty,notional:q.notional,fees:q.entryFee+exitFee,realized_pnl:r,metadata:{dip_low_at_entry:q.dip,entry_at:q.at}});render()}
function tick(sym,p){p=N(p);if(!(p>0))return;live[sym]=p;let st=states[sym];st.last=p;if(!running||!sid||!book.cfg.symbols.includes(sym))return;let c=book.cfg,step=N(c.step_pct)/100;if(st.pos){st.rebound=(p-st.pos.entry)/(st.pos.entry*step);st.score=score(st);if(st.rebound>=N(c.take_profit_steps))sell(st,p);return}if(st.peak==null){st.peak=st.dip=p;return}if(!st.armed){if(p>st.peak)st.peak=p;st.drop=(st.peak-p)/(st.peak*step);if(st.drop>=N(c.dip_trigger_steps)){st.armed=true;st.dip=p;st.lastDipLog=p;st.rebound=0;st.lastAction='HUNT';st.score=score(st);event('DIP_ARMED',sym,p,{metadata:{peak:st.peak,drop_steps:st.drop,dip_score:st.score}})}return}if(p<st.dip){let prev=st.lastDipLog||st.dip;st.dip=p;st.drop=(st.peak-p)/(st.peak*step);st.rebound=0;st.score=score(st);if((prev-p)/(prev*step)>=.25){st.lastDipLog=p;event('DIP_NEW_LOW',sym,p,{metadata:{drop_steps:st.drop,dip_score:st.score}})}return}st.rebound=(p-st.dip)/(st.dip*step);st.score=score(st);if(st.rebound>=N(c.max_chase_steps)){event('SKIP_CHASE',sym,p,{metadata:{dip_low:st.dip,rebound_steps:st.rebound,dip_score:st.score}});st.armed=false;st.peak=st.dip=p;st.lastAction='SKIP';st.score=0;render();return}if(st.rebound>=N(c.rebound_steps))buy(st,p)}
async function snapshot(){if(!running||!sid)return;let m=metrics(),state={startingEquity:book.start,cash:book.cash,realizedPnl:book.realized,tradeCount:book.trades,winCount:book.wins,lossCount:book.losses,config:book.cfg,symbols:states};try{await api('snapshot',{session_id:sid,engine_token:token(),observed_at:iso(),cash:book.cash,equity:m.equity,realized_pnl:book.realized,unrealized_pnl:m.unrealized,trade_count:book.trades,win_count:book.wins,loss_count:book.losses,state});$('cloudState').textContent='SYNC';$('cloudState').className='pos';$('cloudMeta').textContent=`Snapshot ${clock(new Date())}`}catch(e){engineErr(e)}}
function restore(d){session=d.session;if(!session){sid=null;running=false;reset(N($('capitalInput').value),cfgUi());history=[];return}sid=session.session_id;let c=session.config||cfgUi();book.cfg=c;$('capitalInput').value=session.starting_equity;$('tradeInput').value=session.trade_notional;for(let [id,k] of Object.entries({stepPctInput:'step_pct',dipTriggerInput:'dip_trigger_steps',reboundInput:'rebound_steps',takeProfitInput:'take_profit_steps',maxChaseInput:'max_chase_steps',feeInput:'fee_bps',slippageInput:'slippage_bps'}))if(c[k]!=null)$(id).value=c[k];document.querySelectorAll('.symbolToggle').forEach(b=>b.classList.toggle('active',c.symbols.includes(b.dataset.symbol)));let z=d.snapshot;if(z?.state?.symbols){reset(N(session.starting_equity),c);book.cash=N(z.cash);book.realized=N(z.realized_pnl);book.trades=N(z.trade_count);book.wins=N(z.win_count);book.losses=N(z.loss_count);for(let s of COINS)if(z.state.symbols[s])states[s]={...fresh(s),...z.state.symbols[s],symbol:s}}else reset(N(session.starting_equity),c);history=d.events||[]}
async function status(initial=false){try{let d=await api('status');restore(d);if(session?.status==='RUNNING'){try{await api('engine_check',{session_id:sid,engine_token:token()});running=true}catch{running=false}}else running=false;$('cloudState').textContent='ONLINE';$('cloudState').className='pos';render();if(initial)toast('Dip Trader hazır.')}catch(e){engineErr(e);if(initial)toast(String(e.message||e))}}
async function start(restart=false){try{let p=params(),d=await api(restart?'restart':'start',p);session={session_id:d.session_id,status:'RUNNING',started_at:iso(),starting_equity:d.starting_equity,trade_notional:d.trade_notional,config:d.config};sid=d.session_id;reset(d.starting_equity,d.config);history=[];running=true;event('ENGINE_START',null,null,{metadata:{starting_equity:d.starting_equity,trade_notional:d.trade_notional,config:d.config}});await snapshot();render();toast(restart?'Yeni ayrı dip kasası açıldı.':'Aggressive Dip Trader başladı.')}catch(e){toast(String(e.message||e))}}
async function pause(){try{if(running){event('ENGINE_PAUSE',null,null);await persist;await snapshot()}await api('pause');running=false;if(session)session.status='PAUSED';render();toast('Dip Trader pause edildi.')}catch(e){toast(String(e.message||e))}}
async function klines(sym){for(let h of ['https://api.binance.com','https://api1.binance.com','https://api3.binance.com'])try{let r=await fetch(`${h}/api/v3/klines?symbol=${sym}&interval=1m&limit=160`,{cache:'no-store'});if(!r.ok)throw 0;let a=await r.json();candles[sym]=a.map(x=>({t:N(x[0]),o:N(x[1]),h:N(x[2]),l:N(x[3]),c:N(x[4]),v:N(x[5])}));live[sym]=candles[sym].at(-1)?.c;return}catch{}throw Error(`Kline alınamadı: ${sym}`)}
async function historyLoad(){$('chartOverlay').classList.add('show');await Promise.all(COINS.map(s=>klines(s).catch(()=>{})));$('chartOverlay').classList.remove('show');draw();renderRadar()}
function connect(){try{ws?.close()}catch{}let streams=COINS.flatMap(s=>[`${s.toLowerCase()}@aggTrade`,`${s.toLowerCase()}@kline_1m`]).join('/');ws=new WebSocket(`wss://stream.binance.com:9443/stream?streams=${streams}`);ws.onopen=()=>{$('onlineText').textContent='BINANCE LIVE';$('onlinePill').querySelector('.dot').classList.remove('off');$('marketDotSide').classList.remove('off');$('marketTextSide').textContent='Binance Spot canlı';$('feedState').textContent='LIVE';$('feedState').className='pos'};ws.onmessage=e=>{lastWs=Date.now();let m;try{m=JSON.parse(e.data).data}catch{return}if(m.e==='aggTrade'){tick(m.s,N(m.p));if(m.s===selected)draw();renderRadar();renderKpi()}else if(m.e==='kline'){let k=m.k,s=m.s,a=candles[s]||(candles[s]=[]),x={t:N(k.t),o:N(k.o),h:N(k.h),l:N(k.l),c:N(k.c),v:N(k.v)},i=a.findIndex(z=>z.t===x.t);i>=0?a[i]=x:a.push(x);if(a.length>180)a.splice(0,a.length-180);if(s===selected)draw()}};ws.onclose=()=>setTimeout(connect,1400);ws.onerror=()=>{try{ws.close()}catch{}}}
function draw(){let cv=$('candleCanvas'),box=$('chartWrap'),ctx=cv.getContext('2d'),dpr=devicePixelRatio||1,w=Math.max(300,box.clientWidth),h=Math.max(250,box.clientHeight);cv.width=w*dpr;cv.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#080e17';ctx.fillRect(0,0,w,h);let a=(candles[selected]||[]).slice(-100);if(!a.length)return;let lo=Math.min(...a.map(x=>x.l)),hi=Math.max(...a.map(x=>x.h)),pad=(hi-lo)*.06||1;lo-=pad;hi+=pad;let L=10,R=72,T=10,B=30,xw=(w-L-R)/a.length,y=v=>T+(hi-v)/(hi-lo)*(h-T-B);ctx.strokeStyle='#172238';ctx.lineWidth=1;for(let i=1;i<5;i++){let yy=T+(h-T-B)*i/5;ctx.beginPath();ctx.moveTo(L,yy);ctx.lineTo(w-R,yy);ctx.stroke()}a.forEach((c,i)=>{let x=L+xw*i+xw/2,col=c.c>=c.o?'#0ecb81':'#f6465d';ctx.strokeStyle=col;ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(x,y(c.h));ctx.lineTo(x,y(c.l));ctx.stroke();let top=y(Math.max(c.o,c.c)),bot=y(Math.min(c.o,c.c));ctx.fillRect(x-Math.max(1,xw*.28),top,Math.max(2,xw*.56),Math.max(1,bot-top))});let st=states[selected];if(st.dip){ctx.setLineDash([4,4]);ctx.strokeStyle='#97a3b5';ctx.beginPath();ctx.moveTo(L,y(st.dip));ctx.lineTo(w-R,y(st.dip));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#aeb7c4';ctx.fillText(`DIP ${price(st.dip)}`,L+5,y(st.dip)-5)}if(st.pos){ctx.setLineDash([5,4]);ctx.strokeStyle='#2af0a3';ctx.beginPath();ctx.moveTo(L,y(st.pos.entry));ctx.lineTo(w-R,y(st.pos.entry));ctx.stroke();ctx.setLineDash([])}let lp=N(live[selected]);if(lp>0){ctx.fillStyle='#f6465d';ctx.fillRect(w-R+4,y(lp)-9,R-8,18);ctx.fillStyle='#fff';ctx.font='9px system-ui';ctx.fillText(price(lp),w-R+8,y(lp)+3)}$('chartSymbol').textContent=selected;$('lastPrice').textContent=price(lp);$('chartSub').textContent=`Binance Spot · 1m · ${a.length} mum · canlı fiyat`}
function renderRadar(){let c=book.cfg||session?.config||cfgUi();$('coinRadar').innerHTML=COINS.map(s=>{let st=states[s],state=st.pos?'LONG':st.armed?'DIP HUNT':st.lastAction==='SKIP'?'SKIP':c.symbols.includes(s)?'FLAT':'OFF',cl=st.pos?'long':st.armed?'hunt':st.lastAction==='SKIP'?'skip':'';return`<div class="coinCard ${s===selected?'selected':''}" data-s="${s}"><div><div class="coinTop"><span class="coinSymbol">${s.replace('USDT','')}</span><span class="coinState ${cl}">${state}</span></div><div class="coinMeta">Dip ${price(st.dip)}${st.pos?` · Buy ${price(st.pos.entry)}`:''}<br>${st.armed?`Düşüş ${st.drop.toFixed(1)} · dönüş ${st.rebound.toFixed(1)} kademe`:'Yeni dip bekliyor'}</div><div class="scoreBar"><i style="width:${st.score}%"></i></div><div class="scoreLabel">Dip Zekâ Skoru ${st.score}/100 · alış filtresi değil</div></div><div class="coinRight"><div class="coinPrice">${price(live[s])}</div>${st.realized?`<div class="coinMove ${st.realized>=0?'pos':'neg'}">${pnl(st.realized)}</div>`:''}</div></div>`}).join('');document.querySelectorAll('[data-s]').forEach(x=>x.onclick=()=>{selected=x.dataset.s;renderRadar();draw()})}
function note(e){let m=e.metadata||{};if(e.event_kind==='DIP_ARMED')return`Tepe ${price(m.peak)} · ${N(m.drop_steps||0).toFixed(1)} kademe`;if(e.event_kind==='DIP_NEW_LOW')return`Yeni dip · skor ${m.dip_score??'—'}`;if(e.event_kind==='BUY')return`Rebound ${N(m.rebound_steps||0).toFixed(1)} · hedef ${price(m.target_price)}`;if(e.event_kind==='SELL')return'Paper satış · cost dahil';if(e.event_kind==='SKIP_CHASE')return`Ani sıçrama ${N(m.rebound_steps||0).toFixed(1)} kademe · kovalanmadı`;return''}
function renderLog(){$('eventRows').innerHTML=history.length?history.slice(0,70).map(e=>`<tr><td>${clock(e.observed_at)}</td><td><span class="tag ${e.event_kind==='BUY'?'buy':e.event_kind==='SELL'?'sell':e.event_kind.startsWith('DIP')?'dipTag':'neutral'}">${e.event_kind}</span></td><td><b>${(e.symbol||'—').replace('USDT','')}</b></td><td>${price(e.price)}</td><td>${price(e.dip_low)}</td><td>${price(e.entry_price)}</td><td class="${N(e.realized_pnl)>0?'pos':N(e.realized_pnl)<0?'neg':''}">${e.realized_pnl==null?'—':pnl(e.realized_pnl)}</td><td class="noteCell">${note(e)}</td></tr>`).join(''):'<tr><td colspan="8">Henüz dip olayı yok.</td></tr>'}
function renderKpi(){let m=metrics();$('kpiEquity').textContent=cash(m.equity);$('kpiEquityMeta').textContent=`Başlangıç ${cash(book.start)} · ${m.returnPct.toFixed(2)}%`;$('kpiPnl').textContent=pnl(book.realized);$('kpiPnl').className=`value ${book.realized>0?'pos':book.realized<0?'neg':''}`;$('kpiPnlMeta').textContent=`Unrealized ${pnl(m.unrealized)}`;$('kpiOpen').textContent=m.open;$('kpiOpenMeta').textContent=COINS.filter(s=>states[s].pos).map(s=>s.replace('USDT','')).join(' · ')||'Pozisyon yok';let closed=book.wins+book.losses;$('kpiWin').textContent=closed?`${(100*book.wins/closed).toFixed(1)}%`:'—';$('kpiWinMeta').textContent=`${book.wins} win / ${book.losses} loss`;$('kpiTrades').textContent=book.trades;$('kpiEngine').textContent=running?'RUNNING':session?.status==='RUNNING'?'VIEW':'IDLE';$('kpiEngine').className=`value ${running?'pos':'amber'}`;$('kpiEngineMeta').textContent=running?'Bu cihaz fiyatı işliyor':session?.status==='RUNNING'?'Session açık, motor başka cihazda olabilir':'Başlatılmadı'}
function render(){let s=session;$('sessionBanner').textContent=s?`${s.status} · ${cash(s.starting_equity)} · ${cash(s.trade_notional)} / işlem`:'SESSION YOK';$('sessionState').textContent=s?.status||'IDLE';$('sessionState').className=s?.status==='RUNNING'?'pos':'amber';$('sessionTimes').textContent=s?`Başlangıç ${clock(s.started_at)}`:'Dip Trader Başlat ile yeni kasa aç';$('startBtn').disabled=s?.status==='RUNNING';$('pauseBtn').disabled=s?.status!=='RUNNING';$('ruleRebound').textContent=$('reboundInput').value;$('ruleTp').textContent=$('takeProfitInput').value;$('feedMeta').textContent=lastWs?`Son veri ${Math.round((Date.now()-lastWs)/1000)} sn`:'Bağlanıyor';$('radarStatus').textContent=running?'RUNNING':'WAIT';renderKpi();renderRadar();renderLog();draw()}
function bind(){$('unlockBtn').onclick=async()=>{let k=$('unlockKey').value.trim();if(!k)return;localStorage.setItem(KEY,k);$('unlockKey').value='';unlock(false);await status();await historyLoad();connect()};$('startBtn').onclick=()=>start(false);$('restartBtn').onclick=()=>start(true);$('pauseBtn').onclick=pause;document.querySelectorAll('.symbolToggle').forEach(b=>b.onclick=()=>{b.classList.toggle('active');if(!document.querySelector('.symbolToggle.active'))b.classList.add('active');render()});['reboundInput','takeProfitInput'].forEach(id=>$(id).oninput=render);addEventListener('resize',draw)}
async function init(){bind();reset(500,cfgUi());if(!dashboardKey()){unlock(true);return}unlock(false);await status();await historyLoad();connect();setInterval(snapshot,5000);setInterval(()=>{if(!running)status().catch(()=>{});else api('status').then(d=>{session=d.session;history=d.events||history;render()}).catch(()=>{})},7000);setInterval(()=>{$('feedState').textContent=Date.now()-lastWs<6000?'LIVE':'STALE';$('feedState').className=Date.now()-lastWs<6000?'pos':'amber';renderKpi()},2500)}
addEventListener('load',init);
