'use strict';

const ROOT='https://qbcjuxhvhwagvqbjyemo.supabase.co/functions/v1';
const CONTROL=`${ROOT}/brian-control-center`;
const SYSTEM=`${ROOT}/brian-system-control`;
const KEY_STORAGE='mcp-dashboard-key-v1';
const EP={
  world:`${ROOT}/brian-world-status`,
  evolution:`${ROOT}/brian-evolution-status`,
  treasury:`${ROOT}/brian-evolution-treasury-status`,
  ocean:`${ROOT}/brian-evolution-ocean-status`,
  lab:`${ROOT}/brian-evolution-lab-status`,
  alphaIntel:`${ROOT}/brian-evolution-alpha-intelligence-status`,
  news:`${ROOT}/brian-frontier-news`,
};
const $=(id)=>document.getElementById(id);
const $$=(s)=>[...document.querySelectorAll(s)];
const S={control:null,systemControl:null,world:null,evolution:null,treasury:null,ocean:null,lab:null,alphaIntel:null,news:null,errors:{},lastSync:null,selectedAmount:null,busy:false};
const TR={
  'AI compute demand':'Yapay zekâ hesaplama talebi','Semiconductor supply chain':'Yarı iletken tedarik zinciri','Monetary policy':'Para politikası','Inflation':'Enflasyon','Geopolitical risk':'Jeopolitik risk','Energy supply':'Enerji arzı','Crypto regulation':'Kripto düzenlemeleri','ETF flows':'ETF para akışları','Cybersecurity / exploit risk':'Siber güvenlik / saldırı riski','Product launch cycle':'Ürün / teknoloji lansmanı','Corporate earnings':'Şirket finansal sonuçları','Token listing / unlock':'Token listeleme / kilit açılımı'
};
function key(){return(localStorage.getItem(KEY_STORAGE)||'').trim()}
function esc(v){return String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function money(v){const n=num(v);return n==null?'—':new Intl.NumberFormat('tr-TR',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)}
function pct(v){const n=num(v);return n==null?'—':`${Math.round(n*100)}%`}
function clock(v){if(!v)return'—';try{return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v))}catch{return'—'}}
function ageSec(v){const t=Date.parse(String(v||''));return Number.isFinite(t)?Math.max(0,(Date.now()-t)/1000):null}
function age(v){const s=ageSec(v);if(s==null)return'—';return s<60?`${Math.round(s)} sn`:s<3600?`${Math.round(s/60)} dk`:`${Math.round(s/3600)} sa`}
function fresh(v,max){const s=ageSec(v);return s!=null&&s<=max}
function trLabel(v){return TR[String(v)]||String(v||'Bilinmeyen gelişme')}
function act(v){return({OPEN_LONG:'LONG AÇ',OPEN_SHORT:'SHORT AÇ',WAIT:'BEKLE',VETO:'VETO',BUY:'AL',SELL:'SAT',HOLD:'TUT'})[String(v)]||String(v||'—').replaceAll('_',' ')}
function unlock(show){$('unlock')?.classList.toggle('show',show)}
async function post(url,body={}){const k=key();if(!k)throw new Error('UNAUTHORIZED_DASHBOARD');const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-brian-dashboard-key':k},body:JSON.stringify(body),cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok){const e=new Error(data.error||data.status||`HTTP ${r.status}`);e.status=r.status;e.payload=data;throw e}return data}
async function safe(name,p){try{S[name]=await p;delete S.errors[name]}catch(e){S[name]=null;S.errors[name]=String(e?.message||e)}}
function collector(id){const rows=S.systemControl?.last_data?.collectors||[];return rows.find((r)=>String(r.collector_id)===id)||null}
function latestCollector(ids){const rows=S.systemControl?.last_data?.collectors||[];return rows.find((r)=>ids.includes(String(r.collector_id)))||null}
function collectorState(ids,maxAge){const r=latestCollector(ids);if(!r)return{state:'warn',meta:'Canlı çalışma kanıtı bekleniyor',run:null};if(String(r.status)==='FAILED')return{state:'bad',meta:r.error_message||r.error_class||'Worker başarısız',run:r};if(!fresh(r.started_at,maxAge))return{state:'warn',meta:`Son başarılı akış ${age(r.started_at)} önce`,run:r};if(!['SUCCESS','DEGRADED'].includes(String(r.status)))return{state:'warn',meta:`Durum: ${r.status}`,run:r};return{state:r.status==='DEGRADED'?'warn':'ok',meta:`Gerçek veri akışı · ${age(r.started_at)} önce`,run:r}}
function sysControl(){return S.systemControl?.control||{}}
function systemEnabled(){return sysControl().system_enabled!==false}
function stateText(s){return s==='ok'?'Çalışıyor':s==='info'?'Hazır':s==='warn'?'Bekliyor / gecikmiş':'Hata'}
function setDot(id,s){const el=$(id);if(el)el.className=`dot ${s}`}
function setFlow(id,s){const el=$(id);if(el)el.setAttribute('class',`flow ${s}`)}

async function refresh(){
  if(!key()){unlock(true);return}
  $('syncText').textContent='Canlı servisler ve veri akışları doğrulanıyor…';
  await Promise.all([
    safe('systemControl',post(SYSTEM,{action:'status'})),safe('control',post(CONTROL,{action:'status'})),safe('world',post(EP.world)),safe('evolution',post(EP.evolution)),safe('treasury',post(EP.treasury)),safe('ocean',post(EP.ocean)),safe('lab',post(EP.lab)),safe('alphaIntel',post(EP.alphaIntel)),safe('news',post(EP.news))
  ]);
  S.lastSync=new Date();
  const target=num(sysControl().treasury_target_equity_usd);
  if(S.selectedAmount==null&&target!=null)S.selectedAmount=target;
  render();
}

function moduleRows(){
  const enabled=systemEnabled();
  if(!enabled){return[
    {key:'world',name:'Dünya Gezgini',icon:'🌍',state:'info',meta:'Sistem operatör tarafından durduruldu'},
    {key:'behavior',name:'Davranış Motoru',icon:'🧠',state:'info',meta:'Sistem operatör tarafından durduruldu'},
    {key:'alpha',name:'ALPHA',icon:'α',state:'info',meta:'Sistem operatör tarafından durduruldu'},
    {key:'treasury',name:'Hazine / Portföy',icon:'◉',state:'info',meta:'Sistem operatör tarafından durduruldu'},
    {key:'research',name:'Araştırma Lab',icon:'⚗',state:'info',meta:'Sistem operatör tarafından durduruldu'},
    {key:'ocean',name:'Okyanus',icon:'≈',state:'info',meta:'Sistem operatör tarafından durduruldu'}
  ]}
  const worldBrain=collectorState(['brian-world-brain-v1'],720);
  const discovery=collectorState(['brian-world-discovery-eye-v1'],900);
  const worldState=discovery.state==='bad'?'warn':worldBrain.state;
  const worldMeta=discovery.state==='bad'?`Ana Dünya Beyni canlı · Keşif gözü hata: ${discovery.meta}`:worldBrain.meta;
  const alphaRun=collectorState(['brian-alpha-decision-compiler-v2'],240);
  const alphaOnline=S.control?.alpha_v2?.online===true;
  const alphaState=alphaRun.state==='ok'&&alphaOnline?'ok':alphaRun.state==='bad'?'bad':'warn';
  const alphaMeta=alphaOnline?`${alphaRun.meta} · karar ${Math.round(Number(S.control?.alpha_v2?.decision_age_seconds||0))} sn önce`:(S.errors.control||alphaRun.meta);
  const treasuryRun=collectorState(['brian-evolution-treasury-v1'],180);
  const treasuryState=S.treasury&&treasuryRun.state==='ok'?'ok':treasuryRun.state;
  const treasuryMeta=S.treasury?`${treasuryRun.meta} · ${money(S.treasury.summary?.equity_usd)}`:S.errors.treasury||treasuryRun.meta;
  const researchRun=collectorState(['brian-evolution-orchestrator-v1','brian-evolution-researcher-v1','brian-evolution-promotion-council-v1'],900);
  const researchState=S.evolution&&researchRun.state==='ok'?'ok':researchRun.state;
  const oceanRun=collectorState(['brian-evolution-ocean-worker-v1'],660);
  const oceanState=S.ocean&&oceanRun.state==='ok'?'ok':oceanRun.state;
  const oceanMeta=S.ocean?.active_run?`${oceanRun.meta} · Ocean sınavı aktif`:`${oceanRun.meta} · servis hazır, aktif sınav yok`;
  const behaviorEvidence=worldState==='ok'&&alphaState==='ok'&&S.news!=null;
  const behaviorState=behaviorEvidence?'ok':worldState==='bad'||alphaState==='bad'?'bad':'warn';
  return[
    {key:'world',name:'Dünya Gezgini',icon:'🌍',state:worldState,meta:worldMeta},
    {key:'behavior',name:'Davranış Motoru',icon:'🧠',state:behaviorState,meta:behaviorEvidence?'World + ALPHA + haber kanıt akışı canlı':'Birleşik davranış kanıtı tamamlanmadı'},
    {key:'alpha',name:'ALPHA',icon:'α',state:alphaState,meta:alphaMeta},
    {key:'treasury',name:'Hazine / Portföy',icon:'◉',state:treasuryState,meta:treasuryMeta},
    {key:'research',name:'Araştırma Lab',icon:'⚗',state:researchState,meta:S.evolution?researchRun.meta:S.errors.evolution||researchRun.meta},
    {key:'ocean',name:'Okyanus',icon:'≈',state:oceanState,meta:oceanMeta}
  ];
}
function renderModules(){const rows=moduleRows();const good=rows.filter((r)=>r.state==='ok').length;const bad=rows.filter((r)=>r.state==='bad').length;$('moduleCount').textContent=`${good}/${rows.length} canlı`; $('moduleCount').className=`badge ${bad?'bad':good===rows.length?'ok':'warn'}`;$('moduleList').innerHTML=rows.map((r)=>`<div class="module"><div class="module-icon">${r.icon}</div><div class="module-main"><div class="module-name">${esc(r.name)}</div><div class="module-meta">${esc(r.meta)}</div></div><span class="dot ${r.state}"></span></div>`).join('');const map={world:['dotWorld','textWorld','cableWorld'],behavior:['dotBehavior','textBehavior','cableBehavior'],alpha:['dotAlpha','textAlpha','cableAlpha'],treasury:['dotTreasury','textTreasury','cableTreasury'],research:['dotResearch','textResearch','cableResearch'],ocean:['dotOcean','textOcean','cableOcean']};rows.forEach((r)=>{const m=map[r.key];if(!m)return;setDot(m[0],r.state);$(m[1]).textContent=stateText(r.state);setFlow(m[2],r.state)});return{rows,good,bad}}

function news(){if(Array.isArray(S.news?.items)&&S.news.items.length)return S.news.items.slice(0,10).map((x)=>({urgency:x.urgency||'MEDIUM',title:x.title_tr||'Brian için önemli gelişme',summary:x.summary_tr||'',time:x.observed_at,source:x.source_id,asset:x.primary_asset,original:x.original_claim}));const out=[];(S.world?.narratives||[]).slice(0,5).forEach((n)=>out.push({urgency:Number(n.strength)>=.75?'HIGH':'MEDIUM',title:trLabel(n.label),summary:`Brian bu anlatıyı ${Math.round(Number(n.strength||0)*100)}% güçle izliyor.`,time:n.observed_at,source:'World Brain'}));return out}
function renderNews(){const items=news();$('newsBadge').textContent=items.length?`${items.length} ÖNEMLİ`:'AKIŞ YOK';$('newsBadge').className=`badge ${items.length?'ok':'warn'}`;$('criticalNews').innerHTML=items.length?items.slice(0,7).map((n)=>`<div class="news"><div class="news-top"><div class="news-title">${esc(n.title)}</div><div class="severity ${String(n.urgency).toLowerCase()}">${n.urgency==='CRITICAL'?'KRİTİK':n.urgency==='HIGH'?'YÜKSEK':'ORTA'}</div></div><div class="news-meta">${esc(n.summary)}${n.asset?` · ${esc(n.asset)}`:''}<br>${clock(n.time)} · ${esc(n.source||'Brian')}</div>${n.original?`<details class="news-meta"><summary>Orijinal kaynak</summary>${esc(n.original)}</details>`:''}</div>`).join(''):'<div class="news"><div class="news-title">Brian filtresinden geçen kritik gelişme henüz yok.</div><div class="news-meta">Bu bir genel haber akışı değildir; yalnız Brian için değerli gelişmeler görünür.</div></div>';const top=items.slice(0,4);const h=top.length?top.map((n)=>`<div class="ticker-item"><span class="dot ${n.urgency==='CRITICAL'?'bad':n.urgency==='HIGH'?'warn':'info'}"></span><b>Brian:</b> ${esc(n.title)}</div>`).join(''):'<div class="ticker-item"><span class="dot info"></span><b>Brian:</b> dünya akışı izleniyor · kritik gelişme yok</div>';$('tickerTrack').innerHTML=h+h}
function renderAlpha(){const a=S.control?.alpha_v2||{},ds=a.decisions||[],d=ds[0];$('alphaValue').textContent=d?act(d.action):(a.online?'CANLI':'—');$('alphaMeta').textContent=d?`${String(d.asset_id||'').replace('crypto:','')} · ${age(d.observed_at)} önce`:'Karar bekleniyor';$('alphaBadge').textContent=a.online?'CANLI':'BAĞLANTI';$('alphaBadge').className=`badge ${a.online?'ok':'bad'}`;$('alphaFeed').innerHTML=ds.slice(0,5).map((x)=>`<div class="module"><div class="module-icon">α</div><div class="module-main"><div class="module-name">${esc(String(x.asset_id||'').replace('crypto:',''))} · ${esc(act(x.action))}</div><div class="module-meta">${clock(x.observed_at)} · kanıt ${Number(x.evidence_score||0).toFixed(2)} · maliyet ${Number(x.estimated_round_trip_cost_bps||0).toFixed(1)} bps</div></div><span class="dot ${['OPEN_LONG','OPEN_SHORT'].includes(x.action)?'ok':x.action==='VETO'?'bad':'info'}"></span></div>`).join('')||'<div class="module"><span class="dot warn"></span><div class="module-main"><div class="module-name">ALPHA karar akışı bekleniyor</div></div></div>'}
function renderTreasury(){const s=S.treasury?.summary||sysControl().treasury;$('treasuryValue').textContent=s?money(s.equity_usd):'—';$('treasuryMeta').textContent=s?`${money(s.cash_usd)} nakit · ${pct(s.deployment_pct)} kullanım`:'Treasury worker bekleniyor'}
function renderWorld(){const s=S.world?.summary;$('worldValue').textContent=s?String(s.unique_entities??0):'—';$('worldMeta').textContent=s?`${s.narratives??0} anlatı · ${s.asset_impact_candidates??0} etki adayı`:'World Brain bekleniyor'}
function renderResearch(){const e=S.evolution||{},j=e.journal||[],g=e.gaps||[];$('researchBadge').textContent=e.status==='ONLINE'?'CANLI':'İZLENİYOR';$('researchBadge').className=`badge ${e.status==='ONLINE'?'ok':'warn'}`;const rows=[...j.slice(0,3).map((x)=>({title:x.title||x.event_type,meta:x.summary||`${x.stage||''} · ${clock(x.occurred_at)}`})),...g.slice(0,3).map((x)=>({title:`Eksik yetenek: ${x.capabilityId||x.capability_id||x.domain}`,meta:x.reason||x.suggestedAction||x.suggested_action}))];$('researchFeed').innerHTML=rows.slice(0,5).map((x)=>`<div class="module"><div class="module-icon">⚗</div><div class="module-main"><div class="module-name">${esc(x.title||'Araştırma')}</div><div class="module-meta">${esc(x.meta||'')}</div></div></div>`).join('')||'<div class="module"><span class="dot info"></span><div class="module-main"><div class="module-name">Araştırma hattı hazır; yeni kayıt bekleniyor</div></div></div>'}
function renderBehavior(){const n=(S.world?.narratives||[])[0],items=news();const rows=moduleRows(),b=rows.find((x)=>x.key==='behavior');$('behaviorBadge').textContent=b?.state==='ok'?'CANLI KANIT':'KANIT TOPLANIYOR';$('behaviorBadge').className=`badge ${b?.state==='ok'?'ok':'warn'}`;$('behaviorText').textContent=n||items.length?`Brian ${n?trLabel(n.label):items[0].title} çevresindeki insan ve piyasa tepkisini gerçek fiyat/akış kanıtıyla birlikte izliyor. Metin hissi tek başına işlem yetkisi vermez.`:'Davranış katmanı World + ALPHA + kritik haber kanıtını birlikte bekliyor.'}
function renderBelief(){const edges=S.alphaIntel?.expected_edges||S.alphaIntel?.edges||[],e=edges[0];if(!e){$('beliefP').textContent='—';$('beliefQ').textContent='—';$('beliefX').textContent='—';return}const p=num(e.expected_gross_move_bps),q=num(e.estimated_round_trip_cost_bps),x=num(e.expected_net_edge_bps);$('beliefP').textContent=p==null?'—':`${p.toFixed(1)} bps`;$('beliefQ').textContent=q==null?'—':`${q.toFixed(1)} bps`;$('beliefX').textContent=x==null?'—':`${x.toFixed(1)} bps`}

function renderControls(){const c=sysControl(),active=Number(c.managed_jobs_active||0),total=Number(c.managed_jobs_total||0),enabled=c.system_enabled!==false;$('jobBadge').textContent=total?`${active}/${total} İŞ`:'KONTROL';$('jobBadge').className=`badge ${enabled&&active===total&&total>0?'ok':!enabled?'info':'warn'}`;$('jobCount').textContent=total?`${active}/${total}`:'—';const treasury=c.treasury||{};const target=num(c.treasury_target_equity_usd)??num(treasury.starting_equity_usd)??10000;if(S.selectedAmount==null)S.selectedAmount=target;$$('.amount-btn[data-amount]').forEach((b)=>b.classList.toggle('active',Number(b.dataset.amount)===Number(S.selectedAmount)));const current=num(treasury.starting_equity_usd);$('amountNote').textContent=current==null?`Seçilen kasa: ${money(S.selectedAmount)} · Başlat ile uygulanır`:Math.abs(current-S.selectedAmount)<.01?`Aktif SHADOW kasa başlangıcı: ${money(current)}`:`Seçilen ${money(S.selectedAmount)} · mevcut ${money(current)} · Başlat/Yeniden Başlat ile uygulanır`;$('controlFeedback').innerHTML=`<span class="dot ${!enabled?'info':active===total&&total>0?'ok':'warn'}"></span><span>${!enabled?'Brian sistemi durduruldu. DIP bundan etkilenmedi.':active===total&&total>0?'Brian arka plan işlerinin tamamı aktif.':'Bazı Brian arka plan işleri aktif değil; durum listesinde görünür.'}</span>`;const latest=S.systemControl?.last_data?.alpha?.observed_at||S.systemControl?.last_data?.world?.observed_at;$('lastDataAge').textContent=latest?age(latest):'—';$$('#startSystem,#restartSystem,#stopSystem,.amount-btn').forEach((b)=>b.disabled=S.busy)}
function renderAlerts(rows){const alerts=[];rows.forEach((m)=>{if(m.state==='bad'||m.state==='warn')alerts.push({state:m.state,title:`${m.name}: ${stateText(m.state)}`,meta:m.meta})});const failed=(S.systemControl?.last_data?.collectors||[]).filter((r)=>String(r.status)==='FAILED').slice(0,4);failed.forEach((r)=>alerts.push({state:'bad',title:`${r.collector_id}: worker hatası`,meta:r.error_message||r.error_class||'Bilinmeyen hata'}));news().filter((n)=>['CRITICAL','HIGH'].includes(n.urgency)).slice(0,2).forEach((n)=>alerts.push({state:n.urgency==='CRITICAL'?'bad':'warn',title:n.title,meta:n.summary}));$('alertCount').textContent=String(alerts.length);$('alertCount').className=`badge ${alerts.some((a)=>a.state==='bad')?'bad':alerts.length?'warn':'ok'}`;$('alertFeed').innerHTML=alerts.length?alerts.slice(0,8).map((a)=>`<div class="module"><span class="dot ${a.state}"></span><div class="module-main"><div class="module-name">${esc(a.title)}</div><div class="module-meta">${esc(a.meta||'')}</div></div></div>`).join(''):'<div class="module"><span class="dot ok"></span><div class="module-main"><div class="module-name">Kritik bağlantı sorunu yok</div><div class="module-meta">Canlı kanıt hatları stabil</div></div></div>'}
function renderMaster(summary){const c=sysControl(),enabled=c.system_enabled!==false,total=Number(c.managed_jobs_total||0),active=Number(c.managed_jobs_active||0);let state='warn';if(!enabled)state='info';else if(summary.bad>0||S.errors.systemControl)state='bad';else if(summary.good===summary.rows.length&&active===total&&total>0)state='ok';setDot('masterDot',state);$('masterText').textContent=state==='ok'?'SİSTEM CANLI':state==='info'?'DURDURULDU':state==='bad'?'SORUN VAR':'KISMİ / İZLE';$('healthValue').textContent=`${Math.round(summary.good/summary.rows.length*100)}%`;$('healthMeta').textContent=`${summary.good}/${summary.rows.length} modül gerçek taze kanıtla çalışıyor`;$('brainStatus').textContent=state==='ok'?'Brian düşünüyor · veri paketleri canlı · SHADOW ONLY':state==='info'?'Brian operatör tarafından durduruldu · DIP bağımsız çalışır':state==='bad'?'Brian çalışıyor ancak kırmızı hata hattı var':'Brian çalışıyor · bazı hatlar kanıt/güncelleme bekliyor';$('syncText').textContent=S.lastSync?`Canlı senkron ${clock(S.lastSync.toISOString())}`:'Bağlanıyor'}
function renderMeeting(rows){const f=(k)=>rows.find((x)=>x.key===k);[['mWorld','world'],['mAlpha','alpha'],['mTreasury','treasury'],['roomWorld','world'],['roomAlpha','alpha'],['roomTreasury','treasury'],['roomResearch','research']].forEach(([id,k])=>{const r=f(k);if($(id))$(id).textContent=r?stateText(r.state):'—'});$('roomSkeptic').textContent=news().length?'Karşı kanıt tarıyor':'Kanıt bekliyor'}
function render(){renderControls();const summary=renderModules();renderNews();renderAlpha();renderTreasury();renderWorld();renderResearch();renderBehavior();renderBelief();renderAlerts(summary.rows);renderMaster(summary);renderMeeting(summary.rows)}

async function runControl(action){if(S.busy)return;S.busy=true;renderControls();try{const body={action};if(action==='start'||action==='restart')body.starting_equity=S.selectedAmount;const result=await post(SYSTEM,body);bubble(action==='stop'?'Sistemi durdur':action==='restart'?'Sistemi yeniden başlat':'Sistemi başlat','user');bubble(result.status==='RUNNING'||result.status==='RESTARTED'?'Brian sistemi komutu kabul etti. Canlı heartbeatleri yeniden doğruluyorum.':result.status==='STOPPED'?'Brian arka plan işleri durduruldu. DIP etkilenmedi.':String(result.status||'Komut tamamlandı'),'brian');await refresh()}catch(e){bubble(`Kontrol hatası: ${e.message}`,'brian');if(e.status===409&&e.payload?.error)$('controlFeedback').innerHTML=`<span class="dot bad"></span><span>${esc(e.payload.error)}</span>`}finally{S.busy=false;renderControls()}}
function chooseAmount(v){const n=Number(v);if(!Number.isFinite(n)||n<100||n>1000000)return;S.selectedAmount=Math.round(n*100)/100;renderControls()}
function bubble(text,type){const el=document.createElement('div');el.className=`bubble ${type}`;el.textContent=text;$('chatLog').appendChild(el);$('chatLog').scrollTop=$('chatLog').scrollHeight}
function answer(q){const text=String(q||'').trim();if(!text)return;const l=text.toLocaleLowerCase('tr-TR');let r='';if(l.includes('haber')||l.includes('geliş')){const n=news()[0];r=n?`En yüksek öncelikli gelişme: ${n.title}. ${n.summary}`:'Şu an Brian filtresinden geçen kritik gelişme yok.'}else if(l.includes('sorun')||l.includes('hata')||l.includes('çalış')){const bad=moduleRows().filter((m)=>m.state==='bad'||m.state==='warn');r=bad.length?`Dikkat isteyen hatlar: ${bad.map((x)=>`${x.name} (${stateText(x.state)})`).join(', ')}.`:'Ana modüllerde kritik kopukluk görmüyorum.'}else if(l.includes('alpha')||l.includes('karar')){const d=S.control?.alpha_v2?.decisions?.[0];r=d?`ALPHA'nın son kararı ${String(d.asset_id||'').replace('crypto:','')} için ${act(d.action)}. ${age(d.observed_at)} önce üretildi.`:"ALPHA'dan okunabilir karar gelmedi."}else if(l.includes('hazine')||l.includes('kasa')||l.includes('para')){const s=S.treasury?.summary||sysControl().treasury;r=s?`Shadow hazine ${money(s.equity_usd)}. Nakit ${money(s.cash_usd)}, kullanılan sermaye ${pct(s.deployment_pct)}, açık pozisyon ${s.open_positions??0}.`:'Hazine ilk canlı cycle verisini bekliyor.'}else{const rows=moduleRows(),good=rows.filter((x)=>x.state==='ok').length;r=`Şu an ${good}/${rows.length} ana modül taze veri kanıtıyla çalışıyor. Brian ve DIP iki ayrı sistem olarak tutuluyor.`}bubble(text,'user');setTimeout(()=>bubble(r,'brian'),120)}
function open(id){$(id)?.classList.add('show')}function close(id){$(id)?.classList.remove('show')}
function bind(){const h=location.hash||'',m=h.match(/(?:^#|&)key=([^&]+)/);if(m){try{localStorage.setItem(KEY_STORAGE,decodeURIComponent(m[1]))}catch{}history.replaceState(null,'',location.pathname+location.search)}unlock(!key());$('unlockBtn')?.addEventListener('click',()=>{const v=$('unlockKey').value.trim();if(!v)return;localStorage.setItem(KEY_STORAGE,v);unlock(false);refresh()});$('unlockKey')?.addEventListener('keydown',(e)=>{if(e.key==='Enter')$('unlockBtn').click()});$$('.amount-btn[data-amount]').forEach((b)=>b.addEventListener('click',()=>chooseAmount(b.dataset.amount)));$('customAmount')?.addEventListener('click',()=>{const raw=prompt('SHADOW kasa tutarı (USD)',String(S.selectedAmount||10000));if(raw!=null)chooseAmount(raw.replaceAll('.','').replace(',','.'))});$('startSystem')?.addEventListener('click',()=>runControl('start'));$('restartSystem')?.addEventListener('click',()=>runControl('restart'));$('stopSystem')?.addEventListener('click',()=>runControl('stop'));$('chatSend')?.addEventListener('click',()=>{const v=$('chatInput').value;$('chatInput').value='';answer(v)});$('chatInput')?.addEventListener('keydown',(e)=>{if(e.key==='Enter')$('chatSend').click()});$$('[data-q]').forEach((b)=>b.addEventListener('click',()=>answer(b.dataset.q)));$('openMeeting')?.addEventListener('click',()=>open('meetingModal'));$$('[data-close]').forEach((b)=>b.addEventListener('click',()=>close(b.dataset.close)));$$('.modal').forEach((m0)=>m0.addEventListener('click',(e)=>{if(e.target===m0)m0.classList.remove('show')}));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&key())refresh()})}
bind();if(key())refresh();setInterval(()=>{if(key()&&document.visibilityState==='visible'&&!S.busy)refresh()},15000);
