const OCEAN_STATUS_API='https://qbcjuxhvhwagvqbjyemo.supabase.co/functions/v1/brian-evolution-ocean-status';
const OCEAN_CONTROL_API='https://qbcjuxhvhwagvqbjyemo.supabase.co/functions/v1/brian-evolution-ocean-control';
const KEY_STORAGE='mcp-dashboard-key-v1';
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function key(){return(localStorage.getItem(KEY_STORAGE)||'').trim();}
function clock(v){if(!v)return'—';try{return new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Berlin',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v));}catch{return'—';}}
function usd(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('tr-TR',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n):'—';}
function pct(v){const n=Number(v);return Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'—';}
function pill(text,tone=''){return`<span class="oc-pill ${tone}">${esc(text)}</span>`;}
function toast(message){const el=$('toast');if(!el)return;el.textContent=String(message);el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3500);}
function showLock(v){$('ocLock')?.classList.toggle('show',v);}
async function callApi(url,body={}){const k=key();if(!k)throw Error('Anahtar yok');const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-brian-dashboard-key':k},body:JSON.stringify(body),cache:'no-store'});let data={};try{data=await r.json();}catch{}if(!r.ok){if(r.status===401){localStorage.removeItem(KEY_STORAGE);showLock(true);}const e=Error(data.error||data.status||`HTTP ${r.status}`);e.payload=data;throw e;}return data;}
function duration(active){if(!active)return'—';const end=Date.parse(active.effectiveEndAt),now=Date.now();if(!Number.isFinite(end))return'—';const ms=Math.max(0,end-now),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return`${h}s ${m}dk kaldı`;}
function renderPreflight(data){const p=data?.preflight||data;if(!p){$('ocPreflightDetail').innerHTML='<div class="oc-row">Preflight henüz çalıştırılmadı.</div>';return;}const reasons=p.reasons||[];$('ocPreflightDetail').innerHTML=`<div class="oc-row"><div class="oc-title">${p.ready?pill('READY','ok'):pill('BLOCKED','warn')}</div><div class="oc-meta">${p.ready?'Evolution + Layer-4 + Treasury runtime kanıtları hazır.':'Ocean başlamadan önce eksikler kapanmalı.'}</div></div>${reasons.map(r=>`<div class="oc-row"><div class="oc-title">${pill('BLOCK','warn')} ${esc(r)}</div></div>`).join('')}`;}
function render(data){
  const active=data.active_run||null,treasury=data.treasury||{},runs=data.runs||[],reports=data.reports||[],workers=data.worker_runs||[];
  $('ocSync').textContent=`Son durum ${clock(data.observed_at)}`;$('ocState').textContent=`◉ ${data.status||'—'}`;
  $('ocRunState').textContent=active?'ACTIVE':'IDLE';$('ocRunTime').textContent=active?`${duration(active)} · bitiş ${clock(active.effectiveEndAt)}`:'Aktif Ocean run yok.';
  $('ocEquity').textContent=usd(treasury.equity_usd);$('ocTreasuryMeta').textContent=`Cash ${usd(treasury.cash_usd)} · deployment ${usd(treasury.deployment_usd)} · gate ${treasury.promotion_gate_open?'açık':'kapalı'}`;
  const latestReport=reports[0]?.summary||null;$('ocReportPnl').textContent=latestReport?usd(latestReport.treasury?.netPnlUsd):'—';$('ocReportAlpha').textContent=latestReport?`ALPHA after-cost ${pct(latestReport.alpha?.favorableAfterCostRate)} · ${latestReport.alpha?.outcomeSamples??0} outcome`:'Tamamlanmış rapor yok.';
  const latestWorker=workers[0]||null;$('ocWorker').textContent=latestWorker?.status||'—';$('ocWorkerMeta').textContent=latestWorker?`${clock(latestWorker.started_at)} · stored ${latestWorker.stored_records??0}`:'Worker henüz çalışmadı.';

  $('ocRuns').innerHTML=runs.map(r=>`<div class="oc-row"><div class="oc-title">${pill(r.status,r.status==='ACTIVE'?'ok':'')} ${esc(r.runId)}</div><div class="oc-meta">Başlangıç ${clock(r.startedAt)} · plan ${r.durationHours}saat · bitiş ${clock(r.effectiveEndAt)}${r.stoppedAt?`<br>Operatör stop ${clock(r.stoppedAt)}`:''}${r.report?'<br>✓ final report hazır':''}</div></div>`).join('')||'<div class="oc-row">Henüz Ocean run yok.</div>';
  const activeView=runs.find(r=>r.status==='ACTIVE');const checkpoints=activeView?.latest_checkpoint?[activeView.latest_checkpoint]:runs.map(r=>r.latest_checkpoint).filter(Boolean).slice(0,12);
  $('ocCheckpoints').innerHTML=checkpoints.map(c=>`<div class="oc-row"><div class="oc-title">${clock(c.observed_at)} ${c.collector_failures_window?pill(`${c.collector_failures_window} fail`,'bad'):pill('healthy','ok')}</div><div class="oc-meta">Equity ${usd(c.treasury_equity_usd)} · cash ${usd(c.treasury_cash_usd)} · deploy ${usd(c.treasury_deployment_usd)} · pos ${esc(c.treasury_open_positions??0)}<br>15dk collector: ${esc(c.collector_runs_window)} run · ${esc(c.collector_degraded_window)} degraded</div></div>`).join('')||'<div class="oc-row">Checkpoint bekleniyor.</div>';
  if(latestReport){const t=latestReport.treasury||{},e=latestReport.evolution||{},a=latestReport.alpha||{},h=latestReport.health||{};$('ocReport').innerHTML=`<div class="oc-row"><div class="oc-title">Treasury ${usd(t.beginningEquityUsd)} → ${usd(t.endingEquityUsd)} ${pill(usd(t.netPnlUsd),Number(t.netPnlUsd)>=0?'ok':'bad')}</div><div class="oc-meta">Actions ${esc(t.actions)} · replacement ${esc(t.replacements)} · cost ${usd(t.cumulativeCostsUsd)} · open pos ${esc(t.endingOpenPositions)}</div></div><div class="oc-row"><div class="oc-title">Evolution</div><div class="oc-meta">Kaynak ${esc(e.newSources)} · hipotez ${esc(e.newHypotheses)} · code candidate ${esc(e.newCodeCandidates)} · experiment ${esc(e.experimentResults)} · promote ${esc(e.promotionCandidates)} · reject ${esc(e.rejectedPromotions)} · drift ${esc(e.driftEvents)}</div></div><div class="oc-row"><div class="oc-title">ALPHA</div><div class="oc-meta">Outcome ${esc(a.outcomeSamples)} · after-cost favorable ${pct(a.favorableAfterCostRate)} · missed ${esc(a.missedOpportunities)}</div></div><div class="oc-row"><div class="oc-title">System Health</div><div class="oc-meta">Collector ${esc(h.collectorRuns)} · fail ${esc(h.collectorFailures)} · degraded ${esc(h.degradedRuns)} · healthy ${pct(h.healthyRunRate)}</div></div>`;}else $('ocReport').innerHTML='<div class="oc-row">Ocean tamamlanınca final rapor burada oluşacak.</div>';
}
async function refresh(){try{const data=await callApi(OCEAN_STATUS_API);showLock(false);render(data);}catch(e){$('ocSync').textContent='Ocean durumu alınamadı';toast(e.message||String(e));}}
async function preflight(){try{const data=await callApi(OCEAN_CONTROL_API,{action:'PREFLIGHT'});renderPreflight(data);toast(data.preflight?.ready?'Ocean preflight hazır.':'Preflight bloklandı.');return data;}catch(e){renderPreflight(e.payload?.preflight);toast(e.message||String(e));return null;}}
async function start(hours){if(!window.confirm(`${hours} saatlik Ocean SHADOW run başlatılsın mı? Gerçek emir açılmaz.`))return;try{const data=await callApi(OCEAN_CONTROL_API,{action:'START',duration_hours:hours,confirm_shadow_only:true,reason:`dashboard ${hours}h Ocean run`});renderPreflight(data.preflight);toast(`Ocean ${hours}saat başlatıldı.`);await refresh();}catch(e){renderPreflight(e.payload?.preflight);toast(e.message||String(e));}}
async function stop(){if(!window.confirm('Aktif Ocean SHADOW run erken durdurulsun mu?'))return;try{await callApi(OCEAN_CONTROL_API,{action:'STOP',reason:'dashboard operator stop'});toast('Ocean durduruldu; final rapor worker tarafından hazırlanacak.');await refresh();}catch(e){toast(e.message||String(e));}}
function bind(){
  $('ocUnlock')?.addEventListener('click',()=>{const v=($('ocKey')?.value||'').trim();if(!v)return;localStorage.setItem(KEY_STORAGE,v);refresh();});
  $('ocKey')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('ocUnlock')?.click();});
  $('ocPreflight')?.addEventListener('click',preflight);$('ocStart24')?.addEventListener('click',()=>start(24));$('ocStart48')?.addEventListener('click',()=>start(48));$('ocStop')?.addEventListener('click',stop);
}
bind();if(!key())showLock(true);else{refresh();preflight();}setInterval(()=>{if(key())refresh();},15000);
