import {
  type Cal, chooseShadowLeverage, clip, ENGINE_VERSION, hash, type J,
  MAX_HOLD_MS, n, POLICY_VERSION, type Runtime, sizePosition, type Struct, SYMBOL,
} from "../_shared/dip_v8_dual.ts";
import type { Market } from "./market.ts";
import { structure } from "./structure.ts";

export const DECISION_REVISION="dip-v8-dual-integrity-20260908.5";
export const MIN_ECONOMIC_RR=1.25;
type Direction="UP"|"DOWN"|"WAIT";
type SetupCandidate={setup:string;direction:"UP"|"DOWN";trigger:Struct;priority:number;provisionalStop:number|null;reason:string};
function isTradeDirection(direction:Direction):direction is "UP"|"DOWN"{return direction==="UP"||direction==="DOWN";}
function validGeometry(direction:Direction,entry:number,inv:number|null,target:number|null):boolean{
  if(!isTradeDirection(direction)||!(entry>0)||!(inv&&target))return false;
  return direction==="UP"?inv<entry&&entry<target:target<entry&&entry<inv;
}

function recentReversal(m:Market,s1:Struct,s5:Struct):SetupCandidate|null{
  const rows=m.bars["1m"].slice(-8);if(rows.length<8)return null;const last=rows.at(-1)!,prev=rows.at(-2)!,prev2=rows.at(-3)!,recentLow=Math.min(...rows.slice(-7).map(x=>x.l)),recentHigh=Math.max(...rows.slice(-7).map(x=>x.h)),fast=m.flowFast.ofi,slow=m.flowSlow.ofi,improve=fast-slow;
  const upMomentum=(last.c>prev.c&&prev.c>=prev2.c)||(last.c>prev.h&&last.c>last.o),downMomentum=(last.c<prev.c&&prev.c<=prev2.c)||(last.c<prev.l&&last.c<last.o),upDistance=(last.c-recentLow)/last.c*10000,downDistance=(recentHigh-last.c)/last.c*10000,minMove=Math.max(10,s1.atr/last.c*10000*.45),upFlow=fast>=.06||improve>=.18,downFlow=fast<=-.06||improve<=-.18,upConflict=s5.bos==="DOWN"&&s1.bos==="DOWN",downConflict=s5.bos==="UP"&&s1.bos==="UP";
  if(upMomentum&&upFlow&&!upConflict&&upDistance>=minMove)return{setup:"EARLY_REVERSAL",direction:"UP",trigger:s1,priority:6,provisionalStop:recentLow,reason:`1m momentum + flow recovery ${fast.toFixed(2)}/${slow.toFixed(2)}`};
  if(downMomentum&&downFlow&&!downConflict&&downDistance>=minMove)return{setup:"EARLY_REVERSAL",direction:"DOWN",trigger:s1,priority:6,provisionalStop:recentHigh,reason:`1m momentum + flow deterioration ${fast.toFixed(2)}/${slow.toFixed(2)}`};
  return null;
}
function directionScore(direction:"UP"|"DOWN",m:Market,s1:Struct,s5:Struct,s15:Struct):number{
  const opp=direction==="UP"?"DOWN":"UP";let score=0;for(const [s,w] of [[s1,1.2],[s5,2.2],[s15,1.0]] as const){if(s.bos===direction)score+=2*w;if(s.bos===opp)score-=2*w;if(s.choch===direction)score+=1.5*w;if(s.choch===opp)score-=1.5*w;if(s.trend===direction)score+=w;if(s.trend===opp)score-=w;}const sign=direction==="UP"?1:-1;score+=sign*m.flowFast.ofi*1.8+sign*m.flowSlow.ofi*.9;if(direction==="UP"){if(m.book.pressure>1.08)score+=.7;if(m.book.pressure<.82)score-=.7;}else{if(m.book.pressure<.92)score+=.7;if(m.book.pressure>1.18)score-=.7;}return score;
}
function hardCounterStructure(direction:"UP"|"DOWN",s1:Struct,s5:Struct):boolean{return direction==="DOWN"?((s5.bos==="UP"&&(s1.trend==="UP"||s1.bos==="UP"))||(s5.trend==="UP"&&s1.bos==="UP")):((s5.bos==="DOWN"&&(s1.trend==="DOWN"||s1.bos==="DOWN"))||(s5.trend==="DOWN"&&s1.bos==="DOWN"));}
function collectCandidates(m:Market,s1:Struct,s5:Struct,s15:Struct):SetupCandidate[]{const out:SetupCandidate[]=[];for(const s of [s1,s5]){if(s.sweep)out.push({setup:"SWEEP_RECLAIM",direction:s.sweep==="BULL"?"UP":"DOWN",trigger:s,priority:s.tf==="5m"?8:7,provisionalStop:null,reason:`${s.tf} ${s.sweep} sweep`});if(s.failedBreak)out.push({setup:"FAILED_BREAK",direction:s.failedBreak==="BULL"?"UP":"DOWN",trigger:s,priority:s.tf==="5m"?8:7,provisionalStop:null,reason:`${s.tf} ${s.failedBreak} failed break`});}if(s5.bos){const p=s5.bos==="UP"?s5.lastHigh:s5.lastLow;if(p&&Math.abs(m.book.mid-p.p)<=s5.atr*.45)out.push({setup:"BOS_RETEST",direction:s5.bos,trigger:s5,priority:7,provisionalStop:null,reason:"5m BOS retest"});}const early=recentReversal(m,s1,s5);if(early)out.push(early);return out.map(c=>({...c,priority:c.priority+directionScore(c.direction,m,s1,s5,s15)})).sort((a,b)=>b.priority-a.priority);}
export function selectEconomicTarget(direction:Direction,entry:number,_costBps:number,structs:Struct[]):number|null{if(!isTradeDirection(direction)||!(entry>0))return null;const kind=direction==="UP"?"H":"L",candidates:number[]=[];for(const s of structs){const equal=direction==="UP"?s.equalHigh:s.equalLow;if(equal)candidates.push(equal);for(const p of s.pivots)if(p.kind===kind)candidates.push(p.p);}const levels=[...new Set(candidates)].filter(x=>Number.isFinite(x)&&x>0&&(direction==="UP"?x>entry:x<entry)).sort((a,b)=>direction==="UP"?a-b:b-a);if(!levels.length)return null;return levels[0];}

export async function candidate(m:Market,sessionId:string,rt:Runtime,cfg:J,tradeNotional:number,at:number,getCalibration:(setup:string,direction:string,regime:string)=>Promise<Cal>){
  const [s1,s5,s15,s1h,s4h]=await Promise.all(["1m","5m","15m","1h","4h"].map(tf=>structure(tf,m.bars[tf]))),all=[s1,s5,s15,s1h,s4h],combinedFp=await hash(all.map(s=>s.fingerprint).join("|"));let regime="RANGE";if(s4h.trend===s1h.trend&&s1h.trend!=="RANGE")regime="TREND_"+s1h.trend;else if(s15.choch||s5.choch)regime="TRANSITION";const ranked=rt.pos?[]:collectCandidates(m,s1,s5,s15),chosen=ranked[0]||null;let setup=chosen?.setup||"NONE",direction:Direction=chosen?.direction||"WAIT",trigger:Struct|null=chosen?.trigger||null;
  const triggerPivot=trigger?setup==="BOS_RETEST"?(direction==="UP"?trigger.lastHigh:trigger.lastLow):setup==="EARLY_REVERSAL"?null:(direction==="UP"?trigger.lastLow:trigger.lastHigh):null,inv=chosen?.provisionalStop??triggerPivot?.p??null,fee=n(cfg.fee_bps,10),slip=n(cfg.slippage_bps,1),entry=direction==="DOWN"?m.book.bid*(1-slip/10000):m.book.ask*(1+slip/10000),costBps=2*fee+2*slip+m.book.spreadBps+m.fundingBpsHold,target=selectEconomicTarget(direction,entry,costBps,[s1,s5,s15,s1h]),signalAt=trigger?m.bars[trigger.tf].at(-1)!.ct+1:m.bars["1m"].at(-1)!.ct+1,episode=await hash([SYMBOL,setup,direction,trigger?.tf,triggerPivot?.t,inv,setup==="EARLY_REVERSAL"?"EARLY_REVERSAL":chosen?.reason].join("|")),occurrence=await hash([sessionId,POLICY_VERSION,DECISION_REVISION,episode,signalAt].join("|")),cal=await getCalibration(setup,direction,regime),geometry=validGeometry(direction,entry,inv,target),reward=target?Math.abs(target-entry):0,risk=inv?Math.abs(entry-inv):0,targetBps=reward/entry*10000,stopBps=risk/entry*10000,rawRR=geometry&&risk?reward/risk:0,netRewardBps=Math.max(0,targetBps-costBps),netRiskBps=stopBps+costBps,economicRR=geometry&&netRiskBps>0?netRewardBps/netRiskBps:0,flowScore=m.flowFast.ofi*.65+m.flowSlow.ofi*.35,veto:string[]=[];
  if(!isTradeDirection(direction))veto.push("NO_SIGNAL");else{if(!geometry||risk<s1.atr*.04)veto.push("STRUCTURE_LEVEL_INCOMPLETE");if(targetBps<2.5*costBps)veto.push("TARGET_BELOW_COST");if(economicRR<MIN_ECONOMIC_RR)veto.push("ECONOMIC_RR_TOO_LOW");if(direction==="DOWN"&&cfg.allow_shadow_short!==true)veto.push("SHORT_DISABLED");if(hardCounterStructure(direction,s1,s5))veto.push("COUNTER_STRUCTURE");const opposing=direction==="UP"?(m.flowFast.ofi<=-.25&&m.flowSlow.ofi<=-.20):(m.flowFast.ofi>=.25&&m.flowSlow.ofi>=.20);if(opposing)veto.push("OPPOSING_MULTI_FLOW");if(directionScore(direction,m,s1,s5,s15)<-.5)veto.push("DIRECTION_REFEREE_REJECT");if(cal.unavailable)veto.push("CALIBRATION_UNAVAILABLE");else if(cal.p===null)veto.push("CALIBRATING");else if(cal.lower<=(1+costBps/Math.max(stopBps,1))/(1+Math.max(rawRR,1)))veto.push("CALIBRATION_NO_EDGE");if(cal.ambiguous>0&&cal.ambiguous/Math.max(1,cal.samples+cal.ambiguous)>.20)veto.push("LABEL_UNCERTAINTY_HIGH");}
  const last5m=m.bars["5m"].at(-1)!.ct+1;if(rt.lastLock?.episode_id===episode&&(rt.lastLock.fingerprint===combinedFp||last5m<=rt.lastLock.last5m_t))veto.push("THESIS_LOCKED_NO_NEW_STRUCTURE");if(cfg.execution_mode==="OBSERVE")veto.push("OBSERVATION_ONLY");let raw=.45+(setup==="SWEEP_RECLAIM"?.15:setup==="FAILED_BREAK"?.14:setup==="EARLY_REVERSAL"?.13:setup==="BOS_RETEST"?.10:0);if(isTradeDirection(direction)){if(s5.bos===direction)raw+=.07;if(s1.bos===direction)raw+=.05;if(s15.choch===direction||s5.choch===direction)raw+=.07;const sign=direction==="UP"?1:-1;if(sign*m.flowFast.ofi>.08)raw+=.06;if(sign*m.flowSlow.ofi>.05)raw+=.04;if(direction==="UP"?m.book.pressure>1.08:m.book.pressure<.92)raw+=.05;if(hardCounterStructure(direction,s1,s5))raw-=.15;}raw=clip(raw,0,.92);if(isTradeDirection(direction)&&raw<.60)veto.push("RAW_CONVICTION_LOW");const leverage=chooseShadowLeverage({maxAllowed:n(cfg.max_shadow_leverage,1),cal,raw,economicRR,targetBps,costBps,flowScore}),size=geometry&&isTradeDirection(direction)&&inv?sizePosition(rt.cash,tradeNotional,direction,entry,inv,cal,fee,slip,m.book.spreadBps+m.fundingBpsHold,m.rules,leverage,raw):null;if(isTradeDirection(direction)&&geometry&&!size)veto.push("MIN_NOTIONAL_OR_RISK_CAP");
  const thesis:J={thesis_id:occurrence,occurrence_id:occurrence,episode_id:episode,generated_at:new Date(at).toISOString(),decision_time:new Date(at).toISOString(),data_available_at:new Date(m.availableAt).toISOString(),signal_at:new Date(signalAt).toISOString(),setup,direction,thesis_state:veto.some(x=>x!=="CALIBRATING")?"WAIT":"CONFIRMED",regime,venue:"SHADOW_PERP",entry_low:entry,entry_high:entry,invalidation_price:inv,target_price:target,structural_invalidation_price:direction==="DOWN"?s5.lastHigh?.p:direction==="UP"?s5.lastLow?.p:null,rr:economicRR,raw_rr:rawRR,economic_rr:economicRR,target_distance_bps:targetBps,stop_distance_bps:stopBps,net_reward_bps:netRewardBps,net_risk_bps:netRiskBps,cost_bps:costBps,raw_conviction:isTradeDirection(direction)?raw:null,calibrated_probability:cal.p,calibration_samples:cal.samples,calibration:cal,leverage,leverage_policy:leverage===2?"EDGE_GATED_2X":"BASE_1X",why:all.map(s=>`${s.tf}:${s.trend}/${s.sweep||s.failedBreak||s.bos||"NONE"}`),veto,structure:{s1,s5,s15,s1h,s4h,fingerprint:combinedFp},flow:{ofi:flowScore,fast:m.flowFast,slow:m.flowSlow,book_pressure:m.book.pressure,spread_bps:m.book.spreadBps,funding_rate:m.fundingRate,funding_bps_hold:m.fundingBpsHold,source:m.source},candidate_rank:chosen?.priority??null,candidate_reason:chosen?.reason??null,decision_revision:DECISION_REVISION,policy_version:POLICY_VERSION,engine_version:ENGINE_VERSION};
  const decision=geometry&&isTradeDirection(direction)?{occurrence_id:occurrence,session_id:sessionId,episode_id:episode,symbol:SYMBOL,decision_at:new Date(at).toISOString(),due_at:new Date(at+MAX_HOLD_MS).toISOString(),setup,direction,regime,venue:"SHADOW_PERP",entry_price:entry,target_price:target,invalidation_price:inv,raw_conviction:raw,calibrated_probability:cal.p,calibration_samples:cal.samples,policy_version:POLICY_VERSION,metric_version:"target-before-invalidation-v8.2",evidence:{signal_at:thesis.signal_at,data_available_at:thesis.data_available_at,structure_fingerprint:combinedFp,decision_revision:DECISION_REVISION,raw_conviction:raw,calibration:cal,veto,rr:economicRR,raw_rr:rawRR,economic_rr:economicRR,cost_bps:costBps,leverage,flow:thesis.flow,levels:all.map(s=>({tf:s.tf,trend:s.trend,bos:s.bos,choch:s.choch,high:s.lastHigh,low:s.lastLow,atr:s.atr})),market_rules:m.rules,market_source:m.source},shadow_only:true,live_execution:false}:null;
  return{thesis,decision,occurrence,episode,combinedFp,last5m,direction,entry,inv,target,size,fee,slip,leverage,canEnter:isTradeDirection(direction)&&veto.every(x=>x==="CALIBRATING")&&size!==null};
}
