import { type Bar, type Segment, type Position, type FundingSettlement, SYMBOL } from "../_shared/dip_v8_dual.ts";
const HOSTS=["https://fapi.binance.com","https://fapi1.binance.com","https://fapi2.binance.com"];
const SAFE_ROUTES=new Set(["/fapi/v1/klines","/fapi/v1/depth","/fapi/v1/aggTrades","/fapi/v1/exchangeInfo","/fapi/v1/premiumIndex","/fapi/v1/fundingRate"]);
const TF_MS:Record<string,number>={"1m":60000,"5m":300000,"15m":900000,"1h":3600000,"4h":14400000};
type Fetcher=typeof fetch;
export type Flow={ofi:number;ratio:number;prints:number;firstAt:number;lastAt:number};
export type Market={bars:Record<string,Bar[]>;book:{bid:number;ask:number;mid:number;spreadBps:number;pressure:number;receivedAt:number};flow:Flow;flowFast:Flow;flowSlow:Flow;rules:{minNotional:number;minQty:number;maxQty:number;stepSize:number};availableAt:number;fundingRate:number;fundingBpsHold:number;markPrice:number;indexPrice:number;nextFundingTime:number|null;source:"BINANCE_USDM_PERP"};
async function marketJson(path:string,fetcher:Fetcher=fetch):Promise<unknown>{
  if(!SAFE_ROUTES.has(path.split("?")[0]))throw Error("FORBIDDEN_MARKET_ROUTE");let error="MARKET_UNAVAILABLE";
  for(const host of HOSTS){try{const r=await fetcher(host+path,{method:"GET",headers:{accept:"application/json","user-agent":"Brian-DIP-V8.3-Dual-Shadow/1.0"},signal:AbortSignal.timeout(5500)});if(!r.ok){error="HTTP_"+r.status;if([418,429].includes(r.status))throw Error("RATE_LIMIT");continue;}return await r.json();}catch(e){error=e instanceof Error?e.message:String(e);if(error==="RATE_LIMIT")break;}}
  throw Error("BINANCE_USDM:"+error);
}
function parseBars(raw:unknown,tf:string,nowMs:number,minBars=50):Bar[]{
  if(!Array.isArray(raw)||!TF_MS[tf])throw Error("NO_DATA:"+tf);const duration=TF_MS[tf],rows:Bar[]=raw.map(x=>{if(!Array.isArray(x)||x.length<7)throw Error("INVALID_CANDLE:"+tf);return{t:Number(x[0]),ct:Number(x[6]),o:Number(x[1]),h:Number(x[2]),l:Number(x[3]),c:Number(x[4]),v:Number(x[5])};});
  for(let i=0;i<rows.length;i++){const b=rows[i];if(![b.t,b.ct,b.o,b.h,b.l,b.c,b.v].every(Number.isFinite)||b.t%duration||b.ct!==b.t+duration-1||b.l<=0||b.v<0||b.h<Math.max(b.o,b.c)||b.l>Math.min(b.o,b.c)||b.t>nowMs)throw Error("INVALID_CANDLE:"+tf);if(i&&b.t!==rows[i-1].t+duration)throw Error("CANDLE_GAP_OR_ORDER:"+tf);}
  const closed=rows.filter(b=>b.ct<nowMs);if(closed.length<minBars)throw Error("WARMUP_INSUFFICIENT:"+tf);if(nowMs-(closed.at(-1)!.ct+1)>duration+15000)throw Error("STALE_DATA:"+tf);return closed;
}
function readBook(raw:unknown,receivedAt:number){const r=raw as{bids?:unknown[][];asks?:unknown[][]};if(!Array.isArray(r?.bids)||!Array.isArray(r?.asks)||!r.bids.length||!r.asks.length)throw Error("NO_BOOK");const bids=r.bids.map(x=>[Number(x[0]),Number(x[1])]),asks=r.asks.map(x=>[Number(x[0]),Number(x[1])]);for(const side of[bids,asks])for(const[p,q]of side)if(!(p>0&&q>0)||!Number.isFinite(p*q))throw Error("INVALID_BOOK");if(bids.some((x,i)=>i>0&&x[0]>=bids[i-1][0])||asks.some((x,i)=>i>0&&x[0]<=asks[i-1][0]))throw Error("BOOK_ORDER");const bid=bids[0][0],ask=asks[0][0],mid=(bid+ask)/2;if(bid>=ask)throw Error("CROSSED_BOOK");const bn=bids.slice(0,5).reduce((s,x)=>s+x[0]*x[1],0),an=asks.slice(0,5).reduce((s,x)=>s+x[0]*x[1],0);return{bid,ask,mid,spreadBps:(ask-bid)/mid*10000,pressure:bn/an,receivedAt};}
function readFlow(raw:unknown,nowMs:number):Flow{if(!Array.isArray(raw)||raw.length<10)throw Error("NO_TRADES");let buy=0,sell=0,priorId=-1,priorAt=0;for(const x of raw){const r=x as Record<string,unknown>,at=Number(r.T),id=Number(r.a),value=Number(r.p)*Number(r.q);if(!(value>0)||!Number.isFinite(value)||!Number.isSafeInteger(id)||id<=priorId||at<priorAt||at>nowMs+2000||typeof r.m!=="boolean")throw Error("INVALID_TRADE_ORDER");r.m?sell+=value:buy+=value;priorId=id;priorAt=at;}if(nowMs-priorAt>15000)throw Error("STALE_TRADES");return{ofi:(buy-sell)/(buy+sell),ratio:sell?buy/sell:9,prints:raw.length,firstAt:Number((raw[0] as Record<string,unknown>).T),lastAt:priorAt};}
let rulesCache:{at:number;rules:Market["rules"]}|null=null;
async function exchangeRules(fetcher:Fetcher=fetch):Promise<Market["rules"]>{if(rulesCache&&Date.now()-rulesCache.at<600000)return rulesCache.rules;const raw=await marketJson(`/fapi/v1/exchangeInfo?symbol=${SYMBOL}`,fetcher) as {symbols?:{symbol:string;status:string;filters:Record<string,unknown>[]}[]};const s=raw.symbols?.find(s=>s.symbol===SYMBOL);if(!s||s.status!=="TRADING")throw Error("SYMBOL_NOT_TRADING");const lot=s.filters.find(x=>x.filterType==="LOT_SIZE"),notional=s.filters.find(x=>x.filterType==="MIN_NOTIONAL");const rules={minQty:Number(lot?.minQty),maxQty:Number(lot?.maxQty),stepSize:Number(lot?.stepSize),minNotional:Number(notional?.notional??notional?.minNotional)};if(!Object.values(rules).every(x=>Number.isFinite(x)&&x>0))throw Error("INVALID_MARKET_FILTERS");rulesCache={at:Date.now(),rules};return rules;}
export async function getMarket(fetcher:Fetcher=fetch):Promise<Market>{
  const tfs=Object.keys(TF_MS),[candles,depthRaw,tradesRaw,rules,premiumRaw]=await Promise.all([Promise.all(tfs.map(async tf=>[tf,await marketJson(`/fapi/v1/klines?symbol=${SYMBOL}&interval=${tf}&limit=${tf==="4h"?180:240}`,fetcher)] as const)),marketJson(`/fapi/v1/depth?symbol=${SYMBOL}&limit=20`,fetcher).then(raw=>({raw,receivedAt:Date.now()})),marketJson(`/fapi/v1/aggTrades?symbol=${SYMBOL}&limit=1000`,fetcher),exchangeRules(fetcher),marketJson(`/fapi/v1/premiumIndex?symbol=${SYMBOL}`,fetcher)]);
  const availableAt=Date.now(),bars:Record<string,Bar[]>={};for(const[tf,raw]of candles)bars[tf]=parseBars(raw,tf,availableAt);const book=readBook(depthRaw.raw,depthRaw.receivedAt);if(availableAt-book.receivedAt>15000||book.spreadBps>30)throw Error("STALE_OR_WIDE_BOOK");if(!Array.isArray(tradesRaw)||tradesRaw.length<150)throw Error("NO_TRADES");const fastRows=tradesRaw.slice(-150),slowRows=tradesRaw.slice(-Math.min(800,tradesRaw.length)),flowFast=readFlow(fastRows,availableAt),flowSlow=readFlow(slowRows,availableAt),flow={...flowFast,ofi:flowFast.ofi*.62+flowSlow.ofi*.38,ratio:flowFast.ratio*.62+flowSlow.ratio*.38,prints:flowFast.prints+flowSlow.prints,firstAt:flowSlow.firstAt};const p=premiumRaw as Record<string,unknown>,fundingRate=Number(p.lastFundingRate||0),markPrice=Number(p.markPrice||book.mid),indexPrice=Number(p.indexPrice||book.mid),nextFundingTime=Number(p.nextFundingTime||0)||null,fundingBpsHold=Math.abs(fundingRate)*10000;return{bars,book,flow,flowFast,flowSlow,rules,availableAt,fundingRate,fundingBpsHold,markPrice,indexPrice,nextFundingTime,source:"BINANCE_USDM_PERP"};
}
async function boundary(start:number,end:number,fallback:number,fetcher:Fetcher):Promise<Segment>{const points:{t:number;id:number;p:number}[]=[];let nextId:number|null=null,done=false;for(let page=0;page<8;page++){const params=nextId===null?`startTime=${start}&endTime=${end-1}`:`fromId=${nextId}`,rows=await marketJson(`/fapi/v1/aggTrades?symbol=${SYMBOL}&${params}&limit=1000`,fetcher);if(!Array.isArray(rows))throw Error("INVALID_BOUNDARY_TRADES");for(const row of rows){const r=row as Record<string,unknown>,id=Number(r.a),t=Number(r.T),p=Number(r.p);if(!Number.isSafeInteger(id)||!Number.isFinite(t)||!(p>0))throw Error("INVALID_BOUNDARY_TRADES");if(nextId!==null&&id!==nextId)throw Error("TRADE_ID_GAP");nextId=id+1;if(t<start)throw Error("BOUNDARY_BEFORE_DECISION");if(t>=end){done=true;break;}if(points.length&&t<points.at(-1)!.t)throw Error("TRADE_TIME_ORDER");points.push({t,id,p});}if(done||rows.length<1000){done=true;break;}}if(!done)throw Error("BOUNDARY_PAGE_LIMIT");const prices=points.map(x=>x.p);return{start,end,kind:"TRADES",points,o:prices[0]??fallback,c:prices.at(-1)??fallback,h:prices.length?Math.max(...prices):fallback,l:prices.length?Math.min(...prices):fallback};}
export async function pricePath(start:number,due:number,nowMs:number,entry:number,fetcher:Fetcher=fetch):Promise<{end:number;segments:Segment[]}>{const minute=60000,sealed=Math.floor((nowMs-1500)/minute)*minute,end=due<=sealed?due:sealed;if(end<=start)return{end:start,segments:[]};if(end-start>181*minute)throw Error("PATH_WINDOW_TOO_LARGE");const segments:Segment[]=[],firstFull=Math.min(end,Math.ceil(start/minute)*minute),lastFull=Math.floor(end/minute)*minute;if(start<firstFull)segments.push(await boundary(start,firstFull,entry,fetcher));if(lastFull>firstFull){const raw=await marketJson(`/fapi/v1/klines?symbol=${SYMBOL}&interval=1m&startTime=${firstFull}&endTime=${lastFull-1}&limit=200`,fetcher);if(!Array.isArray(raw))throw Error("NO_PRICE_PATH");let cursor=firstFull;for(const x of raw){if(!Array.isArray(x))throw Error("INVALID_PRICE_PATH");const t=Number(x[0]),ct=Number(x[6]),o=Number(x[1]),h=Number(x[2]),l=Number(x[3]),c=Number(x[4]);if(t!==cursor||ct!==t+minute-1||ct>=end||![o,h,l,c].every(Number.isFinite)||l<=0||h<Math.max(o,c)||l>Math.min(o,c))throw Error("PRICE_PATH_GAP_OR_ORDER");segments.push({start:t,end:ct+1,o,h,l,c,kind:"BAR"});cursor=ct+1;}if(cursor!==lastFull)throw Error("PRICE_PATH_INCOMPLETE");}const tailStart=Math.max(firstFull,lastFull);if(tailStart<end)segments.push(await boundary(tailStart,end,segments.at(-1)?.c??entry,fetcher));return{end,segments};}

// Funding is a signed transfer at an actual settlement, never prorated per minute.
export async function positionFunding(pos:Position,end:number,fetcher:Fetcher=fetch):Promise<{cashflow:number;settlements:FundingSettlement[]}>{
  const start=Date.parse(pos.opened_at);
  if(!Number.isFinite(start)||!Number.isFinite(end)||end<start||end-start>181*60000)throw Error("INVALID_FUNDING_WINDOW");
  if(end===start)return{cashflow:0,settlements:[]};
  const rows=await marketJson(`/fapi/v1/fundingRate?symbol=${SYMBOL}&startTime=${start+1}&endTime=${end}&limit=100`,fetcher);
  if(!Array.isArray(rows)||rows.length>=100)throw Error("INCOMPLETE_FUNDING_HISTORY");
  let previous=start;
  const settlements:FundingSettlement[]=rows.map(row=>{
    const fundingTime=Number(row.fundingTime),fundingRate=Number(row.fundingRate),markPrice=Number(row.markPrice);
    if(row.symbol!==SYMBOL||!Number.isSafeInteger(fundingTime)||fundingTime<=previous||fundingTime>end||!Number.isFinite(fundingRate)||!(markPrice>0)||!Number.isFinite(markPrice))throw Error("INVALID_FUNDING_HISTORY");
    previous=fundingTime;
    return{fundingTime,fundingRate,markPrice,cashflow:(pos.side==="LONG"?-1:1)*pos.qty*markPrice*fundingRate};
  });
  return{cashflow:settlements.reduce((sum,x)=>sum+x.cashflow,0),settlements};
}
