import { buildCodeCandidatePlan, buildExperimentPlan, detectDrift, evaluatePromotion, generateResearchHypotheses, type ResearchInputs } from "./evolution_research.ts";

function inputs(observedAt="2026-09-11T13:00:00Z"):ResearchInputs{return{observedAt,gaps:[{gapId:"planned:portfolio.treasury",capabilityId:"portfolio.treasury",severity:"HIGH",reason:"Treasury missing",suggestedAction:"build shadow treasury",evidenceRefs:[]}],challenger:{allowAction:94,downgradeToWait:1021,keepWait:5268,allowAvgCostAdjustedBps:7.5,downgradeAvgCostAdjustedBps:-35.39,observedAt:"2026-09-11T12:00:00Z",evidenceRefs:["challenger:summary"]},outcomes:[{horizonSeconds:300,samples:2525,grossPositiveRate:.439,avgDirectionBps:-3.37,avgAfterCostBps:-26.8,favorableAfterCostRate:.162,observedAt:"2026-09-11T12:00:00Z",evidenceRefs:["outcomes:300"]}],reliability:[{sensorFamily:"micro_velocity",samples:1500,canonicalReliability:.5,measuredScore:.64,avgCostAdjustedBps:3.2,observedAt:"2026-09-11T12:00:00Z",evidenceRefs:["reliability:micro_velocity"]}]};}

Deno.test("research engine produces measurable hypotheses from current weaknesses",()=>{const rows=generateResearchHypotheses(inputs());const kinds=new Set(rows.map(r=>r.hypothesisKind));for(const expected of ["CAPABILITY_GAP","ACTION_GATE","EXPECTED_EDGE","RELIABILITY_FEEDBACK","COST_CONTROL"]){if(!kinds.has(expected as never))throw new Error(`missing ${expected}`);}if(rows.some(r=>!r.measurableSuccessCriteria.length))throw new Error("hypothesis without success criteria");});
Deno.test("research identities stay stable across observation cycles",()=>{const first=generateResearchHypotheses(inputs("2026-09-11T13:00:00Z"));const later=generateResearchHypotheses(inputs("2026-09-11T17:00:00Z"));const firstByKind=new Map(first.map(row=>[row.hypothesisKind,row]));const laterByKind=new Map(later.map(row=>[row.hypothesisKind,row]));for(const [kind,row] of firstByKind){const next=laterByKind.get(kind);if(!next)throw new Error(`missing later ${kind}`);if(row.hypothesisId!==next.hypothesisId)throw new Error(`hypothesis churn for ${kind}: ${row.hypothesisId} -> ${next.hypothesisId}`);const p1=buildExperimentPlan(row,"alpha-v2.2","challenger-v1"),p2=buildExperimentPlan(next,"alpha-v2.2","challenger-v1");if(p1.experimentId!==p2.experimentId)throw new Error(`experiment churn for ${kind}`);}});
Deno.test("control or challenger version changes intentionally create a new experiment identity",()=>{const h=generateResearchHypotheses(inputs())[0];const a=buildExperimentPlan(h,"alpha-v2.2","challenger-v1"),b=buildExperimentPlan(h,"alpha-v2.3","challenger-v1"),c=buildExperimentPlan(h,"alpha-v2.2","challenger-v2");if(a.experimentId===b.experimentId||a.experimentId===c.experimentId)throw new Error("semantic version change did not roll experiment identity");});
Deno.test("experiment plans are prospective and contamination-aware",()=>{const h=generateResearchHypotheses(inputs())[0];const p=buildExperimentPlan(h,"alpha-v2.2","challenger-v1");if(p.mode!=="PROSPECTIVE_SHADOW"||p.minimumSamples<300||p.minimumRegimes<3)throw new Error("weak experiment gate");if(!p.contaminationRules.some(x=>x.includes("future data")))throw new Error("causality rule missing");});
Deno.test("promotion council rejects leakage",()=>{const d=evaluatePromotion({samples:500,regimes:4,netEdgeBps:-2,grossEdgeBps:5,maxDrawdownPct:4,favorableAfterCostRate:.3,turnover:10,costBps:7,leakageDetected:false,dataQualityOk:true,stabilityScore:.6,complexityDelta:0},{samples:500,regimes:4,netEdgeBps:10,grossEdgeBps:20,maxDrawdownPct:3,favorableAfterCostRate:.6,turnover:9,costBps:8,leakageDetected:true,dataQualityOk:true,stabilityScore:.8,complexityDelta:1});if(d.decision!=="REJECT")throw new Error("leakage must reject");});
Deno.test("promotion council can nominate robust positive challenger",()=>{const d=evaluatePromotion({samples:600,regimes:4,netEdgeBps:-3,grossEdgeBps:8,maxDrawdownPct:5,favorableAfterCostRate:.3,turnover:20,costBps:11,leakageDetected:false,dataQualityOk:true,stabilityScore:.6,complexityDelta:0},{samples:600,regimes:5,netEdgeBps:6,grossEdgeBps:16,maxDrawdownPct:4,favorableAfterCostRate:.5,turnover:12,costBps:10,leakageDetected:false,dataQualityOk:true,stabilityScore:.8,complexityDelta:1});if(d.decision!=="PROMOTE_CANDIDATE"||d.requiredNextStage!=="SHADOW_CANDIDATE")throw new Error(JSON.stringify(d));});
Deno.test("drift engine distinguishes material changes",()=>{const d=detectDrift("sensor:velocity",.5,.75,"2026-09-11T13:00:00Z");if(d.severity!=="SEVERE"||d.direction!=="UP")throw new Error(JSON.stringify(d));});
Deno.test("self coding candidate cannot touch DIP or protected control plane",()=>{const h=generateResearchHypotheses(inputs())[0];let blocked=false;try{buildCodeCandidatePlan(h,"abc123",["supabase/functions/brian-dip-worker/index.ts"]);}catch{blocked=true;}if(!blocked)throw new Error("DIP path allowed");blocked=false;try{buildCodeCandidatePlan(h,"abc123",[".github/workflows/brian-ci.yml"]);}catch{blocked=true;}if(!blocked)throw new Error("CI path allowed");const ok=buildCodeCandidatePlan(h,"abc123",["supabase/functions/brian-alpha-challenger-v3/index.ts","tests/test_alpha_challenger_v3.py"]);if(ok.autonomousApplyAllowed)throw new Error("autonomous apply must stay false");});
