import type { HypothesisCandidate } from "./evolution_research.ts";
import { buildSandboxGenerationBrief, type SandboxGenerationBrief } from "./evolution_sandbox.ts";

export const EVOLUTION_CODEGEN_VERSION = "brian.evolution-codegen.v1";

export interface GeneratedSandboxFile { path:string; content:string; }
export interface GeneratedSandboxArtifact { brief:SandboxGenerationBrief; files:GeneratedSandboxFile[]; generator:string; }

function stemFromPath(path:string){const name=path.split("/").pop()??"candidate.ts";return name.replace(/\.test\.ts$|\.ts$|\.md$/g,"");}
function codePath(brief:SandboxGenerationBrief){return brief.changedPaths.find(p=>p.endsWith(".ts")&&!p.endsWith(".test.ts"))!;}
function testPath(brief:SandboxGenerationBrief){return brief.changedPaths.find(p=>p.endsWith(".test.ts"))!;}
function docPath(brief:SandboxGenerationBrief){return brief.changedPaths.find(p=>p.endsWith(".md"))!;}

export function canGenerateBuiltIn(h:HypothesisCandidate){return["ACTION_GATE","EXPECTED_EDGE","RELIABILITY_FEEDBACK","COST_CONTROL","DRIFT"].includes(h.hypothesisKind);}

function expectedEdgeCode(){return`// Auto-generated Evolution challenger artifact. SHADOW ONLY.\nexport interface ExpectedEdgeInput { expectedGrossMoveBps:number; roundTripCostBps:number; uncertaintyPenaltyBps:number; eventDecayPenaltyBps:number; minimumMarginBps?:number; }\nexport interface ExpectedEdgeDecision { expectedNetEdgeBps:number; minimumMarginBps:number; eligible:boolean; }\nexport function expectedNetEdge(input:ExpectedEdgeInput):ExpectedEdgeDecision {\n  const values=[input.expectedGrossMoveBps,input.roundTripCostBps,input.uncertaintyPenaltyBps,input.eventDecayPenaltyBps];\n  if(values.some(v=>!Number.isFinite(v))) throw new Error("non-finite expected-edge input");\n  if(input.roundTripCostBps<0||input.uncertaintyPenaltyBps<0||input.eventDecayPenaltyBps<0) throw new Error("penalties/cost must be non-negative");\n  const margin=Number.isFinite(input.minimumMarginBps)?Math.max(0,Number(input.minimumMarginBps)):2;\n  const net=input.expectedGrossMoveBps-input.roundTripCostBps-input.uncertaintyPenaltyBps-input.eventDecayPenaltyBps;\n  return {expectedNetEdgeBps:net,minimumMarginBps:margin,eligible:net>margin};\n}\n`;}
function expectedEdgeTest(importPath:string){return`import { expectedNetEdge } from "./${importPath}";\nDeno.test("expected edge subtracts cost uncertainty and decay",()=>{const r=expectedNetEdge({expectedGrossMoveBps:40,roundTripCostBps:20,uncertaintyPenaltyBps:5,eventDecayPenaltyBps:3,minimumMarginBps:2});if(r.expectedNetEdgeBps!==12||!r.eligible)throw new Error(JSON.stringify(r));});\nDeno.test("expected edge fails closed on invalid costs",()=>{let threw=false;try{expectedNetEdge({expectedGrossMoveBps:10,roundTripCostBps:-1,uncertaintyPenaltyBps:0,eventDecayPenaltyBps:0});}catch{threw=true;}if(!threw)throw new Error("negative cost accepted");});\n`;}

function reliabilityCode(){return`// Auto-generated Evolution challenger artifact. SHADOW ONLY.\nexport interface ReliabilityWeightInput { measuredReliability:number; samples:number; prior?:number; shrinkSamples?:number; maxDeviation?:number; driftSeverity?:"NONE"|"WATCH"|"MATERIAL"|"SEVERE"; }\nexport function boundedReliabilityWeight(input:ReliabilityWeightInput):number {\n  if(!Number.isFinite(input.measuredReliability)||input.measuredReliability<0||input.measuredReliability>1) throw new Error("measured reliability must be [0,1]");\n  if(!Number.isFinite(input.samples)||input.samples<0) throw new Error("samples must be non-negative");\n  const prior=Number.isFinite(input.prior)?Number(input.prior):0.5,shrink=Math.max(1,Number(input.shrinkSamples??200));\n  const maturity=Math.max(0,Math.min(1,input.samples/(input.samples+shrink)));\n  const driftFactor=input.driftSeverity==="SEVERE"?0.15:input.driftSeverity==="MATERIAL"?0.4:input.driftSeverity==="WATCH"?0.7:1;\n  const maxDev=Math.max(0,Math.min(0.25,Number(input.maxDeviation??0.15)));\n  const raw=prior+(input.measuredReliability-prior)*maturity*driftFactor;\n  return Math.max(prior-maxDev,Math.min(prior+maxDev,raw));\n}\n`;}
function reliabilityTest(importPath:string){return`import { boundedReliabilityWeight } from "./${importPath}";\nDeno.test("reliability challenger shrinks immature evidence",()=>{const w=boundedReliabilityWeight({measuredReliability:.8,samples:20});if(w<=.5||w>=.6)throw new Error(String(w));});\nDeno.test("severe drift decays weight toward neutral",()=>{const normal=boundedReliabilityWeight({measuredReliability:.7,samples:1000});const drift=boundedReliabilityWeight({measuredReliability:.7,samples:1000,driftSeverity:"SEVERE"});if(Math.abs(drift-.5)>=Math.abs(normal-.5))throw new Error(String(normal)+"/"+String(drift));});\n`;}

function actionGateCode(){return`// Auto-generated Evolution challenger artifact. SHADOW ONLY.\nexport interface ActionGateInput { calibrationScore:number; matureSupportCount:number; avgSupportCostAdjustedBps:number; minimumScore?:number; minimumSupports?:number; }\nexport function allowShadowAction(input:ActionGateInput):boolean {\n  if(!Number.isFinite(input.calibrationScore)||!Number.isFinite(input.avgSupportCostAdjustedBps)) return false;\n  const score=Number(input.minimumScore??0.56),supports=Math.max(1,Math.trunc(Number(input.minimumSupports??2)));\n  return input.matureSupportCount>=supports&&input.calibrationScore>=score&&input.avgSupportCostAdjustedBps>0;\n}\n`;}
function actionGateTest(importPath:string){return`import { allowShadowAction } from "./${importPath}";\nDeno.test("action gate requires mature positive after-cost support",()=>{if(!allowShadowAction({calibrationScore:.7,matureSupportCount:3,avgSupportCostAdjustedBps:4}))throw new Error("good action blocked");if(allowShadowAction({calibrationScore:.7,matureSupportCount:1,avgSupportCostAdjustedBps:4}))throw new Error("immature action allowed");if(allowShadowAction({calibrationScore:.7,matureSupportCount:3,avgSupportCostAdjustedBps:-1}))throw new Error("negative edge allowed");});\n`;}

function costCode(){return`// Auto-generated Evolution challenger artifact. SHADOW ONLY.\nexport interface NetCostGateInput { expectedGrossMoveBps:number; roundTripCostBps:number; uncertaintyPenaltyBps?:number; minimumEdgeToCostRatio?:number; }\nexport function passesNetCostGate(input:NetCostGateInput):boolean {\n  const uncertainty=Math.max(0,Number(input.uncertaintyPenaltyBps??0)),ratio=Math.max(1,Number(input.minimumEdgeToCostRatio??1.2));\n  if(!Number.isFinite(input.expectedGrossMoveBps)||!Number.isFinite(input.roundTripCostBps)||input.roundTripCostBps<0)return false;\n  const net=input.expectedGrossMoveBps-input.roundTripCostBps-uncertainty;\n  const edgeToCost=input.roundTripCostBps===0?Infinity:input.expectedGrossMoveBps/input.roundTripCostBps;\n  return net>0&&edgeToCost>=ratio;\n}\n`;}
function costTest(importPath:string){return`import { passesNetCostGate } from "./${importPath}";\nDeno.test("cost gate rejects gross edge that does not clear costs",()=>{if(passesNetCostGate({expectedGrossMoveBps:18,roundTripCostBps:20}))throw new Error("cost-dominated action allowed");if(!passesNetCostGate({expectedGrossMoveBps:35,roundTripCostBps:20,uncertaintyPenaltyBps:2}))throw new Error("healthy edge blocked");});\n`;}

function driftCode(){return`// Auto-generated Evolution challenger artifact. SHADOW ONLY.\nexport function decayTowardNeutral(weight:number,severity:"NONE"|"WATCH"|"MATERIAL"|"SEVERE",neutral=0.5):number {\n  if(!Number.isFinite(weight)||!Number.isFinite(neutral))throw new Error("non-finite drift input");\n  const factor=severity==="SEVERE"?0.2:severity==="MATERIAL"?0.5:severity==="WATCH"?0.8:1;\n  return neutral+(weight-neutral)*factor;\n}\n`;}
function driftTest(importPath:string){return`import { decayTowardNeutral } from "./${importPath}";\nDeno.test("severe drift decays challenger confidence",()=>{const w=decayTowardNeutral(.8,"SEVERE");if(!(w>.5&&w<.6))throw new Error(String(w));});\n`;}

function docs(h:HypothesisCandidate,brief:SandboxGenerationBrief){return`# Evolution candidate: ${h.hypothesisKind}\n\nStatus: EXPERIMENTAL / SHADOW ONLY / NO AUTO APPLY\n\nHypothesis: ${h.hypothesisId}\n\nProblem: ${h.problemStatement}\n\nMechanism: ${h.proposedMechanism}\n\nParent commit: ${brief.parentCommit}\n\nCandidate branch: ${brief.branchName}\n\nThis artifact is generated into the isolated Evolution candidate namespace. It cannot modify canonical ALPHA, CI/security, auth/secrets, migrations/control-plane, live-money execution, or DIP. Promotion requires replay, stress, prospective evidence and explicit human review.\n`;}

export function generateBuiltInArtifact(h:HypothesisCandidate,parentCommit:string):GeneratedSandboxArtifact{
  if(!canGenerateBuiltIn(h))throw new Error(`NO_BUILTIN_GENERATOR:${h.hypothesisKind}`);
  const brief=buildSandboxGenerationBrief(h,parentCommit);const code=codePath(brief),test=testPath(brief),doc=docPath(brief);const stem=stemFromPath(code),importName=`${stem}.ts`;
  let codeText="",testText="";
  if(h.hypothesisKind==="EXPECTED_EDGE"){codeText=expectedEdgeCode();testText=expectedEdgeTest(importName);}
  else if(h.hypothesisKind==="RELIABILITY_FEEDBACK"){codeText=reliabilityCode();testText=reliabilityTest(importName);}
  else if(h.hypothesisKind==="ACTION_GATE"){codeText=actionGateCode();testText=actionGateTest(importName);}
  else if(h.hypothesisKind==="COST_CONTROL"){codeText=costCode();testText=costTest(importName);}
  else {codeText=driftCode();testText=driftTest(importName);}
  return{brief,files:[{path:code,content:codeText},{path:test,content:testText},{path:doc,content:docs(h,brief)}],generator:EVOLUTION_CODEGEN_VERSION};
}
