import { EVOLUTION_EVIDENCE_CLASS, type EvolutionStage } from "./evolution_contract.ts";

export const WORLD_BRAIN_VERSION = "brian.world-brain.v1";

export type WorldEntityType = "ASSET" | "COMPANY" | "PERSON" | "COUNTRY" | "CENTRAL_BANK" | "REGULATOR" | "COMMODITY" | "CURRENCY" | "SECTOR" | "TECHNOLOGY" | "PRODUCT" | "PROTOCOL" | "THEME";
export interface WorldBrainInputEvent { event_id:string; asset?:string|null; event_kind?:string|null; source_kind?:string|null; source_id?:string|null; published_at?:string|null; first_observed_at:string; claim:string; direction?:number|null; magnitude?:number|null; trust_class?:string|null; entity_confidence?:number|null; provenance_uri?:string|null; metadata?:Record<string,unknown>|null; }
export interface WorldEventFrame { frameId:string; eventId:string; observedAt:string; publishedAt:string|null; eventKind:string; sourceId:string; claim:string; primaryAsset:string|null; entityIds:string[]; narrativeIds:string[]; directionHint:-1|0|1; sourceTrustClass:string; provenanceUri:string|null; stage:EvolutionStage; evidenceRefs:string[]; }
export interface WorldEntityObservation { observationId:string; entityId:string; canonicalName:string; entityType:WorldEntityType; observedAt:string; eventId:string; matchKind:"ASSET_FIELD"|"ALIAS"|"PHRASE"; confidence:number; provenanceUri:string|null; evidenceRefs:string[]; }
export interface WorldRelationAssertion { assertionId:string; srcEntityId:string; dstEntityId:string; relation:string; observedAt:string; eventId:string; confidence:number; mechanism:string; stage:EvolutionStage; evidenceRefs:string[]; }
export interface WorldNarrativeSnapshot { snapshotId:string; narrativeId:string; label:string; observedAt:string; eventIds:string[]; entityIds:string[]; strength:number; breadth:number; directionBalance:number; stage:EvolutionStage; evidenceRefs:string[]; }
export interface WorldFutureEventCandidate { futureEventId:string; eventKind:string; scheduledAt:string; firstObservedAt:string; title:string; entityIds:string[]; assetIds:string[]; sourceEventId:string; confidence:number; stage:EvolutionStage; evidenceRefs:string[]; }
export interface WorldCausalMechanism { mechanismId:string; narrativeId:string; observedAt:string; cause:string; transmission:string[]; affectedAssets:Array<{assetId:string;conditionalDirection:-1|0|1;rationale:string}>; confidence:number; stage:EvolutionStage; evidenceRefs:string[]; counterEvidenceRequired:true; }
export interface WorldScenarioSnapshot { scenarioId:string; mechanismId:string; observedAt:string; branch:"MECHANISM_HOLDS"|"MECHANISM_BREAKS"; assumptions:string[]; invalidators:string[]; assetImpacts:Array<{assetId:string;conditionalDirection:-1|0|1;rationale:string}>; confidence:number; stage:EvolutionStage; evidenceRefs:string[]; }
export interface WorldAssetImpactCandidate { impactId:string; assetId:string; observedAt:string; mechanismId:string; scenarioId:string; conditionalDirection:-1|0|1; confidence:number; rationale:string; stage:EvolutionStage; directAlphaInfluence:false; evidenceRefs:string[]; }
export interface WorldBrainBatch { observedAt:string; eventFrames:WorldEventFrame[]; entityObservations:WorldEntityObservation[]; relationAssertions:WorldRelationAssertion[]; narrativeSnapshots:WorldNarrativeSnapshot[]; futureEvents:WorldFutureEventCandidate[]; causalMechanisms:WorldCausalMechanism[]; scenarios:WorldScenarioSnapshot[]; assetImpacts:WorldAssetImpactCandidate[]; evidenceClass:typeof EVOLUTION_EVIDENCE_CLASS; shadowOnly:true; liveExecution:false; directAlphaInfluence:false; }

type EntityDef={id:string;name:string;type:WorldEntityType;aliases:RegExp[]};
const ENTITIES:EntityDef[]=[
  {id:"asset:BTC",name:"Bitcoin",type:"ASSET",aliases:[/\bbitcoin\b/i,/\bbtc\b/i]},
  {id:"asset:ETH",name:"Ethereum",type:"ASSET",aliases:[/\bethereum\b/i,/\beth\b/i]},
  {id:"asset:SOL",name:"Solana",type:"ASSET",aliases:[/\bsolana\b/i,/\bsol\b/i]},
  {id:"asset:XRP",name:"XRP",type:"ASSET",aliases:[/\bxrp\b/i,/\bripple\b/i]},
  {id:"asset:BNB",name:"BNB",type:"ASSET",aliases:[/\bbnb\b/i,/binance coin/i]},
  {id:"commodity:GOLD",name:"Gold",type:"COMMODITY",aliases:[/\bgold\b/i,/\bxau\b/i]},
  {id:"commodity:SILVER",name:"Silver",type:"COMMODITY",aliases:[/\bsilver\b/i,/\bxag\b/i]},
  {id:"commodity:OIL",name:"Oil",type:"COMMODITY",aliases:[/\boil\b/i,/\bbrent\b/i,/\bwti\b/i,/crude/i]},
  {id:"currency:USD",name:"US Dollar",type:"CURRENCY",aliases:[/us dollar/i,/\busd\b/i,/dollar index/i,/\bdxy\b/i]},
  {id:"currency:EUR",name:"Euro",type:"CURRENCY",aliases:[/\beuro\b/i,/\beur\b/i]},
  {id:"centralbank:FED",name:"Federal Reserve",type:"CENTRAL_BANK",aliases:[/federal reserve/i,/\bfed\b/i,/\bfomc\b/i]},
  {id:"centralbank:ECB",name:"European Central Bank",type:"CENTRAL_BANK",aliases:[/european central bank/i,/\becb\b/i]},
  {id:"regulator:SEC",name:"U.S. SEC",type:"REGULATOR",aliases:[/securities and exchange commission/i,/\bsec\b/i]},
  {id:"company:NVIDIA",name:"NVIDIA",type:"COMPANY",aliases:[/\bnvidia\b/i,/\bnvda\b/i]},
  {id:"company:APPLE",name:"Apple",type:"COMPANY",aliases:[/\bapple\b/i,/\baapl\b/i,/\biphone\b/i]},
  {id:"company:TSMC",name:"TSMC",type:"COMPANY",aliases:[/\btsmc\b/i,/taiwan semiconductor/i]},
  {id:"company:MICROSOFT",name:"Microsoft",type:"COMPANY",aliases:[/\bmicrosoft\b/i,/\bmsft\b/i]},
  {id:"company:ALPHABET",name:"Alphabet / Google",type:"COMPANY",aliases:[/\balphabet\b/i,/\bgoogle\b/i,/\bgoogl\b/i]},
  {id:"company:AMAZON",name:"Amazon",type:"COMPANY",aliases:[/\bamazon\b/i,/\bamzn\b/i]},
  {id:"company:OPENAI",name:"OpenAI",type:"COMPANY",aliases:[/\bopenai\b/i,/chatgpt/i]},
  {id:"person:TRUMP",name:"Donald Trump",type:"PERSON",aliases:[/donald trump/i,/president trump/i,/\btrump\b/i]},
  {id:"person:MUSK",name:"Elon Musk",type:"PERSON",aliases:[/elon musk/i,/\bmusk\b/i]},
  {id:"sector:SEMICONDUCTORS",name:"Semiconductors",type:"SECTOR",aliases:[/semiconductor/i,/chipmaker/i,/\bchip\b/i,/gpu/i]},
  {id:"technology:AI",name:"Artificial Intelligence",type:"TECHNOLOGY",aliases:[/artificial intelligence/i,/\bai\b/i,/large language model/i,/inference/i]},
];

type NarrativeRule={id:string;label:string;patterns:RegExp[]};
const NARRATIVES:NarrativeRule[]=[
  {id:"narrative:AI_COMPUTE",label:"AI compute demand",patterns:[/artificial intelligence/i,/\bai\b/i,/gpu/i,/accelerator/i,/inference/i,/data ?center/i]},
  {id:"narrative:SEMICONDUCTOR_SUPPLY",label:"Semiconductor supply chain",patterns:[/semiconductor/i,/foundry/i,/wafer/i,/hbm/i,/packaging/i,/chip supply/i]},
  {id:"narrative:MONETARY_POLICY",label:"Monetary policy",patterns:[/federal reserve/i,/\bfed\b/i,/\bfomc\b/i,/\becb\b/i,/interest rate/i,/rate cut/i,/rate hike/i]},
  {id:"narrative:INFLATION",label:"Inflation",patterns:[/inflation/i,/\bcpi\b/i,/\bpce\b/i,/consumer prices/i]},
  {id:"narrative:GEOPOLITICS",label:"Geopolitical risk",patterns:[/war/i,/conflict/i,/sanction/i,/missile/i,/invasion/i,/ceasefire/i,/geopolit/i]},
  {id:"narrative:ENERGY_SUPPLY",label:"Energy supply",patterns:[/\boil\b/i,/\bbrent\b/i,/\bwti\b/i,/opec/i,/crude/i,/pipeline/i,/refinery/i]},
  {id:"narrative:CRYPTO_REGULATION",label:"Crypto regulation",patterns:[/crypto regulation/i,/securities and exchange commission/i,/\bsec\b/i,/lawsuit/i,/ban/i,/regulat/i]},
  {id:"narrative:ETF_FLOWS",label:"ETF flows",patterns:[/\betf\b/i,/inflow/i,/outflow/i,/spot bitcoin/i,/spot ethereum/i]},
  {id:"narrative:STABLECOIN_PAYMENTS",label:"Stablecoin payments",patterns:[/stablecoin/i,/usdc/i,/usdt/i,/digital dollar/i,/payments/i]},
  {id:"narrative:CYBERSECURITY",label:"Cybersecurity / exploit risk",patterns:[/hack/i,/exploit/i,/breach/i,/cyber/i,/vulnerability/i]},
  {id:"narrative:PRODUCT_LAUNCH",label:"Product launch cycle",patterns:[/launch/i,/unveil/i,/release/i,/new iphone/i,/new gpu/i,/product event/i]},
  {id:"narrative:EARNINGS",label:"Corporate earnings",patterns:[/earnings/i,/revenue/i,/guidance/i,/quarterly results/i]},
  {id:"narrative:TOKEN_EVENT",label:"Token listing / unlock",patterns:[/token unlock/i,/listing/i,/delisting/i,/airdrop/i,/mainnet/i]},
];

type Template={narrativeId:string;cause:string;transmission:string[];affectedAssets:Array<{assetId:string;conditionalDirection:-1|0|1;rationale:string}>};
const TEMPLATES:Template[]=[
  {narrativeId:"narrative:MONETARY_POLICY",cause:"A material change in expected policy rates or liquidity conditions",transmission:["policy expectations","sovereign yields / real yields","USD and financial conditions","risk-asset and precious-metal discount rates"],affectedAssets:[{assetId:"commodity:GOLD",conditionalDirection:1,rationale:"easier real-rate conditions can support non-yielding gold, all else equal"},{assetId:"currency:USD",conditionalDirection:-1,rationale:"relative easing can weaken USD, conditional on other central banks and risk demand"},{assetId:"asset:BTC",conditionalDirection:1,rationale:"easier liquidity can support liquidity-sensitive assets, regime dependent"}]},
  {narrativeId:"narrative:GEOPOLITICS",cause:"A material rise in geopolitical uncertainty or conflict risk",transmission:["risk premium","safe-haven demand","trade / logistics disruption","energy supply expectations"],affectedAssets:[{assetId:"commodity:GOLD",conditionalDirection:1,rationale:"safe-haven demand can rise during severe uncertainty"},{assetId:"commodity:OIL",conditionalDirection:1,rationale:"supply-route risk can add an energy risk premium"},{assetId:"asset:BTC",conditionalDirection:0,rationale:"crypto response is regime dependent"}]},
  {narrativeId:"narrative:ENERGY_SUPPLY",cause:"A change in expected physical energy supply or demand balance",transmission:["physical oil balance","energy prices","inflation expectations","rates / margins / purchasing power"],affectedAssets:[{assetId:"commodity:OIL",conditionalDirection:1,rationale:"supply tightening tends to support crude prices, conditional on demand"},{assetId:"commodity:GOLD",conditionalDirection:0,rationale:"second-order effect depends on inflation versus real-yield response"}]},
  {narrativeId:"narrative:AI_COMPUTE",cause:"A change in expected demand for AI training/inference compute",transmission:["accelerator demand","foundry / advanced packaging / HBM demand","datacenter capex","power and cooling demand"],affectedAssets:[{assetId:"company:NVIDIA",conditionalDirection:1,rationale:"accelerator demand is directly relevant to NVIDIA expectations"},{assetId:"company:TSMC",conditionalDirection:1,rationale:"advanced-node and packaging demand can transmit to foundry utilization"},{assetId:"sector:SEMICONDUCTORS",conditionalDirection:1,rationale:"suppliers can benefit if compute capex expands"}]},
  {narrativeId:"narrative:CRYPTO_REGULATION",cause:"A material change in legal access, enforcement or market-structure rules for crypto",transmission:["market access","listing / custody / institutional participation","liquidity","risk premium"],affectedAssets:[{assetId:"asset:BTC",conditionalDirection:0,rationale:"direction depends on whether regulation expands or restricts access"},{assetId:"asset:ETH",conditionalDirection:0,rationale:"direction depends on rule scope and asset classification"}]},
  {narrativeId:"narrative:PRODUCT_LAUNCH",cause:"A product launch materially changes expected demand, pricing power or ecosystem adoption",transmission:["product reception","unit / service demand","company revenue expectations","supplier order expectations"],affectedAssets:[{assetId:"company:APPLE",conditionalDirection:0,rationale:"impact depends on product reception versus expectations"},{assetId:"company:NVIDIA",conditionalDirection:0,rationale:"launch impact depends on performance, pricing and supply versus expectations"},{assetId:"company:TSMC",conditionalDirection:0,rationale:"supplier impact depends on actual order mix"}]},
];

const clamp=(n:number)=>Number.isFinite(n)?Math.max(0,Math.min(1,n)):0;
const sid=(parts:Array<string|number|null|undefined>)=>parts.map(v=>String(v??"").trim().toLowerCase().replace(/[^a-z0-9:_-]+/g,"-")).join("|");
const direction=(v:unknown):-1|0|1=>Number(v)>0?1:Number(v)<0?-1:0;

function entitiesFor(event:WorldBrainInputEvent):WorldEntityObservation[]{
  const text=`${event.claim} ${event.asset??""}`; const asset=String(event.asset??"").toUpperCase(); const seen=new Set<string>(); const out:WorldEntityObservation[]=[];
  for(const entity of ENTITIES){const assetMatch=Boolean(asset)&&entity.aliases.some(re=>re.test(asset)); const textMatch=entity.aliases.some(re=>re.test(text)); if(!assetMatch&&!textMatch||seen.has(entity.id))continue; seen.add(entity.id); out.push({observationId:sid(["entity",event.event_id,entity.id]),entityId:entity.id,canonicalName:entity.name,entityType:entity.type,observedAt:event.first_observed_at,eventId:event.event_id,matchKind:assetMatch?"ASSET_FIELD":"ALIAS",confidence:clamp(assetMatch?0.95:Number(event.entity_confidence??0.7)),provenanceUri:event.provenance_uri??null,evidenceRefs:[`intel_event:${event.event_id}`]});}
  if(asset&&!out.some(r=>r.matchKind==="ASSET_FIELD")){const normalized=asset.replace(/[^A-Z0-9:_-]+/g,"_").slice(0,48);out.push({observationId:sid(["entity",event.event_id,`asset:${normalized}`]),entityId:`asset:${normalized}`,canonicalName:asset,entityType:"ASSET",observedAt:event.first_observed_at,eventId:event.event_id,matchKind:"ASSET_FIELD",confidence:0.9,provenanceUri:event.provenance_uri??null,evidenceRefs:[`intel_event:${event.event_id}`]});}
  return out;
}
function narrativesFor(event:WorldBrainInputEvent):NarrativeRule[]{return NARRATIVES.filter(r=>r.patterns.some(re=>re.test(event.claim)));}
function explicitFuture(event:WorldBrainInputEvent,now:string):string|null{const m=event.metadata??{};for(const raw of [m.scheduled_at,m.event_at,m.release_at,m.launch_at,m.earnings_at]){if(typeof raw!=="string")continue;const t=Date.parse(raw);if(Number.isFinite(t)&&t>Date.parse(now))return new Date(t).toISOString();}const hit=event.claim.match(/\b(20\d{2}-\d{2}-\d{2})(?:[T ](\d{2}:\d{2})(?::\d{2})?Z?)?\b/);if(!hit)return null;const t=Date.parse(hit[2]?`${hit[1]}T${hit[2]}:00Z`:`${hit[1]}T12:00:00Z`);return Number.isFinite(t)&&t>Date.parse(now)?new Date(t).toISOString():null;}
function relationsFor(event:WorldBrainInputEvent,entities:WorldEntityObservation[]):WorldRelationAssertion[]{const text=event.claim.toLowerCase();const rel=/supplier|supplies|supply agreement/.test(text)?"SUPPLY_CHAIN_RELATED":/partner|partnership|collaborat/.test(text)?"PARTNERSHIP_RELATED":/acquir|merger|buyout/.test(text)?"CORPORATE_TRANSACTION_RELATED":/uses|powered by|built on/.test(text)?"TECHNOLOGY_DEPENDENCY_RELATED":"CO_MENTIONED";const confidence=rel==="CO_MENTIONED"?0.25:0.55;const out:WorldRelationAssertion[]=[];for(let i=0;i<entities.length;i++)for(let j=i+1;j<entities.length;j++)out.push({assertionId:sid(["relation",event.event_id,entities[i].entityId,entities[j].entityId,rel]),srcEntityId:entities[i].entityId,dstEntityId:entities[j].entityId,relation:rel,observedAt:event.first_observed_at,eventId:event.event_id,confidence,mechanism:rel==="CO_MENTIONED"?"entities appeared in the same prospective event; no causal relationship is asserted":`headline language suggested ${rel.toLowerCase().replaceAll("_"," ")}; requires independent verification`,stage:"RESEARCHING",evidenceRefs:[`intel_event:${event.event_id}`]});return out;}

export function buildWorldBrainBatch(events:WorldBrainInputEvent[],observedAt:string):WorldBrainBatch{
  const eventFrames:WorldEventFrame[]=[];const entityObservations:WorldEntityObservation[]=[];const relationAssertions:WorldRelationAssertion[]=[];const futureEvents:WorldFutureEventCandidate[]=[];const map=new Map<string,{rule:NarrativeRule;events:WorldBrainInputEvent[];entities:Set<string>}>();
  for(const event of events){if(!event.event_id||!event.first_observed_at||!event.claim)continue;const entities=entitiesFor(event);const narratives=narrativesFor(event);entityObservations.push(...entities);relationAssertions.push(...relationsFor(event,entities));for(const rule of narratives){const bucket=map.get(rule.id)??{rule,events:[],entities:new Set<string>()};bucket.events.push(event);entities.forEach(e=>bucket.entities.add(e.entityId));map.set(rule.id,bucket);}eventFrames.push({frameId:sid(["frame",event.event_id]),eventId:event.event_id,observedAt:event.first_observed_at,publishedAt:event.published_at??null,eventKind:String(event.event_kind??"UNKNOWN"),sourceId:String(event.source_id??"unknown"),claim:event.claim,primaryAsset:event.asset?String(event.asset):null,entityIds:entities.map(e=>e.entityId),narrativeIds:narratives.map(n=>n.id),directionHint:direction(event.direction),sourceTrustClass:String(event.trust_class??"UNKNOWN"),provenanceUri:event.provenance_uri??null,stage:"RESEARCHING",evidenceRefs:[`intel_event:${event.event_id}`]});const scheduled=explicitFuture(event,observedAt);if(scheduled)futureEvents.push({futureEventId:sid(["future",event.event_id,scheduled]),eventKind:String(event.event_kind??"SCHEDULED_EVENT"),scheduledAt:scheduled,firstObservedAt:event.first_observed_at,title:event.claim.slice(0,320),entityIds:entities.map(e=>e.entityId),assetIds:entities.filter(e=>["ASSET","COMMODITY","CURRENCY","COMPANY","SECTOR"].includes(e.entityType)).map(e=>e.entityId),sourceEventId:event.event_id,confidence:clamp(Number(event.entity_confidence??0.6)),stage:"VERIFYING",evidenceRefs:[`intel_event:${event.event_id}`]});}
  const narrativeSnapshots:WorldNarrativeSnapshot[]=[];for(const {rule,events:rows,entities} of map.values()){const dirs=rows.map(r=>direction(r.direction));const sum=dirs.reduce<number>((a,b)=>a+b,0);const breadth=new Set(rows.map(r=>String(r.source_id??"unknown"))).size;narrativeSnapshots.push({snapshotId:sid(["narrative",rule.id,observedAt]),narrativeId:rule.id,label:rule.label,observedAt,eventIds:rows.map(r=>r.event_id),entityIds:[...entities],strength:clamp((Math.log1p(rows.length)/Math.log(8))*0.65+Math.min(1,breadth/5)*0.35),breadth,directionBalance:dirs.length?sum/dirs.length:0,stage:"RESEARCHING",evidenceRefs:rows.map(r=>`intel_event:${r.event_id}`)});}
  const causalMechanisms:WorldCausalMechanism[]=[];for(const narrative of narrativeSnapshots)for(const t of TEMPLATES.filter(x=>x.narrativeId===narrative.narrativeId))causalMechanisms.push({mechanismId:sid(["mechanism",narrative.narrativeId,observedAt]),narrativeId:narrative.narrativeId,observedAt,cause:t.cause,transmission:[...t.transmission],affectedAssets:t.affectedAssets.map(x=>({...x})),confidence:clamp(0.25+0.12*Math.min(4,narrative.eventIds.length)+0.08*Math.min(3,narrative.breadth)),stage:"RESEARCHING",evidenceRefs:[...narrative.evidenceRefs],counterEvidenceRequired:true});
  const scenarios:WorldScenarioSnapshot[]=[];const assetImpacts:WorldAssetImpactCandidate[]=[];for(const m of causalMechanisms){const hold=sid(["scenario",m.mechanismId,"holds"]);const brk=sid(["scenario",m.mechanismId,"breaks"]);scenarios.push({scenarioId:hold,mechanismId:m.mechanismId,observedAt,branch:"MECHANISM_HOLDS",assumptions:["source evidence remains valid","transmission is not fully priced","no stronger countervailing regime dominates"],invalidators:["independent counter-evidence","market reaction contradicts transmission","source claim is retracted or materially revised"],assetImpacts:m.affectedAssets.map(x=>({...x})),confidence:m.confidence,stage:"RESEARCHING",evidenceRefs:[...m.evidenceRefs]},{scenarioId:brk,mechanismId:m.mechanismId,observedAt,branch:"MECHANISM_BREAKS",assumptions:["the proposed mechanism fails, is priced, or is overwhelmed"],invalidators:["fresh independent evidence restores the mechanism"],assetImpacts:m.affectedAssets.map(x=>({...x,conditionalDirection:0 as const,rationale:`no directional inference retained: ${x.rationale}`})),confidence:clamp(1-m.confidence*0.5),stage:"RESEARCHING",evidenceRefs:[...m.evidenceRefs]});for(const x of m.affectedAssets)assetImpacts.push({impactId:sid(["impact",hold,x.assetId]),assetId:x.assetId,observedAt,mechanismId:m.mechanismId,scenarioId:hold,conditionalDirection:x.conditionalDirection,confidence:m.confidence,rationale:x.rationale,stage:"RESEARCHING",directAlphaInfluence:false,evidenceRefs:[...m.evidenceRefs]});}
  return{observedAt,eventFrames,entityObservations,relationAssertions,narrativeSnapshots,futureEvents,causalMechanisms,scenarios,assetImpacts,evidenceClass:EVOLUTION_EVIDENCE_CLASS,shadowOnly:true,liveExecution:false,directAlphaInfluence:false};
}
