const{test}=require('node:test'),a=require('node:assert/strict'),{project}=require('../monster-coins-pro/brian-command-model.js');const now=Date.now(),t=new Date(now-1000).toISOString();const rows=['world','behavior','alpha','treasury','research','ocean'].map(key=>({key,state:'ok',meta:'record'}));const h={status:"OK",behavior:{pipeline_status:"SUCCESS",pipeline_observed_at:t},observed_at:t,control:{system_enabled:true,treasury:{observed_at:t,equity_usd:5000}},alpha:{observed_at:t},world_run:{finished_at:t},collectors:{'brian-evolution-orchestrator-v1':{finished_at:t},'brian-evolution-ocean-worker-v1':{finished_at:t}}};
test('no heartbeat cannot be green',()=>a.equal(project(null,rows,null,now).live,0));
test('fresh evidence supports six module labels',()=>a.equal(project(h,rows,null,now).live,6));
test('cached, failed, stale and future heartbeat cannot be live',()=>{for(const hb of [{...h,__cached:true},{...h,observed_at:new Date(now-121000).toISOString()},{...h,observed_at:new Date(now+1000).toISOString()}])a.equal(project(hb,rows,null,now).live,0);a.equal(project(h,rows,'error',now).live,0)});
test('future module evidence is rejected even if legacy status says ok',()=>a.equal(project({...h,alpha:{observed_at:new Date(now+1000).toISOString()}},rows,null,now).modules.find(m=>m.key==='alpha').state,'waiting'));
test('stopped system never shows working',()=>a(project({...h,control:{system_enabled:false}},rows,null,now).modules.every(m=>m.state==='off')));
test('missing cash stays unknown and old snapshot labeled stale',()=>{a.equal(project(null).equity,null);a.equal(project({...h,control:{treasury:{equity_usd:5000,observed_at:'2020-01-01'}}},rows,null,now).treasuryFresh,false)});

test("heartbeat without successful status is not healthy",()=>a.equal(project({...h,status:undefined},rows,null,now).live,0));
