const{test}=require('node:test'),a=require('node:assert/strict'),{project,num}=require('../monster-coins-pro/treasury-accounting-model.js');const t='2026-09-16T06:00:00Z';const open={action_id:'o',position_id:'p',kind:'OPEN',asset_id:'BTC',direction:1,capital_usd:1000,reference_price:100,cost_usd:1,observed_at:'2026-09-15T06:00:00Z'};const exit={...open,action_id:'e',kind:'EXIT',reference_price:110,cost_usd:2,observed_at:t};const data={snapshot:{observed_at:t,starting_equity_usd:1000,equity_usd:1097,realized_pnl_usd:97},actions:[exit,open],history:[]};
test('long gain and fees match ledger, no double deduction',()=>{const v=project(data);a(Math.abs(v.knownRealized-97)<1e-9);a(Math.abs(v.rows[0].net-97)<1e-9);a.equal(v.cost,3);a.equal(v.total,97)});
test('short loss uses signed return',()=>{const v=project({...data,actions:[{...open,direction:-1},{...exit,direction:-1}]});a(Math.abs(v.knownRealized+103)<1e-9)});
test('missing or ambiguous opening stays unknown',()=>{for(const actions of [[exit],[exit,open,{...open,action_id:'o2'}]])a.equal(project({...data,actions}).rows[0].net,null)});
test('period exit uses older matched entry but charges only exit-period ledger cost',()=>{const v=project({...data,actions:[exit],opening_actions:[{...open,observed_at:'2026-09-10T00:00:00Z'}]},1);a(Math.abs(v.knownRealized-98)<1e-9);a(Math.abs(v.rows[0].net-97)<1e-9);a.equal(v.cost,2)});
test('missing data is not numeric zero',()=>{a.equal(num(null),null);a.equal(project({}).equity,null);a.equal(project({...data,actions:[{...exit,cost_usd:null},open]}).rows[0].realized,null)});
test('future records and duplicates excluded',()=>a.equal(project({...data,actions:[open,open,{...exit,observed_at:'2027-01-01'}]}).rows.length,1));
test('wrong asset or partial capital cannot be falsely paired',()=>{for(const patch of [{asset_id:'ETH'},{capital_usd:500}])a.equal(project({...data,actions:[open,{...exit,...patch}]}).rows[0].net,null)});
test('open net contribution is fee only, not invested capital',()=>a.equal(project({...data,actions:[open]}).knownRealized,-1));
