import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!, KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const EVIDENCE="AGGRESSIVE_DIP_SHADOW";
const ORIGIN=/^https:\/\/monster-coins(?:-pro)?-[a-z0-9-]*oemer-yildirim\.vercel\.app$/i;
const EXACT=new Set(["https://monster-coins-pro-seven.vercel.app","https://monster-coins-pro-oemer-yildirim.vercel.app","http://localhost:3000","http://127.0.0.1:3000"]);
const KINDS=new Set(["ENGINE_START","ENGINE_PAUSE","DIP_ARMED","DIP_NEW_LOW","BUY","SELL","SKIP_CHASE","NO_CASH","INFO"]);
type Row={event_id:string;session_id:string;event_kind:"START"|"PAUSE";requested_at:string;starting_equity:number|string|null;trade_notional:number|string|null;config:Record<string,unknown>|null;engine_token_sha256:string|null};
type S={start:Row;last:Row;active:boolean;ended_at:string|null};
function cors(o:string|null){let a=o&&(EXACT.has(o)||ORIGIN.test(o))?o:"https://monster-coins-pro-oemer-yildirim.vercel.app";return{"access-control-allow-origin":a,"access-control-allow-headers":"content-type,x-brian-dashboard-key","access-control-allow-methods":"POST,OPTIONS","vary":"Origin"}}
function out(x:unknown,status=200,o:string|null=null){return new Response(JSON.stringify(x),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...cors(o)}})}
async function sha(s:string){let b=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)));return[...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
function same(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function num(v:unknown,n:string){let x=Number(v);if(!Number.isFinite(x))throw Error(`INVALID_${n}`);return x}
function object(v:unknown,n:string,max:number){if(!v||typeof v!=="object"||Array.isArray(v))throw Error(`INVALID_${n}`);let s=JSON.stringify(v);if(new TextEncoder().encode(s).byteLength>max)throw Error(`${n}_TOO_LARGE`);return v as Record<string,unknown>}
async function auth(req:Request){let k=(req.headers.get("x-brian-dashboard-key")??"").trim();if(!k)throw Error("UNAUTHORIZED_DASHBOARD");let q=await db.from("brian_dashboard_auth").select("dashboard_key_sha256,created_at").order("created_at",{ascending:false}).limit(1).maybeSingle();if(q.error||!q.data)throw Error("UNAUTHORIZED_DASHBOARD");if(!same(await sha(k),String(q.data.dashboard_key_sha256)))throw Error("UNAUTHORIZED_DASHBOARD")}
async function latest():Promise<S|null>{let q=await db.from("brian_dip_session_events").select("event_id,session_id,event_kind,requested_at,starting_equity,trade_notional,config,engine_token_sha256").order("requested_at",{ascending:false}).order("event_id",{ascending:false}).limit(1).maybeSingle();if(q.error)throw q.error;if(!q.data)return null;let last=q.data as Row, z=await db.from("brian_dip_session_events").select("event_id,session_id,event_kind,requested_at,starting_equity,trade_notional,config,engine_token_sha256").eq("session_id",last.session_id).eq("event_kind","START").order("requested_at",{ascending:true}).limit(1).single();if(z.error||!z.data)throw Error("DIP_START_MISSING");return{start:z.data as Row,last,active:last.event_kind==="START",ended_at:last.event_kind==="PAUSE"?last.requested_at:null}}
async function engine(s:S,b:Record<string,unknown>){if(!s.active)throw Error("DIP_SESSION_PAUSED");if(String(b.session_id??"")!==s.start.session_id)throw Error("STALE_DIP_SESSION");let t=String(b.engine_token??"").trim(),expected=String(s.start.engine_token_sha256??"");if(t.length<20||!expected||!same(await sha(t),expected))throw Error("UNAUTHORIZED_DIP_ENGINE")}
function settings(b:Record<string,unknown>){let starting=num(b.starting_equity??500,"STARTING_EQUITY"),trade=num(b.trade_notional??5,"TRADE_NOTIONAL");if(starting<=0||starting>1e6)throw Error("STARTING_EQUITY_OUT_OF_RANGE");if(trade<=0||trade>starting)throw Error("TRADE_NOTIONAL_OUT_OF_RANGE");let i=object(b.config??{},"CONFIG",20000),raw=Array.isArray(i.symbols)?i.symbols:[],symbols=[...new Set(raw.map(x=>String(x).toUpperCase().trim()))].filter(x=>/^[A-Z0-9]{5,20}$/.test(x)).slice(0,10);if(!symbols.length)throw Error("NO_SYMBOLS");let n=(k:string,f:number,min:number,max:number)=>{let v=num(i[k]??f,k.toUpperCase());if(v<min||v>max)throw Error(`${k.toUpperCase()}_OUT_OF_RANGE`);return v};let config={symbols,interval:"1m",step_pct:n("step_pct",.15,.01,10),dip_trigger_steps:n("dip_trigger_steps",2,.25,100),rebound_steps:n("rebound_steps",1,.1,100),take_profit_steps:n("take_profit_steps",3,.1,200),max_chase_steps:n("max_chase_steps",5,.25,500),fee_bps:n("fee_bps",10,0,500),slippage_bps:n("slippage_bps",1,0,500),engine_version:"aggressive-dip-v1"};if(config.max_chase_steps<=config.rebound_steps)throw Error("MAX_CHASE_MUST_EXCEED_REBOUND");return{starting,trade,config}}
async function status(){let s=await latest(),base={schema_version:"brian.aggressive-dip.status.v1",generated_at:new Date().toISOString(),evidence_class:EVIDENCE,shadow_only:true,live_execution:false};if(!s)return{...base,session:null,snapshot:null,events:[]};let [z,e]=await Promise.all([db.from("brian_dip_snapshots").select("snapshot_id,session_id,observed_at,cash,equity,realized_pnl,unrealized_pnl,trade_count,win_count,loss_count,state").eq("session_id",s.start.session_id).order("observed_at",{ascending:false}).limit(1).maybeSingle(),db.from("brian_dip_events").select("event_id,session_id,observed_at,event_kind,symbol,price,dip_low,entry_price,exit_price,quantity,notional,fees,realized_pnl,cash_after,equity_after,metadata").eq("session_id",s.start.session_id).order("observed_at",{ascending:false}).limit(120)]);if(z.error)throw z.error;if(e.error)throw e.error;return{...base,session:{session_id:s.start.session_id,status:s.active?"RUNNING":"PAUSED",started_at:s.start.requested_at,ended_at:s.ended_at,starting_equity:Number(s.start.starting_equity),trade_notional:Number(s.start.trade_notional),config:s.start.config??{}},snapshot:z.data??null,events:e.data??[]}}
async function begin(b:Record<string,unknown>,restart=false){let {starting,trade,config}=settings(b),t=String(b.engine_token??"").trim();if(t.length<20||t.length>200)throw Error("INVALID_ENGINE_TOKEN");let id=`dip-${new Date().toISOString().replace(/[-:.TZ]/g,"").slice(0,14)}-${crypto.randomUUID().slice(0,8)}`,h=await sha(t),q=restart?await db.rpc("brian_dip_restart_session",{p_pause_event_id:`dip-evt-${crypto.randomUUID()}`,p_start_event_id:`dip-evt-${crypto.randomUUID()}`,p_new_session_id:id,p_starting_equity:starting,p_trade_notional:trade,p_config:config,p_engine_token_sha256:h}):await db.rpc("brian_dip_start_session",{p_event_id:`dip-evt-${crypto.randomUUID()}`,p_session_id:id,p_starting_equity:starting,p_trade_notional:trade,p_config:config,p_engine_token_sha256:h});if(q.error)throw q.error;return{status:restart?"RESTARTED":"STARTED",session_id:id,starting_equity:starting,trade_notional:trade,config,shadow_only:true,live_execution:false}}
async function pause(){let s=await latest();if(!s||!s.active)return{status:"ALREADY_PAUSED",shadow_only:true,live_execution:false};let q=await db.rpc("brian_dip_pause_session",{p_event_id:`dip-evt-${crypto.randomUUID()}`,p_session_id:s.start.session_id});if(q.error)throw q.error;return{status:"PAUSED",session_id:s.start.session_id,shadow_only:true,live_execution:false}}
function optional(b:Record<string,unknown>,k:string){if(b[k]==null||b[k]==="")return null;return num(b[k],k.toUpperCase())}
async function event(b:Record<string,unknown>){let s=await latest();if(!s)throw Error("NO_DIP_SESSION");await engine(s,b);let kind=String(b.event_kind??"").toUpperCase();if(!KINDS.has(kind))throw Error("INVALID_EVENT_KIND");let symbol=String(b.symbol??"").toUpperCase().trim()||null;if(symbol&&!/^[A-Z0-9]{5,20}$/.test(symbol))throw Error("INVALID_SYMBOL");let at=new Date(String(b.observed_at??new Date().toISOString()));if(!Number.isFinite(at.getTime()))throw Error("INVALID_OBSERVED_AT");let row={event_id:String(b.event_id??`dip-event-${crypto.randomUUID()}`),session_id:s.start.session_id,observed_at:at.toISOString(),event_kind:kind,symbol,price:optional(b,"price"),dip_low:optional(b,"dip_low"),entry_price:optional(b,"entry_price"),exit_price:optional(b,"exit_price"),quantity:optional(b,"quantity"),notional:optional(b,"notional"),fees:optional(b,"fees"),realized_pnl:optional(b,"realized_pnl"),cash_after:optional(b,"cash_after"),equity_after:optional(b,"equity_after"),metadata:object(b.metadata??{},"METADATA",25000),evidence_class:EVIDENCE,shadow_only:true,live_execution:false};let q=await db.from("brian_dip_events").insert(row);if(q.error)throw q.error;return{status:"RECORDED",event_id:row.event_id}}
async function snapshot(b:Record<string,unknown>){let s=await latest();if(!s)throw Error("NO_DIP_SESSION");await engine(s,b);let at=new Date(String(b.observed_at??new Date().toISOString()));if(!Number.isFinite(at.getTime()))throw Error("INVALID_OBSERVED_AT");let row={snapshot_id:String(b.snapshot_id??`dip-snap-${crypto.randomUUID()}`),session_id:s.start.session_id,observed_at:at.toISOString(),cash:num(b.cash,"CASH"),equity:num(b.equity,"EQUITY"),realized_pnl:num(b.realized_pnl??0,"REALIZED_PNL"),unrealized_pnl:num(b.unrealized_pnl??0,"UNREALIZED_PNL"),trade_count:Math.max(0,Math.trunc(num(b.trade_count??0,"TRADE_COUNT"))),win_count:Math.max(0,Math.trunc(num(b.win_count??0,"WIN_COUNT"))),loss_count:Math.max(0,Math.trunc(num(b.loss_count??0,"LOSS_COUNT"))),state:object(b.state??{},"STATE",150000),evidence_class:EVIDENCE,shadow_only:true,live_execution:false};let q=await db.from("brian_dip_snapshots").insert(row);if(q.error)throw q.error;return{status:"SNAPSHOT_RECORDED",snapshot_id:row.snapshot_id}}
Deno.serve(async(req:Request)=>{let o=req.headers.get("origin");if(req.method==="OPTIONS")return new Response("ok",{headers:cors(o)});if(req.method!=="POST")return out({status:"METHOD_NOT_ALLOWED"},405,o);try{await auth(req);let b=await req.json().catch(()=>({})) as Record<string,unknown>,a=String(b.action??"status").toLowerCase();if(a==="status")return out(await status(),200,o);if(a==="start")return out(await begin(b,false),200,o);if(a==="restart")return out(await begin(b,true),200,o);if(a==="pause")return out(await pause(),200,o);if(a==="engine_check"){let s=await latest();if(!s)throw Error("NO_DIP_SESSION");await engine(s,b);return out({status:"ENGINE_OK",session_id:s.start.session_id,shadow_only:true,live_execution:false},200,o)}if(a==="event")return out(await event(b),200,o);if(a==="snapshot")return out(await snapshot(b),200,o);return out({status:"UNKNOWN_ACTION",action:a},400,o)}catch(e){let m=String(e instanceof Error?e.message:e),u=m.includes("UNAUTHORIZED_");console.error("brian-dip-trader",{message:m,unauthorized:u});return out({status:u?"UNAUTHORIZED":"FAILED_CLOSED",error:m,evidence_class:EVIDENCE,shadow_only:true,live_execution:false},u?401:400,o)}});
