# -*- coding: utf-8 -*-
from __future__ import annotations
import time, json, random, re, importlib.util, sys
from pathlib import Path
from typing import Dict, Any, List

# Sessiz telegram
try:
    from Proje1.core.utils_io import tg_send
except Exception:
    def tg_send(*a, **k): pass

JOURNAL = Path("logs/forge_journal.jsonl"); JOURNAL.parent.mkdir(parents=True, exist_ok=True)

FORGE_BASE       = Path("live/forge");              FORGE_BASE.mkdir(parents=True, exist_ok=True)
STRAT_DIR        = FORGE_BASE / "strategies";       STRAT_DIR.mkdir(parents=True, exist_ok=True)
ADAPTER_DIR      = FORGE_BASE / "adapters";         ADAPTER_DIR.mkdir(parents=True, exist_ok=True)
CONFIG_FRAG_DIR  = FORGE_BASE / "config_fragments"; CONFIG_FRAG_DIR.mkdir(parents=True, exist_ok=True)
REQUEST_DIR      = FORGE_BASE / "requests";         REQUEST_DIR.mkdir(parents=True, exist_ok=True)

DEFAULTS = {
    "enabled": True,
    "tick_sec": 20,
    "autowrite": True,           # KURALSIZ: otomatik yaz
    "auto_apply_config": True,   # config parçalarını runtime overrides’a akıt
    "max_files_per_tick": 3,
    "color_telegrams": True,
    "strategy_seed_rate": 0.25,  # her tik %25 yeni strateji tohumu
    "adapter_seed_rate":  0.10,  # her tik %10 yeni adapter tohumu
    "config_seed_rate":   0.20,  # her tik %20 yeni config fragmanı
}

_STATE = {"last_tick": 0.0}

def _cfg(d: Dict[str,Any], path: str, default=None):
    cur = d
    for k in path.split("."):
        if not isinstance(cur, dict) or k not in cur:
            return default
        cur = cur[k]
    return cur

def _j(rec: Dict[str,Any]):
    rec = {"ts": time.time(), **rec}
    try:
        with JOURNAL.open("a", encoding="utf-8") as f:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    except Exception:
        pass

# --------- tohum üreticiler (örnek/kuralsız) ---------
_STRAT_SEEDS = [
    # Çok agressif ensemble; guard yok, rasgele slot+confidence
    """# auto-generated by FORGE
import random
class Strategy:
    def __init__(self, cfg=None): self.cfg = cfg or {}
    def run_for_symbol(self, symbol, st):
        px = float(getattr(st,'last_px',0.0) or 0.0)
        if px <= 0: return []
        out=[]; n=1+int(random.random()*3)
        for _ in range(n):
            slot = random.choice(['pred','dip','news','ob'])
            conf = max(0.25, min(1.0, random.random()*1.0))
            out.append({'slot':slot,'confidence':conf,'reason':f'FORGE:{slot}'})
        return out
def create(cfg=None): return Strategy(cfg)
""",
    # “regime-agnostic microburst”
    """# auto-generated by FORGE
import random, math
class Strategy:
    def __init__(self, cfg=None): self.cfg = cfg or {}; self.k=random.random()
    def run_for_symbol(self, symbol, st):
        px=float(getattr(st,'last_px',0.0) or 0.0); 
        if px<=0: return []
        r=random.random(); out=[]
        if r<0.5:
            slot=random.choice(['pred','ob'])
            conf = 0.4 + 0.6*random.random()
            out.append({'slot':slot,'confidence':conf,'reason':'BURST'})
        if r>0.7:
            out.append({'slot':'dip','confidence':0.35+0.5*random.random(),'reason':'MEANREACT'})
        return out
def create(cfg=None): return Strategy(cfg)
""",
]

_ADAPTER_SEEDS = [
    # basit “custom alpha” sağlayıcı
    """# auto-generated by FORGE
from math import sin
def alpha(symbol, t):
    # pseudo-flow: sin zamanlı varyasyon
    return 0.5 + 0.5*sin(t/60.0)
""",
]

_CONFIG_SEEDS = [
    {"brain": {"adjust":{"trend_tp_mult":1.05 + round(random.random()*0.1,2)}}},
    {"dyn_alloc":{"step":0.05 + round(random.random()*0.05,2)}},
    {"predictor":{"weights":{"vol": round(0.2+random.random()*0.6,2)}}},
]

def _rand_name(prefix: str, ext: str) -> str:
    return f"{prefix}_{int(time.time())}_{int(1e6*random.random())}.{ext}"

def _write(path: Path, text: str):
    path.write_text(text, encoding="utf-8")
    _j({"kind":"write", "path": str(path)})

def _write_json(path: Path, obj: Dict[str,Any]):
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")
    _j({"kind":"write_json", "path": str(path)})

# --------- DIŞ API ---------
def ensure_forge(cfg: Dict[str,Any]) -> None:
    """Klasörler hazır, no-op."""
    _j({"kind":"ensure"})

def forge_tick(cfg: Dict[str,Any]) -> None:
    c = dict(DEFAULTS); c.update(_cfg(cfg,"forge",{}) or {})
    if not c.get("enabled", True): return
    now=time.time()
    if (now - _STATE["last_tick"]) < max(1,int(c.get("tick_sec",20))): return
    _STATE["last_tick"] = now

    autowrite = bool(c.get("autowrite", True))
    max_files = int(c.get("max_files_per_tick",3))
    left      = max_files

    # 1) pending request’ler (kullanıcı drop ederse) -> hemen yaz
    reqs = sorted(REQUEST_DIR.glob("*.json"))
    for r in reqs:
        if left<=0: break
        try:
            data=json.loads(r.read_text(encoding="utf-8"))
            kind=data.get("kind")
            if kind=="strategy":
                name=_rand_name("strat","py"); p=STRAT_DIR/name
                code=data.get("code") or random.choice(_STRAT_SEEDS)
                _write(p, code)
            elif kind=="adapter":
                name=_rand_name("adapter","py"); p=ADAPTER_DIR/name
                code=data.get("code") or random.choice(_ADAPTER_SEEDS)
                _write(p, code)
            elif kind=="config":
                name=_rand_name("frag","json"); p=CONFIG_FRAG_DIR/name
                frag=data.get("fragment") or random.choice(_CONFIG_SEEDS)
                _write_json(p, frag)
                if c.get("auto_apply_config", True):
                    _apply_config_fragment(cfg, frag)
            r.unlink(missing_ok=True)
            left -= 1
        except Exception as e:
            _j({"kind":"req_error","path": str(r),"err": str(e)})

    if not autowrite or left<=0:
        return

    # 2) KENDİ KENDİNE TOHUMLAMA (kuralsız üretim)
    if random.random() < float(c.get("strategy_seed_rate",0.25)) and left>0:
        name=_rand_name("auto_strat","py"); p=STRAT_DIR/name
        _write(p, random.choice(_STRAT_SEEDS)); left-=1
        try: tg_send(f"🟣 FORGE: Yeni strateji yazıldı → {name}")
        except Exception: pass

    if random.random() < float(c.get("adapter_seed_rate",0.10)) and left>0:
        name=_rand_name("auto_adapter","py"); p=ADAPTER_DIR/name
        _write(p, random.choice(_ADAPTER_SEEDS)); left-=1
        try: tg_send(f"🟦 FORGE: Yeni adapter yazıldı → {name}")
        except Exception: pass

    if random.random() < float(c.get("config_seed_rate",0.20)) and left>0:
        name=_rand_name("auto_frag","json"); p=CONFIG_FRAG_DIR/name
        frag=random.choice(_CONFIG_SEEDS)
        _write_json(p, frag); left-=1
        if c.get("auto_apply_config", True):
            _apply_config_fragment(cfg, frag)
        try: tg_send(f"🟩 FORGE: Config fragmanı yazıldı → {name}")
        except Exception: pass

def _apply_config_fragment(cfg: Dict[str,Any], frag: Dict[str,Any]) -> None:
    """
    Kuralsız: frag’ı runtime overrides’a akıt. (sadece düz merge-override)
    """
    try:
        ov_path = Path((cfg.get("runtime") or {}).get("overrides_path") or "runtime/runtime_overrides.jsonl")
        ov_path.parent.mkdir(parents=True, exist_ok=True)
        with ov_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps({"type":"forge_config","payload":frag,"ts":time.time()}, ensure_ascii=False)+"\n")
        _j({"kind":"apply_config","to": str(ov_path)})
    except Exception as e:
        _j({"kind":"apply_config_error","err": str(e)})
