import { createClient } from "npm:@supabase/supabase-js@2.116.0";
import type { SupabaseClient } from "npm:@supabase/supabase-js@2.116.0";

const RELEASE_ID="dip-v841-brian-authority-20260911.1";
const POLICY_VERSION="dip-v841-brian-authority-20260911.1";
const METRIC_VERSION="target-before-invalidation-v841.1";
const RESOLVER_VERSION="dip-v841-path-20260911.1";
const LOGIC_HASH="git:b16ada5b40e5da2b9766946ddd83647e6c299763";
const STRATEGY_MANIFEST_HASH="1b9bc41c4edd2f0b9896be316843bde4cd27b67793d4d3912fb3450fe47ee7f1";
const CALIBRATION_FAMILY_ID="dip-v841-brian-authority-family-1";
const SYMBOL="ETHUSDT";
const LEASE_KEY="brian-dip-v84-foresight";
const HOSTS=["https://fapi.binance.com","https://fapi1.binance.com","https://fapi2.binance.com"];
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const EXACT=new Set(["https://monster-coins-pro-seven.vercel.app","https://monster-coins-pro-oemer-yildirim.vercel.app","http://localhost:3000","http://127.0.0.1:3000"]);
const ORIGIN=/^https:\/\/monster-coins(?:-pro)?-[a-z0-9-]*oemer-yildirim\.vercel\.app$/i;
function headers(origin:string|null){return{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":origin&&(EXACT.has(origin)||ORIGIN.test(origin))?origin:"https://monster-coins-pro-seven.vercel.app","access-control-allow-headers":"content-type,x-brian-dashboard-key,x-brian-cron-key,authorization,apikey","access-control-allow-methods":"POST,OPTIONS","vary":"Origin"};}
async function sha256(s:string){const b=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)));return [...b].map(x=>x.toString(16).padStart(2,"0")).join("");}
function same(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function requireCronAuth(req:Request){const supplied=(req.headers.get("x-brian-cron-key")||"").trim();if(!supplied)throw Error("UNAUTHORIZED_CRON");const q=await db.from("brian_dashboard_auth").select("cron_key_sha256").eq("auth_id","control-v3").single();if(q.error||!q.data)throw Error("CRON_AUTH_UNAVAILABLE");if(!same(await sha256(supplied),String(q.data.cron_key_sha256||"")))throw Error("UNAUTHORIZED_CRON");}
async function authorize(req:Request):Promise<"reader"|"cron">{const key=(req.headers.get("x-brian-dashboard-key")||"").trim();if(!key){await requireCronAuth(req);return"cron";}const q=await db.from("brian_dashboard_auth").select("dashboard_key_sha256").eq("auth_id","control-v3").single();if(q.error||!q.data||!same(await sha256(key),String(q.data.dashboard_key_sha256||"")))throw Error("UNAUTHORIZED_DASHBOARD");return"reader";}
async function marketJson(path:string){let err="MARKET_UNAVAILABLE";for(const host of HOSTS){try{const r=await fetch(host+path,{method:"GET",headers:{accept:"application/json","user-agent":"Brian-DIP-V8.4.1-Foresight/1.0"},signal:AbortSignal.timeout(5500)});if(!r.ok){err="HTTP_"+r.status;if([418,429].includes(r.status))break;continue;}return await r.json();}catch(e){err=e instanceof Error?e.message:String(e);}}throw Error("BINANCE_USDM:"+err);}
async function assertRelease(){const q=await db.from("brian_dip_v84_releases").select("status,logic_hash,strategy_manifest_hash,calibration_family_id,manifest").eq("release_id",RELEASE_ID).maybeSingle();if(q.error||!q.data)throw Error("V841_RELEASE_REGISTRY_UNAVAILABLE");if(q.data.status!=="SEALED"||q.data.logic_hash!==LOGIC_HASH||q.data.strategy_manifest_hash!==STRATEGY_MANIFEST_HASH||q.data.calibration_family_id!==CALIBRATION_FAMILY_ID)throw Error("V841_RELEASE_REGISTRY_MISMATCH");if(q.data.manifest?.shadow_only!==true||q.data.manifest?.live_execution!==false||q.data.manifest?.browser_execution!==false||Number(q.data.manifest?.max_shadow_leverage)!==1)throw Error("V841_RELEASE_SAFETY_MISMATCH");}

async function withLease<T>(work:(assertOwned:()=>void)=>Promise<T>):Promise<{contended:boolean;value?:T}>{const owner=crypto.randomUUID(),seconds=55;const a=await db.rpc("brian_dip_v84_acquire_lease",{p_lease_key:LEASE_KEY,p_owner_id:owner,p_lease_seconds:seconds});if(a.error)throw Error("V841_FORECAST_LEASE_READ_FAILED:"+a.error.message);const row=Array.isArray(a.data)?a.data[0]:a.data;if(!row||row.acquired!==true)return{contended:true};const generation=Number(row.lease_generation);let lost=false,finished=false;const timer=setInterval(async()=>{try{const r=await db.rpc("brian_dip_v84_renew_lease",{p_lease_key:LEASE_KEY,p_owner_id:owner,p_lease_generation:generation,p_lease_seconds:seconds});if(r.error||r.data!==true)lost=true;}catch{lost=true;}if(lost||finished)clearInterval(timer);},18000);const assertOwned=()=>{if(lost)throw Error("V841_FORECAST_LEASE_LOST");};try{return{contended:false,value:await work(assertOwned)};}finally{finished=true;clearInterval(timer);await db.rpc("brian_dip_v84_release_lease",{p_lease_key:LEASE_KEY,p_owner_id:owner,p_lease_generation:generation});}}

type Row={occurrence_id:string;decision_at:string;due_at:string;direction:"UP"|"DOWN";target_price:number;invalidation_price:number;entry_price:number;checked_until:string|null;last_price:number|null};
type Eval={reason:"TARGET_FIRST"|"INVALIDATION_FIRST"|"AMBIGUOUS"|"EXPIRED_NO_BARRIER"|"PENDING";hit:boolean|null;price:number;eventAt:number|null;checkedUntil:number;eventRangeStart:number|null;detail?:string};
async function tradesFirst(start:number,end:number,direction:"UP"|"DOWN",target:number,stop:number):Promise<Eval|null>{const raw=await marketJson(`/fapi/v1/aggTrades?symbol=${SYMBOL}&startTime=${Math.max(0,Math.floor(start))}&endTime=${Math.max(0,Math.floor(end-1))}&limit=1000`);if(!Array.isArray(raw))return null;for(const x of raw as any[]){const t=Number(x.T),p=Number(x.p);if(!(t>=start&&t<end&&p>0))continue;const win=direction==="UP"?p>=target:p<=target,loss=direction==="UP"?p<=stop:p>=stop;if(loss)return{reason:"INVALIDATION_FIRST",hit:false,price:p,eventAt:t,checkedUntil:end,eventRangeStart:t};if(win)return{reason:"TARGET_FIRST",hit:true,price:p,eventAt:t,checkedUntil:end,eventRangeStart:t};}return null;}
async function evaluate(row:Row):Promise<Eval>{const start=Date.parse(row.checked_until||row.decision_at),due=Date.parse(row.due_at),now=Date.now(),end=Math.min(due,Math.floor(now/60000)*60000);const entry=Number(row.last_price||row.entry_price),target=Number(row.target_price),stop=Number(row.invalidation_price);if(!(start<due&&target>0&&stop>0&&entry>0))throw Error("V841_INVALID_FORECAST_ROW");if(end<=start)return{reason:"PENDING",hit:null,price:entry,eventAt:null,checkedUntil:start,eventRangeStart:null};let cursor=start,last=entry;const firstBoundary=Math.min(end,Math.ceil(cursor/60000)*60000);if(cursor%60000!==0&&firstBoundary>cursor){const first=await tradesFirst(cursor,firstBoundary,row.direction,target,stop);if(first)return first;cursor=firstBoundary;}if(cursor<end){const raw=await marketJson(`/fapi/v1/klines?symbol=${SYMBOL}&interval=1m&startTime=${cursor}&endTime=${end-1}&limit=1000`);if(!Array.isArray(raw))throw Error("V841_KLINES_INVALID");for(const k of raw as any[]){const ot=Number(k[0]),h=Number(k[2]),l=Number(k[3]),c=Number(k[4]),ct=Number(k[6])+1;if(ot<cursor||ot>=end)continue;const segEnd=Math.min(ct,end);const win=row.direction==="UP"?h>=target:l<=target,loss=row.direction==="UP"?l<=stop:h>=stop;if(win&&loss){const exact=await tradesFirst(Math.max(cursor,ot),segEnd,row.direction,target,stop);if(exact)return exact;return{reason:"AMBIGUOUS",hit:false,price:c,eventAt:segEnd,eventRangeStart:Math.max(cursor,ot),checkedUntil:segEnd,detail:"BOTH_BARRIERS_SAME_CANDLE"};}if(loss)return{reason:"INVALIDATION_FIRST",hit:false,price:row.direction==="UP"?stop:stop,eventAt:segEnd,eventRangeStart:Math.max(cursor,ot),checkedUntil:segEnd};if(win)return{reason:"TARGET_FIRST",hit:true,price:target,eventAt:segEnd,eventRangeStart:Math.max(cursor,ot),checkedUntil:segEnd};last=c;cursor=segEnd;}}
if(end>=due)return{reason:"EXPIRED_NO_BARRIER",hit:false,price:last,eventAt:due,eventRangeStart:due,checkedUntil:due};return{reason:"PENDING",hit:null,price:last,eventAt:null,eventRangeStart:null,checkedUntil:end};}

async function resolvePending(assertOwned:()=>void){await assertRelease();const q=await db.from("brian_dip_v84_decisions").select("occurrence_id,decision_at,due_at,direction,target_price,invalidation_price,entry_price,checked_until,last_price").eq("release_id",RELEASE_ID).eq("policy_version",POLICY_VERSION).eq("metric_version",METRIC_VERSION).not("target_price","is",null).not("invalidation_price","is",null).is("resolved_at",null).order("checked_until",{ascending:true,nullsFirst:true}).order("decision_at",{ascending:true}).limit(24);if(q.error)throw Error("V841_FORECAST_READ_FAILED:"+q.error.message);let resolved=0,progressed=0,deferred=0;for(const row of (q.data||[]) as Row[]){assertOwned();try{const r=await evaluate(row);if(r.checkedUntil<=Date.parse(row.checked_until||row.decision_at))continue;const done=r.reason!=="PENDING",recordedAt=new Date().toISOString(),values:any={checked_until:new Date(r.checkedUntil).toISOString(),last_price:r.price};if(done)Object.assign(values,{resolved_at:recordedAt,hit:r.hit,resolution:{...r,resolver_version:RESOLVER_VERSION,recorded_at:recordedAt,event_time_precision:r.eventRangeStart===r.eventAt?"TRADE_OR_DEADLINE":"CANDLE_RANGE"}});let u=db.from("brian_dip_v84_decisions").update(values).eq("occurrence_id",row.occurrence_id).eq("release_id",RELEASE_ID).is("resolved_at",null);u=row.checked_until?u.eq("checked_until",row.checked_until):u.is("checked_until",null);const s=await u.select("occurrence_id");if(s.error)throw Error(s.error.message);if(s.data?.length){progressed++;if(done)resolved++;}}catch(e){deferred++;console.error("v841 foresight defer",row.occurrence_id,e instanceof Error?e.message:String(e));}}return{status:"OK",resolved,progressed,deferred,resolver_version:RESOLVER_VERSION,release_id:RELEASE_ID,policy_version:POLICY_VERSION,decision_authority:"BRIAN",shadow_only:true,live_execution:false,browser_execution:false};}
async function readForesight(sessionId?:string){await assertRelease();const s=await db.from("brian_dip_v84_session_events").select("session_id,requested_at,config").eq("event_kind","START").contains("config",{release_id:RELEASE_ID}).order("requested_at",{ascending:false}).order("event_id",{ascending:false}).limit(1).maybeSingle();const base={forecasts:{},focus:[SYMBOL],shadow_only:true,live_execution:false,browser_execution:false,decision_authority:"BRIAN",release_id:RELEASE_ID,policy_version:POLICY_VERSION,metric_version:METRIC_VERSION};if(s.error)throw Error("V841_START_READ_FAILED");if(!s.data)return{...base,status:"NO_ACTIVE_SESSION"};const sid=String(s.data.session_id);if(sessionId&&sessionId!==sid)return{...base,status:"STALE_SESSION",session_id:sid};const r=await db.from("brian_dip_v84_runtime").select("runtime,updated_at,state_version").eq("session_id",sid).maybeSingle();if(r.error||!r.data)throw Error("V841_RUNTIME_READ_FAILED");const t=r.data.runtime?.latestThesis;if(!t)return{...base,status:"WAIT_STRUCTURE",session_id:sid,state_version:r.data.state_version};return{...base,status:"OK",session_id:sid,state_version:r.data.state_version,updated_at:r.data.updated_at,forecasts:{[SYMBOL]:{...t,symbol:SYMBOL,target:t.target_price,invalidation:t.invalidation_price,confidence:t.authority_confidence??t.raw_conviction,position:r.data.runtime?.pos??null,horizon_min:90}}};}

Deno.serve(async(req:Request)=>{const h=headers(req.headers.get("origin"));if(req.method==="OPTIONS")return new Response("ok",{headers:h});if(req.method!=="POST")return new Response("method",{status:405,headers:h});try{const mode=await authorize(req);if(mode==="cron"){const r=await withLease(resolvePending);return Response.json(r.contended?{status:"WAIT_LEASE",release_id:RELEASE_ID,decision_authority:"BRIAN",shadow_only:true,live_execution:false}:r.value,{headers:h});}const body=await req.json().catch(()=>({}));return Response.json(await readForesight(typeof body.session_id==="string"?body.session_id:undefined),{headers:h});}catch(e){const message=e instanceof Error?e.message:String(e);return Response.json({status:"FAILED_CLOSED",error:message,release_id:RELEASE_ID,decision_authority:"BRIAN",shadow_only:true,live_execution:false,browser_execution:false},{status:message.includes("UNAUTHORIZED")?401:500,headers:h});}});
