import { createClient } from "npm:@supabase/supabase-js@2";
import { gzip } from "npm:pako@2.1.0";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!; const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const supabase=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const COLLECTOR_ID="phase39-gdelt-news"; const EVIDENCE="PROSPECTIVE_DEVELOPMENT_SHADOW"; const BUCKET="brian-intelligence-raw";
const GDELT="https://api.gdeltproject.org/api/v2/doc/doc?query=(bitcoin%20OR%20ethereum%20OR%20solana%20OR%20xrp%20OR%20cryptocurrency%20OR%20crypto%20OR%20binance%20OR%20gold%20OR%20silver%20OR%20oil%20OR%20Federal%20Reserve%20OR%20ECB)&mode=ArtList&maxrecords=75&format=json&sort=HybridRel&timespan=30min";
const POS=["approval","approved","partnership","launch","record high","inflow","rally","surge","upgrade","adoption","buyback"];
const NEG=["hack","hacked","exploit","ban","lawsuit","outflow","crash","fraud","liquidation","breach","attack","downgrade"];

type Article={url?:string;title?:string;seendate?:string;domain?:string;language?:string;sourcecountry?:string};
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}})}
function bytes(s:string){return new TextEncoder().encode(s)} async function sha(v:string|Uint8Array){const b=typeof v==="string"?bytes(v):v;const d=new Uint8Array(await crypto.subtle.digest("SHA-256",b));return [...d].map(x=>x.toString(16).padStart(2,"0")).join("")}
function clip(v:number){return Math.max(0,Math.min(1,v))} function sign(v:number){return v>0?1:v<0?-1:0}
function parseSeen(v?:string){if(!v)return null;const m=v.match(/^(\d{4})(\d{2})(\d{2})T?(\d{2})(\d{2})(\d{2})Z?$/);if(!m)return null;const d=new Date(`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`);return Number.isFinite(d.getTime())?d.toISOString():null}
function asset(title:string){const t=title.toLowerCase();if(/bitcoin|\bbtc\b/.test(t))return "BTCUSDT";if(/ethereum|\beth\b/.test(t))return "ETHUSDT";if(/solana|\bsol\b/.test(t))return "SOLUSDT";if(/\bxrp\b|ripple/.test(t))return "XRPUSDT";if(/binance coin|\bbnb\b/.test(t))return "BNBUSDT";if(/gold/.test(t))return "GOLD";if(/silver/.test(t))return "SILVER";if(/\boil\b|brent|wti/.test(t))return "OIL";if(/federal reserve|\bfed\b|ecb|interest rate|inflation/.test(t))return "MACRO";return "CRYPTO_MARKET"}
function pressure(title:string){const t=title.toLowerCase();const p=POS.filter(w=>t.includes(w)).length,n=NEG.filter(w=>t.includes(w)).length;if(p>0&&n===0)return 1;if(n>0&&p===0)return -1;return 0}
async function rawCapture(payload:unknown,at:string){const canonical=JSON.stringify(payload),raw=bytes(canonical),hash=await sha(raw),z=gzip(raw,{level:6});const path=`gdelt/phase39_news/${at.slice(0,10)}/${hash}.json.gz`;const up=await supabase.storage.from(BUCKET).upload(path,z,{contentType:"application/gzip",upsert:false,cacheControl:"31536000"});if(up.error&&!String(up.error.message).toLowerCase().match(/exist|duplicate/))throw up.error;const id=await sha(`gdelt|phase39_news|${at}|${hash}`);const ins=await supabase.from("brian_raw_captures").insert({capture_id:id,provider:"gdelt_doc2",record_type:"phase39_news",observed_at:at,captured_at:new Date().toISOString(),provenance_uri:"https://api.gdeltproject.org/api/v2/doc/doc",payload_hash:hash,payload:{storage_bucket:BUCKET,storage_path:path,content_type:"application/json",content_encoding:"gzip"}});if(ins.error)throw ins.error;return id}
async function recordRun(start:string,status:string,observed:number,stored:number,error?:unknown){const end=new Date().toISOString(),id=await sha(`${COLLECTOR_ID}|${start}|${end}|${status}`);await supabase.from("brian_collector_runs").insert({run_id:id,collector_id:COLLECTOR_ID,started_at:start,finished_at:end,status,observed_records:observed,stored_records:stored,degraded_sources:[],error_class:error?"COLLECTOR_ERROR":null,error_message:error?String(error).slice(0,1000):null,evidence_class:EVIDENCE,shadow_only:true,live_execution:false})}

Deno.serve(async req=>{if(req.method!=="POST")return out({error:"POST required"},405);const started=new Date().toISOString();try{
 const r=await fetch(GDELT,{headers:{accept:"application/json","user-agent":"Brian-2026-News-Eye/1.0"},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`GDELT ${r.status}`);const payload=await r.json();const observedAt=new Date().toISOString();const captureId=await rawCapture(payload,observedAt);const articles=Array.isArray(payload?.articles)?payload.articles as Article[]:[];
 const events:Record<string,unknown>[]=[];const grouped=new Map<string,{dirs:number[];domains:Set<string>;events:string[]}>();
 for(const a of articles){const url=String(a.url??"").trim(),title=String(a.title??"").trim();if(!url||!title)continue;const aId=asset(title),dir=pressure(title),fingerprint=await sha(`${url}|${title}`),eventId=await sha(`gdelt|${fingerprint}`),published=parseSeen(a.seendate);events.push({event_id:eventId,asset:aId,event_kind:"NEWS_HEADLINE",source_kind:"GDELT_DISCOVERY",source_id:String(a.domain??"unknown"),published_at:published,first_observed_at:observedAt,captured_at:new Date().toISOString(),claim:title,direction:dir,magnitude:dir===0?0.25:0.5,trust_class:"UNVERIFIED_DISCOVERY",entity_confidence:0.4,content_fingerprint:fingerprint,corroboration_key:await sha(`${aId}|${title.toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}`),provenance_uri:url,pit_verified:true,raw_capture_id:captureId,metadata:{gdelt_seen_at:published,domain:a.domain,language:a.language,source_country:a.sourcecountry,headline_pressure_only:true}});const g=grouped.get(aId)??{dirs:[],domains:new Set<string>(),events:[]};g.dirs.push(dir);if(a.domain)g.domains.add(a.domain);g.events.push(eventId);grouped.set(aId,g)}
 if(events.length){const ins=await supabase.from("brian_intel_events").upsert(events,{onConflict:"event_id",ignoreDuplicates:true});if(ins.error)throw ins.error}
 const observations:Record<string,unknown>[]=[];for(const [aId,g] of grouped){const avg=g.dirs.length?g.dirs.reduce((x,y)=>x+y,0)/g.dirs.length:0;const direction=Math.abs(avg)>=0.25?sign(avg):0;const strength=direction?clip(Math.abs(avg)*Math.min(1,g.dirs.length/8)):clip(g.dirs.length/25);const confidence=clip(0.35+0.05*Math.min(6,g.domains.size));const eye=await sha(`gdelt-headline-pressure|${aId}`),obs=await sha(`${eye}|${observedAt}|${direction}|${g.events.join(",")}`);observations.push({observation_id:obs,eye_id:eye,template_id:"gdelt-headline-pressure",asset_id:aId.startsWith("BTC")||aId.startsWith("ETH")||aId.startsWith("SOL")||aId.startsWith("XRP")||aId.startsWith("BNB")?`crypto:${aId}`:`global:${aId}`,market_domain:aId==="MACRO"?"macro":aId==="GOLD"||aId==="SILVER"||aId==="OIL"?"commodity":"news",sensor_family:"news_attention",horizon:"EVENT_DRIVEN",independent_group:"news_gdelt",observed_at:observedAt,direction,strength,confidence,reliability:0.4,available:true,source_ids:[captureId],reason:`GDELT ${g.dirs.length} headlines across ${g.domains.size} domains; directional headline pressure=${avg.toFixed(3)}`,evidence_class:EVIDENCE,shadow_only:true,live_execution:false,metadata:{event_ids:g.events,independent_domains:g.domains.size,headline_pressure_only:true,not_source_truth:true}})}
 if(observations.length){const ins=await supabase.from("brian_sensor_observations").insert(observations);if(ins.error)throw ins.error}await recordRun(started,"SUCCESS",articles.length,events.length+observations.length);return out({status:"CAPTURED",articles:articles.length,events:events.length,sensor_observations:observations.length,learning_enabled:false,live_execution:false,shadow_only:true});
}catch(e){await recordRun(started,"FAILED",0,0,e);return out({status:"FAILED",error:String(e),shadow_only:true},500)}});
