import { createClient } from "npm:@supabase/supabase-js@2";
import { gzip } from "npm:pako@2.1.0";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!,SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const supabase=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const COLLECTOR_ID="phase39-ecb-fx",EVIDENCE="PROSPECTIVE_DEVELOPMENT_SHADOW",BUCKET="brian-intelligence-raw";
const URL="https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml";const CURRENCIES=["USD","GBP","JPY","CHF"];
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}})}function bytes(s:string){return new TextEncoder().encode(s)}async function sha(v:string|Uint8Array){const b=typeof v==="string"?bytes(v):v,d=new Uint8Array(await crypto.subtle.digest("SHA-256",b));return [...d].map(x=>x.toString(16).padStart(2,"0")).join("")}function clip(v:number){return Math.max(0,Math.min(1,v))}function sign(v:number){return v>0?1:v<0?-1:0}
function parse(xml:string){const blocks=[...xml.matchAll(/<Cube\s+time=['\"]([^'\"]+)['\"]>([\s\S]*?)<\/Cube>/g)].map(m=>({date:m[1],body:m[2]}));return blocks.map(b=>{const rates:Record<string,number>={};for(const m of b.body.matchAll(/<Cube\s+currency=['\"]([A-Z]{3})['\"]\s+rate=['\"]([^'\"]+)['\"]\s*\/>/g))rates[m[1]]=Number(m[2]);return{date:b.date,rates}}).filter(x=>Object.keys(x.rates).length)}
async function rawCapture(xml:string,at:string){const raw=bytes(xml),hash=await sha(raw),z=gzip(raw,{level:6}),path=`ecb/phase39_fx/${at.slice(0,10)}/${hash}.xml.gz`;const up=await supabase.storage.from(BUCKET).upload(path,z,{contentType:"application/gzip",upsert:false,cacheControl:"31536000"});if(up.error&&!String(up.error.message).toLowerCase().match(/exist|duplicate/))throw up.error;const id=await sha(`ecb|phase39_fx|${at}|${hash}`);const ins=await supabase.from("brian_raw_captures").insert({capture_id:id,provider:"ecb_reference_fx",record_type:"phase39_fx",observed_at:at,captured_at:new Date().toISOString(),provenance_uri:URL,payload_hash:hash,payload:{storage_bucket:BUCKET,storage_path:path,content_type:"application/xml",content_encoding:"gzip"}});if(ins.error)throw ins.error;return id}
async function runReceipt(start:string,status:string,observed:number,stored:number,error?:unknown){const end=new Date().toISOString(),id=await sha(`${COLLECTOR_ID}|${start}|${end}|${status}`);await supabase.from("brian_collector_runs").insert({run_id:id,collector_id:COLLECTOR_ID,started_at:start,finished_at:end,status,observed_records:observed,stored_records:stored,degraded_sources:[],error_class:error?"COLLECTOR_ERROR":null,error_message:error?String(error).slice(0,1000):null,evidence_class:EVIDENCE,shadow_only:true,live_execution:false})}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"POST required"},405);const start=new Date().toISOString();try{const r=await fetch(URL,{headers:{accept:"application/xml","user-agent":"Brian-2026-ECB-FX-Eye/1.0"},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`ECB ${r.status}`);const xml=await r.text(),observedAt=new Date().toISOString(),captureId=await rawCapture(xml,observedAt),days=parse(xml);if(days.length<2)throw new Error("ECB history parse produced fewer than two days");const latest=days[0],prior=days[1],obs:Record<string,unknown>[]=[];for(const c of CURRENCIES){const now=latest.rates[c],before=prior.rates[c];if(!(now>0&&before>0))continue;const ret=Math.log(now/before),direction=Math.abs(ret)>=0.001?sign(ret):0,strength=clip(Math.abs(ret)/0.01),eye=await sha(`ecb-eur-${c.toLowerCase()}|fx:EUR${c}`),id=await sha(`${eye}|${latest.date}|${now}`);obs.push({observation_id:id,eye_id:eye,template_id:`ecb-eur-${c.toLowerCase()}`,asset_id:`fx:EUR${c}`,market_domain:"fx",sensor_family:"fx_reference_rate",horizon:"DAILY",independent_group:"official_ecb_fx",observed_at:observedAt,direction,strength,confidence:0.9,reliability:0.8,available:true,source_ids:[captureId],reason:`ECB reference rate ${latest.date}: ${now}; prior ${prior.date}: ${before}; daily log return=${ret.toFixed(6)}`,evidence_class:EVIDENCE,shadow_only:true,live_execution:false,metadata:{rate:now,prior_rate:before,rate_date:latest.date,prior_date:prior.date,native_frequency:"daily",not_intraday:true}})}if(obs.length){const ins=await supabase.from("brian_sensor_observations").upsert(obs,{onConflict:"observation_id",ignoreDuplicates:true});if(ins.error)throw ins.error}await runReceipt(start,"SUCCESS",CURRENCIES.length,obs.length);return out({status:"CAPTURED",rate_date:latest.date,stored_observations:obs.length,native_frequency:"daily",learning_enabled:false,live_execution:false,shadow_only:true});}catch(e){await runReceipt(start,"FAILED",0,0,e);return out({status:"FAILED",error:String(e),shadow_only:true},500)}});
