import { createClient } from "npm:@supabase/supabase-js@2.116.0";

const URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});

const ENGINE_ID="dip-multiasset-v1";
const POLICY_VERSION="dip-v853-guardian-recovery-20260914.1";
const MAX_POSITIONS=2;
const MAX_SCAN=8;
const FEE_BPS=10;
const RADAR_SOFT_STALE_MS=12*60_000;
const RADAR_HARD_STALE_MS=4*60*60_000;
const LOSS_STREAK_STOP=3;
const LOSS_STREAK_PAUSE_MS=45*60_000;
const SESSION_DD_STOP=.02;
const HOSTS=["https://api.binance.com","https://api1.binance.com","https://api2.binance.com"];
const EXCLUDED=new Set(["ETHUSDT","USDTUSDT","USDCUSDT","FDUSDUSDT","TUSDUSDT","DAIUSDT","BUSDUSDT","EURUSDT","TRYUSDT","USD1USDT"]);

type J=Record<string,unknown>;
type Candidate={symbol:string;radar_score:number;price_change_pct:number;quote_volume:number;trades_24h:number;momentum_score:number;volatility_score:number;spread_bps:number};
type Bar={o:number;h:number;l:number;c:number;closeTime:number};
type Market={symbol:string;bid:number;ask:number;mid:number;spreadBps:number;atr:number;atrPct:number;ema8:number;ema21:number;recentHigh:number;recentLow:number;pullbackPct:number;bouncePct:number;lastClose:number;prevClose:number;recovery:boolean;trendOk:boolean};
type Position={symbol:string;entry:number;qty:number;opened_at:string;stop:number;target:number;trail:number|null;max_price:number;open_fee:number;cost_basis:number;atr:number;radar_score:number;opportunity_score:number;forecast_edge_bps:number;entry_spread_bps:number;entry_reason:string;policy_version:string;estimated_cost_bps:number};
type Guard={until:number;reason:string;exit_price:number;exit_at:number;pnl:number};
type State={engine_id:string;source_session_id?:string;started_at:string;run_until:string;starting_equity:number;cash:number;realized_pnl:number;trade_count:number;win_count:number;loss_count:number;positions:Record<string,Position>;cooldowns:Record<string,Guard|number>;last_scan:J;last_eval_minute:string|null;updated_at:string;enabled:boolean;shadow_only:boolean;live_execution:boolean};
type Eval={ok:boolean;score:number;opportunity:number;costBps:number;grossBps:number;uncertaintyBps:number;netBps:number;requiredPull:number;requiredBounce:number;gates:Record<string,boolean>;reason:string};

const num=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clip=(v:number,lo=0,hi=1)=>Math.max(lo,Math.min(hi,v));
const iso=()=>new Date().toISOString();
async function sha(v:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)));return[...d].map(x=>x.toString(16).padStart(2,"0")).join("");}
function same(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function requireCron(req:Request){const supplied=(req.headers.get("x-brian-cron-key")||"").trim();if(!supplied)throw Error("UNAUTHORIZED_CRON");const q=await db.from("brian_dashboard_auth").select("cron_key_sha256").eq("auth_id","control-v3").single();if(q.error||!q.data)throw Error("CRON_AUTH_UNAVAILABLE");if(!same(await sha(supplied),String(q.data.cron_key_sha256||"")))throw Error("UNAUTHORIZED_CRON");}
async function marketJson(path:string){let last="MARKET_UNAVAILABLE";for(const host of HOSTS){try{const r=await fetch(host+path,{headers:{accept:"application/json","user-agent":"Brian-DIP-V853/1.0"},signal:AbortSignal.timeout(4500)});if(!r.ok){last=`HTTP_${r.status}`;continue;}return await r.json();}catch(e){last=e instanceof Error?e.message:String(e);}}throw Error(`BINANCE:${last}`);}
function ema(xs:number[],period:number){const k=2/(period+1);let out=xs[0]??0;for(let i=1;i<xs.length;i++)out=xs[i]*k+out*(1-k);return out;}
function atr(b:Bar[],period=14){if(b.length<period+2)return 0;const xs:number[]=[];for(let i=1;i<b.length;i++)xs.push(Math.max(b[i].h-b[i].l,Math.abs(b[i].h-b[i-1].c),Math.abs(b[i].l-b[i-1].c)));return xs.slice(-period).reduce((a,x)=>a+x,0)/period;}

async function loadMarket(symbol:string):Promise<Market>{
  const [rawBars,rawBook]=await Promise.all([marketJson(`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=1m&limit=70`),marketJson(`/api/v3/ticker/bookTicker?symbol=${encodeURIComponent(symbol)}`)]);
  if(!Array.isArray(rawBars)||rawBars.length<35)throw Error("INSUFFICIENT_BARS");
  const now=Date.now(),bars:Bar[]=rawBars.map(x=>{if(!Array.isArray(x)||x.length<7)throw Error("BAD_BAR");return{o:num(x[1]),h:num(x[2]),l:num(x[3]),c:num(x[4]),closeTime:num(x[6])};}).filter(x=>x.closeTime<now-250).slice(-60);
  if(bars.length<30)throw Error("INSUFFICIENT_CLOSED_BARS");
  const book=rawBook as J,bid=num(book.bidPrice),ask=num(book.askPrice);if(!(bid>0&&ask>bid))throw Error("BAD_BOOK");
  const mid=(bid+ask)/2,spreadBps=(ask-bid)/mid*10000;if(spreadBps>30)throw Error("WIDE_BOOK");
  const closes=bars.map(x=>x.c),a=atr(bars);if(!(a>0))throw Error("BAD_ATR");
  const recent20=bars.slice(-20),recent12=bars.slice(-12),recentHigh=Math.max(...recent20.map(x=>x.h)),recentLow=Math.min(...recent12.map(x=>x.l)),lastClose=bars.at(-1)!.c,prevClose=bars.at(-2)!.c,ema8=ema(closes.slice(-35),8),ema21=ema(closes.slice(-45),21),atrPct=a/mid*100;
  return{symbol,bid,ask,mid,spreadBps,atr:a,atrPct,ema8,ema21,recentHigh,recentLow,pullbackPct:(recentHigh-mid)/recentHigh*100,bouncePct:(mid-recentLow)/recentLow*100,lastClose,prevClose,recovery:mid>=lastClose*.999&&lastClose>=prevClose*.9975,trendOk:ema8>=ema21*.992};
}

async function acquireLease(){const owner=crypto.randomUUID(),q=await db.rpc("brian_dip_v84_acquire_lease",{p_lease_key:"brian-dip-multiasset-worker-v1",p_owner_id:owner,p_lease_seconds:40});if(q.error)throw Error(`LEASE:${q.error.message}`);const row=Array.isArray(q.data)?q.data[0]:q.data;return row?.acquired?{owner,generation:Number(row.lease_generation)}:null;}
async function releaseLease(l:{owner:string;generation:number}|null){if(!l)return;try{await db.rpc("brian_dip_v84_release_lease",{p_lease_key:"brian-dip-multiasset-worker-v1",p_owner_id:l.owner,p_lease_generation:l.generation});}catch{}}
async function loadState():Promise<State>{const q=await db.from("brian_dip_multiasset_state").select("*").eq("engine_id",ENGINE_ID).single();if(q.error)throw q.error;return q.data as State;}
async function loadCandidates(){const q=await db.from("brian_universe_snapshots").select("observed_at,candidates").order("observed_at",{ascending:false}).limit(1).maybeSingle();if(q.error||!q.data)throw Error("RADAR_UNAVAILABLE");const observedAt=String(q.data.observed_at),ageMs=Date.now()-Date.parse(observedAt);if(!Number.isFinite(ageMs)||ageMs>RADAR_HARD_STALE_MS)throw Error("RADAR_HARD_STALE");const stale=ageMs>RADAR_SOFT_STALE_MS,payload=(q.data.candidates??{}) as J,raw=Array.isArray(payload.candidates)?payload.candidates:[];const rows:Candidate[]=raw.map(v=>{const r=(v??{}) as J;return{symbol:String(r.symbol||"").toUpperCase(),radar_score:num(r.radar_score),price_change_pct:num(r.price_change_pct),quote_volume:num(r.quote_volume),trades_24h:num(r.trades_24h),momentum_score:num(r.momentum_score),volatility_score:num(r.volatility_score),spread_bps:num(r.spread_bps,999)}}).filter(r=>/^[A-Z0-9]{2,20}USDT$/.test(r.symbol)&&!EXCLUDED.has(r.symbol)&&r.radar_score>=(stale?.74:.70)&&r.quote_volume>=8_000_000&&r.trades_24h>=35_000&&r.spread_bps<=18&&Math.abs(r.price_change_pct)<=60).sort((a,b)=>(b.radar_score*.62+clip(b.momentum_score)*.22+clip(b.volatility_score)*.16)-(a.radar_score*.62+clip(a.momentum_score)*.22+clip(a.volatility_score)*.16)).slice(0,MAX_SCAN);return{rows,observedAt,ageSec:Math.round(ageMs/1000),stale};}
function equity(state:State,markets:Map<string,Market>,cash=num(state.cash),positions=state.positions||{}){let e=cash;for(const p of Object.values(positions)){const m=markets.get(p.symbol);e+=p.qty*(m?.bid??p.entry);}return e;}
function riskMode(state:State,current:number,radarStale:boolean,lossStreak:number){const start=Math.max(1,num(state.starting_equity,1000)),dd=(start-current)/start,closed=num(state.win_count)+num(state.loss_count),wr=closed?num(state.win_count)/closed:0;if(dd>=SESSION_DD_STOP)return{name:"FROZEN",gross:.0,risk:.0,minScore:.99,minOpp:.99,reason:"SESSION_DRAWDOWN",dd,wr};if(lossStreak>=LOSS_STREAK_STOP)return{name:"FROZEN",gross:.0,risk:.0,minScore:.99,minOpp:.99,reason:"LOSS_STREAK",dd,wr};if(radarStale)return{name:"DEFENSIVE",gross:.03,risk:.0025,minScore:.80,minOpp:.79,reason:"RADAR_SOFT_STALE",dd,wr};if(closed<8||wr<.35)return{name:"CALIBRATING",gross:.04,risk:.0035,minScore:.77,minOpp:.76,reason:"LOW_SAMPLE",dd,wr};return{name:"NORMAL",gross:.07,risk:.005,minScore:.74,minOpp:.74,reason:"WARM",dd,wr};}
function evaluate(c:Candidate,m:Market,mode:ReturnType<typeof riskMode>):Eval{const atrBps=m.atrPct*100,slip=Math.max(2,m.spreadBps/2),costBps=2*FEE_BPS+m.spreadBps+2*slip,requiredPull=Math.max(.55,m.atrPct*.68),requiredBounce=Math.max(.16,m.atrPct*.16),structural=Math.max(0,(m.recentHigh-m.ask)/m.ask*10000),quality=clip(.62+(c.radar_score-.70)*.8+clip(c.momentum_score-.5,0,.5)*.25,.60,1),grossBps=Math.min(structural,atrBps*1.65)*quality,uncertaintyBps=Math.max(8,atrBps*.16,costBps*.35),netBps=grossBps-costBps-uncertaintyBps,score=clip(c.radar_score*.34+clip(m.pullbackPct/Math.max(requiredPull*1.7,.6))*.20+clip(m.bouncePct/Math.max(requiredBounce*2.7,.25))*.13+(m.recovery?.10:0)+(m.trendOk?.08:0)+clip(netBps/100)*.15),opportunity=clip(score*.62+c.radar_score*.22+clip(c.momentum_score)*.08+clip(netBps/100)*.08),gates={radar:c.radar_score>=(mode.name==="DEFENSIVE"?.80:.75),spread:m.spreadBps<=(mode.name==="DEFENSIVE"?9:12),day_move:Math.abs(c.price_change_pct)<=38,pullback:m.pullbackPct>=requiredPull,bounce:m.bouncePct>=requiredBounce,recovery:m.recovery,trend:m.trendOk,not_chasing:m.mid<=m.recentHigh*(1-Math.max(.0018,m.atrPct*.10/100)),economics:netBps>=Math.max(16,costBps*.65)&&grossBps>=costBps*2.0},ok:mode.name!=="FROZEN"&&score>=mode.minScore&&opportunity>=mode.minOpp};const failed=Object.entries(gates).filter(([,v])=>!v).map(([k])=>k);gates.score=score>=mode.minScore;gates.opportunity=opportunity>=mode.minOpp;const ok=mode.name!=="FROZEN"&&Object.values(gates).every(Boolean);return{ok,score,opportunity,costBps,grossBps,uncertaintyBps,netBps,requiredPull,requiredBounce,gates,reason:ok?"V853_EDGE_READY":mode.name==="FROZEN"?`RISK_FROZEN_${mode.reason}`:`WAIT_${failed.join("+")||"score"}`};}
function readGuard(v:Guard|number|undefined):Guard|null{if(typeof v==="number")return{until:v,reason:"LEGACY",exit_price:0,exit_at:v-20*60_000,pnl:0};return v&&typeof v==="object"?v:null;}
function guardCheck(v:Guard|number|undefined,m:Market,ev:Eval,now:number){const g=readGuard(v);if(!g)return{blocked:false,reason:"",clear:false};if(now<g.until)return{blocked:true,reason:`COOLDOWN_${g.reason}`,clear:false};if(now-g.exit_at>4*60*60_000)return{blocked:false,reason:"",clear:true};const below=g.exit_price>0?m.mid<=g.exit_price*(1-.002):true;if(g.pnl<0){const ready=below&&ev.score>=.83&&m.pullbackPct>=Math.max(.8,ev.requiredPull*1.3)&&m.recovery;return{blocked:!ready,reason:ready?"":"LOSS_REENTRY_GUARD",clear:ready};}const ready=below&&ev.score>=.77&&m.pullbackPct>=Math.max(.65,ev.requiredPull*1.1);return{blocked:!ready,reason:ready?"":"PROFIT_REENTRY_GUARD",clear:ready};}
async function writeEvent(row:J){const q=await db.from("brian_dip_multiasset_events").insert(row);if(q.error)throw q.error;}
async function writeEvaluations(rows:J[]){if(!rows.length)return;try{const q=await db.from("brian_dip_multiasset_evaluations").insert(rows);if(q.error)console.error("evaluation telemetry",q.error.message);}catch(e){console.error("evaluation telemetry",e);}}
async function recordFailure(message:string){try{const q=await db.from("brian_dip_multiasset_state").select("last_scan").eq("engine_id",ENGINE_ID).maybeSingle();const prev=(q.data?.last_scan??{}) as J;await db.from("brian_dip_multiasset_state").update({updated_at:iso(),last_scan:{...prev,status:"FAILED_CLOSED",policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",error:message,error_at:iso()}}).eq("engine_id",ENGINE_ID);}catch{}}

async function run(){
  const state=await loadState(),now=Date.now();if(!state.enabled||now>=Date.parse(state.run_until))return{status:"WINDOW_COMPLETE",engine_id:ENGINE_ID,policy_version:POLICY_VERSION};
  const radar=await loadCandidates(),symbols=[...new Set([...Object.keys(state.positions||{}),...radar.rows.map(x=>x.symbol)])].slice(0,MAX_SCAN+MAX_POSITIONS),pairs=await Promise.all(symbols.map(async s=>{try{return[s,await loadMarket(s)] as const;}catch(e){return[s,{error:e instanceof Error?e.message:String(e)}] as const;}})),markets=new Map<string,Market>(),marketErrors:J={};for(const[s,v]of pairs){if("error" in v)marketErrors[s]=v.error;else markets.set(s,v);}
  const positions={...(state.positions||{})},cooldowns={...(state.cooldowns||{})};let cash=num(state.cash),realized=num(state.realized_pnl),trades=num(state.trade_count),wins=num(state.win_count),losses=num(state.loss_count),lossStreak=num((state.last_scan||{}).loss_streak),lastLossAt=num((state.last_scan||{}).last_loss_at);if(lossStreak>=LOSS_STREAK_STOP&&now-lastLossAt>LOSS_STREAK_PAUSE_MS)lossStreak=0;const actions:J[]=[];
  for(const[s,p]of Object.entries(positions)){const m=markets.get(s);if(!m)continue;const held=now-Date.parse(p.opened_at),slip=Math.max(2,m.spreadBps/2),cost=num(p.estimated_cost_bps,2*FEE_BPS+m.spreadBps+2*slip);p.max_price=Math.max(num(p.max_price,p.entry),m.bid);const mfe=(p.max_price-p.entry)/p.entry*10000,trailArm=Math.max(cost+16,m.atrPct*100*.70);if(mfe>=trailArm){const floor=p.entry*(1+(cost+8)/10000),candidate=Math.max(floor,m.bid-Math.max(m.atr*.58,p.entry*.0045));p.trail=Math.max(num(p.trail),candidate);}const momentum=held>4*60_000&&m.ema8<m.ema21*.996&&m.lastClose<m.prevClose*.997&&m.bid<p.entry*(1+cost/10000),decay=held>10*60_000&&!m.recovery&&m.bid<p.entry*(1+Math.max(cost,12)/10000);let reason="";if(m.bid<=p.stop)reason="STOP";else if(p.trail&&m.bid<=p.trail)reason="TRAIL";else if(m.bid>=p.target)reason="TARGET";else if(momentum)reason="MOMENTUM_BREAK";else if(decay)reason="EDGE_DECAY";else if(held>=45*60_000)reason="MAX_HOLD";if(!reason)continue;const exit=m.bid*(1-slip/10000),gross=p.qty*exit,exitFee=gross*FEE_BPS/10000,pnl=gross-exitFee-p.cost_basis;cash+=gross-exitFee;realized+=pnl;trades++;if(pnl>.01){wins++;lossStreak=0;}else if(pnl<-.01){losses++;lossStreak++;lastLossAt=now;}delete positions[s];cooldowns[s]={until:now+(pnl<0?45:25)*60_000,reason,exit_price:exit,exit_at:now,pnl};const row={engine_id:ENGINE_ID,observed_at:iso(),symbol:s,action:"SELL",price:exit,qty:p.qty,notional:gross,pnl,reason,metadata:{policy_version:POLICY_VERSION,entry:p.entry,hold_seconds:Math.round(held/1000),target:p.target,stop:p.stop,trail:p.trail,max_price:p.max_price,estimated_cost_bps:cost,shadow_only:true,live_execution:false}};await writeEvent(row);actions.push(row);}
  const mode=riskMode({...state,win_count:wins,loss_count:losses,realized_pnl:realized} as State,equity(state,markets,cash,positions),radar.stale,lossStreak),evals:J[]=[],ready:{c:Candidate;m:Market;ev:Eval}[]=[];
  for(const c of radar.rows){const m=markets.get(c.symbol);if(!m)continue;const ev=evaluate(c,m,mode),g=guardCheck(cooldowns[c.symbol],m,ev,now),open=!!positions[c.symbol];if(g.clear)delete cooldowns[c.symbol];const isReady=ev.ok&&!g.blocked&&!open,reason=open?"POSITION_OPEN":g.blocked?g.reason:ev.reason;const e={symbol:c.symbol,price:m.mid,radar_score:c.radar_score,signal_score:ev.score,opportunity_score:ev.opportunity,estimated_cost_bps:ev.costBps,forecast_gross_bps:ev.grossBps,uncertainty_bps:ev.uncertaintyBps,forecast_net_bps:ev.netBps,pullback_pct:m.pullbackPct,bounce_pct:m.bouncePct,spread_bps:m.spreadBps,ready:isReady,reason,gates:ev.gates,policy_version:POLICY_VERSION,risk_mode:mode.name};evals.push(e);if(isReady)ready.push({c,m,ev});}
  ready.sort((a,b)=>b.ev.opportunity-a.ev.opportunity||b.ev.netBps-a.ev.netBps);
  for(const x of ready){if(mode.name==="FROZEN"||Object.keys(positions).length>=MAX_POSITIONS)break;const liveEq=Math.max(0,equity(state,markets,cash,positions)),openGross=Object.values(positions).reduce((a,p)=>a+p.qty*p.entry,0),remaining=Math.max(0,liveEq*mode.gross*MAX_POSITIONS-openGross),riskUsd=liveEq*mode.risk,stopDist=Math.min(x.m.ask*.022,Math.max(x.m.atr*1.2,x.m.ask*.007)),riskPerDollar=stopDist/x.m.ask+x.ev.costBps/10000,budget=Math.min(cash*.92,liveEq*mode.gross,remaining,riskUsd/Math.max(.0001,riskPerDollar));if(budget<20)continue;const slip=Math.max(2,x.m.spreadBps/2),entry=x.m.ask*(1+slip/10000),gross=budget/(1+FEE_BPS/10000),qty=gross/entry,openFee=gross*FEE_BPS/10000,costBasis=gross+openFee;let targetDist=Math.max(x.m.atr*1.55,entry*(x.ev.costBps*2.7/10000),stopDist*1.6);targetDist=Math.min(targetDist,entry*.045);const p:Position={symbol:x.c.symbol,entry,qty,opened_at:iso(),stop:entry-stopDist,target:entry+targetDist,trail:null,max_price:entry,open_fee:openFee,cost_basis:costBasis,atr:x.m.atr,radar_score:x.c.radar_score,opportunity_score:x.ev.opportunity,forecast_edge_bps:x.ev.netBps,entry_spread_bps:x.m.spreadBps,entry_reason:x.ev.reason,policy_version:POLICY_VERSION,estimated_cost_bps:x.ev.costBps};positions[x.c.symbol]=p;cash-=costBasis;const row={engine_id:ENGINE_ID,observed_at:iso(),symbol:x.c.symbol,action:"BUY",price:entry,qty,notional:gross,pnl:null,reason:p.entry_reason,metadata:{policy_version:POLICY_VERSION,risk_mode:mode.name,gross_cap_pct:mode.gross,risk_cap_pct:mode.risk,signal_score:x.ev.score,opportunity_score:x.ev.opportunity,forecast_net_bps:x.ev.netBps,estimated_cost_bps:x.ev.costBps,target:p.target,stop:p.stop,shadow_only:true,live_execution:false}};await writeEvent(row);actions.push(row);}
  const minute=new Date(Math.floor(now/60000)*60000).toISOString();if(state.last_eval_minute!==minute)await writeEvaluations(evals.map(e=>({engine_id:ENGINE_ID,observed_at:iso(),symbol:e.symbol,price:e.price,radar_score:e.radar_score,signal_score:e.signal_score,action:e.ready?"READY":"WAIT",reason:e.reason,metadata:e})));
  const finalEq=equity(state,markets,cash,positions),scan={status:"RUNNING",policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",risk_mode:mode.name,risk_reason:mode.reason,drawdown_pct:mode.dd,win_rate:mode.wr,loss_streak:lossStreak,last_loss_at:lastLossAt,radar_observed_at:radar.observedAt,radar_age_seconds:radar.ageSec,radar_soft_stale:radar.stale,scanned:evals,ranked_ready:ready.slice(0,5).map(x=>({symbol:x.c.symbol,opportunity_score:x.ev.opportunity,forecast_net_bps:x.ev.netBps,radar_score:x.c.radar_score})),actions,market_errors:marketErrors,equity:finalEq,position_count:Object.keys(positions).length,max_positions:MAX_POSITIONS,gross_cap_pct:mode.gross,risk_cap_pct:mode.risk};
  const u=await db.from("brian_dip_multiasset_state").update({cash,realized_pnl:realized,trade_count:trades,win_count:wins,loss_count:losses,positions,cooldowns,last_eval_minute:minute,last_scan:scan,updated_at:iso(),enabled:true,shadow_only:true,live_execution:false}).eq("engine_id",ENGINE_ID);if(u.error)throw u.error;
  return{status:"RUNNING",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,risk_mode:mode.name,risk_reason:mode.reason,radar_age_seconds:radar.ageSec,equity:finalEq,cash,realized_pnl:realized,trade_count:trades,positions:Object.keys(positions),actions,shadow_only:true,live_execution:false};
}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response("method",{status:405});let lease:{owner:string;generation:number}|null=null;try{await requireCron(req);lease=await acquireLease();if(!lease)return Response.json({status:"WAIT_LEASE",engine_id:ENGINE_ID,policy_version:POLICY_VERSION});return Response.json(await run(),{headers:{"cache-control":"no-store"}});}catch(e){const message=e instanceof Error?e.message:String(e);console.error("dip-v853",message);await recordFailure(message);return Response.json({status:"FAILED_CLOSED",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,error:message,shadow_only:true,live_execution:false},{status:message.includes("UNAUTHORIZED")?401:500});}finally{await releaseLease(lease);}});
