import { createClient } from "npm:@supabase/supabase-js@2.116.0";

const URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(URL, SERVICE, { auth: { persistSession: false, autoRefreshToken: false } });

const ENGINE_ID = "dip-multiasset-v1";
const POLICY_VERSION = "dip-v85-guardian-20260914.1";
const RUN_HOURS = 18;
const MAX_POSITIONS = 2;
const MAX_SCAN = 12;
const FEE_BPS = 10;
const SESSION_DD_STOP = 0.020;
const LOSS_STREAK_STOP = 3;
const LOSS_STREAK_PAUSE_MS = 45 * 60_000;
const LOSS_COOLDOWN_MS = 45 * 60_000;
const TARGET_COOLDOWN_MS = 30 * 60_000;
const PROFIT_COOLDOWN_MS = 25 * 60_000;
const BASE_COOLDOWN_MS = 20 * 60_000;
const GUARD_MAX_AGE_MS = 4 * 60 * 60_000;
const HOSTS = ["https://api.binance.com", "https://api1.binance.com", "https://api2.binance.com"];
const EXCLUDED = new Set(["ETHUSDT","USDTUSDT","USDCUSDT","FDUSDUSDT","TUSDUSDT","DAIUSDT","BUSDUSDT","EURUSDT","TRYUSDT","USD1USDT"]);

type J = Record<string, unknown>;
type Position = {
  symbol:string; entry:number; qty:number; opened_at:string; stop:number; target:number;
  trail:number|null; max_price:number; open_fee:number; cost_basis:number; atr:number;
  radar_score:number; opportunity_score?:number; forecast_edge_bps?:number; entry_spread_bps:number;
  entry_reason:string; policy_version?:string; estimated_cost_bps?:number;
};
type ReentryGuard = { until:number; reason:string; exit_price:number; exit_at:number; pnl:number; peak_price:number; atr_pct:number; };
type State = {
  engine_id:string; started_at:string; run_until:string; starting_equity:number; cash:number; realized_pnl:number;
  trade_count:number; win_count:number; loss_count:number; positions:Record<string,Position>; cooldowns:Record<string,number|ReentryGuard>;
  last_scan:J; last_eval_minute:string|null; updated_at:string; enabled:boolean; shadow_only:boolean; live_execution:boolean;
};
type Candidate = { symbol:string; base_asset:string; radar_score:number; price_change_pct:number; range_pct:number; spread_bps:number; quote_volume:number; trades_24h:number; momentum_score:number; volatility_score:number; };
type Bar = { o:number; h:number; l:number; c:number; v:number; openTime:number; closeTime:number };
type Market = { symbol:string; bid:number; ask:number; mid:number; spreadBps:number; bars:Bar[]; atr:number; atrPct:number; ema8:number; ema21:number; recentLow:number; recentHigh:number; pullbackPct:number; bouncePct:number; lastClose:number; prevClose:number; recovery:boolean; trendOk:boolean; };
type EntryEval = { ok:boolean; score:number; opportunity:number; costBps:number; forecastGrossBps:number; uncertaintyBps:number; forecastNetBps:number; requiredPull:number; requiredBounce:number; gates:Record<string,boolean>; reason:string; };
type GuardCheck = { blocked:boolean; reason:string; clear:boolean; metrics:J };
type Ready = { c:Candidate; m:Market; ev:EntryEval; guard:GuardCheck };
type RiskMode = { name:"COLD"|"DEFENSIVE"|"NORMAL"|"FROZEN"; grossCapPct:number; riskCapPct:number; minScore:number; minOpportunity:number; frozen:boolean; reason:string; drawdownPct:number; winRate:number; };

function num(v:unknown,fallback=0):number{const n=Number(v);return Number.isFinite(n)?n:fallback;}
function clip(v:number,lo=0,hi=1):number{return Math.max(lo,Math.min(hi,v));}
function nowIso(){return new Date().toISOString();}
async function sha256Hex(value:string):Promise<string>{const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));return[...d].map(b=>b.toString(16).padStart(2,"0")).join("");}
function same(a:string,b:string):boolean{if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function requireCron(req:Request){const supplied=(req.headers.get("x-brian-cron-key")||"").trim();if(!supplied)throw Error("UNAUTHORIZED_CRON");const q=await db.from("brian_dashboard_auth").select("cron_key_sha256").eq("auth_id","control-v3").single();if(q.error||!q.data)throw Error("CRON_AUTH_UNAVAILABLE");if(!same(await sha256Hex(supplied),String(q.data.cron_key_sha256||"")))throw Error("UNAUTHORIZED_CRON");}
async function marketJson(path:string):Promise<unknown>{let last="MARKET_UNAVAILABLE";for(const host of HOSTS){try{const r=await fetch(host+path,{headers:{accept:"application/json","user-agent":"Brian-DIP-V85-Guardian/1.0"},signal:AbortSignal.timeout(5000)});if(!r.ok){last=`HTTP_${r.status}`;if(r.status===418||r.status===429)break;continue;}return await r.json();}catch(e){last=e instanceof Error?e.message:String(e);}}throw Error(`BINANCE_SPOT:${last}`);}
function ema(values:number[],period:number):number{const k=2/(period+1);let out=values[0]??0;for(let i=1;i<values.length;i++)out=values[i]*k+out*(1-k);return out;}
function atr(bars:Bar[],period=14):number{if(bars.length<period+2)return 0;const xs:number[]=[];for(let i=1;i<bars.length;i++){const b=bars[i],p=bars[i-1].c;xs.push(Math.max(b.h-b.l,Math.abs(b.h-p),Math.abs(b.l-p)));}return xs.slice(-period).reduce((a,b)=>a+b,0)/period;}
async function loadMarket(symbol:string):Promise<Market>{const [rawBars,rawBook]=await Promise.all([marketJson(`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=1m&limit=70`),marketJson(`/api/v3/ticker/bookTicker?symbol=${encodeURIComponent(symbol)}`)]);if(!Array.isArray(rawBars)||rawBars.length<35)throw Error("INSUFFICIENT_BARS");const t=Date.now();const parsed:Bar[]=rawBars.map(x=>{if(!Array.isArray(x)||x.length<7)throw Error("BAD_BAR");return{o:num(x[1]),h:num(x[2]),l:num(x[3]),c:num(x[4]),v:num(x[5]),openTime:num(x[0]),closeTime:num(x[6])};});const bars=parsed.filter(b=>b.closeTime<t-250).slice(-60);if(bars.length<30)throw Error("INSUFFICIENT_CLOSED_BARS");const book=rawBook as J,bid=num(book.bidPrice),ask=num(book.askPrice);if(!(bid>0&&ask>bid))throw Error("BAD_BOOK");const mid=(bid+ask)/2,spreadBps=(ask-bid)/mid*10000;if(!Number.isFinite(spreadBps)||spreadBps>30)throw Error("WIDE_BOOK");const closes=bars.map(b=>b.c),a=atr(bars,14);if(!(a>0))throw Error("BAD_ATR");const recent20=bars.slice(-20),recent12=bars.slice(-12),recentHigh=Math.max(...recent20.map(b=>b.h)),recentLow=Math.min(...recent12.map(b=>b.l));const lastClose=bars.at(-1)!.c,prevClose=bars.at(-2)!.c,ema8=ema(closes.slice(-35),8),ema21=ema(closes.slice(-45),21);const pullbackPct=(recentHigh-mid)/recentHigh*100,bouncePct=(mid-recentLow)/recentLow*100,atrPct=a/mid*100;const recovery=mid>=lastClose*.999&&lastClose>=prevClose*.9975;const trendOk=ema8>=ema21*.992;return{symbol,bid,ask,mid,spreadBps,bars,atr:a,atrPct,ema8,ema21,recentLow,recentHigh,pullbackPct,bouncePct,lastClose,prevClose,recovery,trendOk};}
async function acquireLease():Promise<{owner:string;generation:number}|null>{const owner=crypto.randomUUID();const q=await db.rpc("brian_dip_v84_acquire_lease",{p_lease_key:"brian-dip-multiasset-worker-v1",p_owner_id:owner,p_lease_seconds:45});if(q.error)throw Error("LEASE:"+q.error.message);const row=Array.isArray(q.data)?q.data[0]:q.data;if(!row?.acquired)return null;return{owner,generation:Number(row.lease_generation)};}
async function releaseLease(lease:{owner:string;generation:number}|null){if(!lease)return;try{await db.rpc("brian_dip_v84_release_lease",{p_lease_key:"brian-dip-multiasset-worker-v1",p_owner_id:lease.owner,p_lease_generation:lease.generation});}catch{}}
async function loadOrCreateState():Promise<State>{const q=await db.from("brian_dip_multiasset_state").select("*").eq("engine_id",ENGINE_ID).maybeSingle();if(q.error)throw q.error;if(q.data)return q.data as State;const now=new Date(),runUntil=new Date(now.getTime()+RUN_HOURS*3600_000);const row={engine_id:ENGINE_ID,started_at:now.toISOString(),run_until:runUntil.toISOString(),starting_equity:1000,cash:1000,realized_pnl:0,trade_count:0,win_count:0,loss_count:0,positions:{},cooldowns:{},last_scan:{status:"BOOT",policy_version:POLICY_VERSION,risk_mode:"COLD"},last_eval_minute:null,updated_at:now.toISOString(),enabled:true,shadow_only:true,live_execution:false};const ins=await db.from("brian_dip_multiasset_state").insert(row).select("*").single();if(ins.error)throw ins.error;return ins.data as State;}
async function latestCandidates():Promise<{observedAt:string;rows:Candidate[]}>{const q=await db.from("brian_universe_snapshots").select("observed_at,candidates").order("observed_at",{ascending:false}).limit(1).maybeSingle();if(q.error||!q.data)throw Error("RADAR_UNAVAILABLE");const observedAt=String(q.data.observed_at),age=Date.now()-Date.parse(observedAt);if(!Number.isFinite(age)||age>12*60_000)throw Error("RADAR_STALE");const payload=(q.data.candidates??{}) as J,raw=Array.isArray(payload.candidates)?payload.candidates:[];const rows:Candidate[]=raw.map(v=>{const r=(v??{}) as J;return{symbol:String(r.symbol||"").toUpperCase(),base_asset:String(r.base_asset||"").toUpperCase(),radar_score:num(r.radar_score),price_change_pct:num(r.price_change_pct),range_pct:num(r.range_pct),spread_bps:num(r.spread_bps,999),quote_volume:num(r.quote_volume),trades_24h:num(r.trades_24h),momentum_score:num(r.momentum_score),volatility_score:num(r.volatility_score)}}).filter(r=>/^[A-Z0-9]{2,20}USDT$/.test(r.symbol)&&!EXCLUDED.has(r.symbol)&&r.radar_score>=.70&&r.quote_volume>=8_000_000&&r.trades_24h>=35_000&&r.spread_bps<=18&&Math.abs(r.price_change_pct)<=60).sort((a,b)=>(b.radar_score*.60+clip(b.momentum_score)*.22+clip(b.volatility_score)*.18)-(a.radar_score*.60+clip(a.momentum_score)*.22+clip(a.volatility_score)*.18)).slice(0,MAX_SCAN);return{observedAt,rows};}
function equity(state:State,markets:Map<string,Market>):number{let e=num(state.cash);for(const p of Object.values(state.positions||{})){const m=markets.get(p.symbol);e+=p.qty*(m?.bid??p.entry);}return e;}
function evaluateEntry(c:Candidate,m:Market,mode:RiskMode):EntryEval{const atrBps=m.atrPct*100,slipBps=Math.max(2,m.spreadBps/2),costBps=2*FEE_BPS+m.spreadBps+2*slipBps;const requiredPull=Math.max(.60,m.atrPct*.72),requiredBounce=Math.max(.18,m.atrPct*.18);const structuralRoom=Math.max(0,(m.recentHigh-m.ask)/m.ask*10000);const quality=clip(.60+(c.radar_score-.70)*.85+clip(c.momentum_score-.55,0,.45)*.35,0.58,1.0);const grossCeiling=Math.min(structuralRoom,atrBps*1.60);const forecastGrossBps=grossCeiling*quality;const uncertaintyBps=Math.max(8,atrBps*.18,costBps*.35);const forecastNetBps=forecastGrossBps-costBps-uncertaintyBps;const score=clip(c.radar_score*.34+clip(m.pullbackPct/Math.max(requiredPull*1.7,.7))*.20+clip(m.bouncePct/Math.max(requiredBounce*2.6,.3))*.13+(m.recovery?.10:0)+(m.trendOk?.08:0)+clip(forecastNetBps/100)*.15);const opportunity=clip(score*.62+c.radar_score*.22+clip(c.momentum_score)*.08+clip(forecastNetBps/100)*.08);const gates={radar:c.radar_score>=(mode.name==="DEFENSIVE"?.80:.76),spread:m.spreadBps<=(mode.name==="DEFENSIVE"?8:12),day_move:Math.abs(c.price_change_pct)<=35,pullback:m.pullbackPct>=requiredPull,bounce:m.bouncePct>=requiredBounce,recovery:m.recovery,trend:m.trendOk,not_chasing:m.mid<=m.recentHigh*(1-Math.max(.0020,m.atrPct*.12/100)),economics:forecastNetBps>=Math.max(18,costBps*.70)&&forecastGrossBps>=costBps*2.15};const ok=!mode.frozen&&score>=mode.minScore&&opportunity>=mode.minOpportunity&&Object.values(gates).every(Boolean);const failed=Object.entries(gates).filter(([,v])=>!v).map(([k])=>k);return{ok,score,opportunity,costBps,forecastGrossBps,uncertaintyBps,forecastNetBps,requiredPull,requiredBounce,gates,reason:ok?"V85_EDGE_READY":mode.frozen?`RISK_FROZEN_${mode.reason}`:`WAIT_${failed.join("+")||"SCORE"}`};}
function readGuard(raw:unknown):ReentryGuard|null{if(typeof raw==="number"&&Number.isFinite(raw))return{until:raw,reason:"LEGACY",exit_price:0,exit_at:raw-BASE_COOLDOWN_MS,pnl:0,peak_price:0,atr_pct:0};if(!raw||typeof raw!=="object")return null;const r=raw as J,until=num(r.until);if(!(until>0))return null;return{until,reason:String(r.reason||"UNKNOWN"),exit_price:num(r.exit_price),exit_at:num(r.exit_at,until-BASE_COOLDOWN_MS),pnl:num(r.pnl),peak_price:num(r.peak_price),atr_pct:num(r.atr_pct)};}
function reentryCheck(raw:unknown,c:Candidate,m:Market,ev:EntryEval,now:number):GuardCheck{const g=readGuard(raw);if(!g)return{blocked:false,reason:"",clear:raw!=null,metrics:{}};const age=Math.max(0,now-g.exit_at),base={guard_reason:g.reason,guard_age_sec:Math.round(age/1000),cooldown_left_sec:Math.max(0,Math.round((g.until-now)/1000)),last_exit_price:g.exit_price,last_exit_pnl:g.pnl};if(now<g.until)return{blocked:true,reason:`COOLDOWN_${g.reason}`,clear:false,metrics:base};if(age>GUARD_MAX_AGE_MS||g.reason==="LEGACY")return{blocked:false,reason:"",clear:true,metrics:{...base,guard_reset:"AGED_OUT"}};const lowerThanExit=g.exit_price>0?m.mid<=g.exit_price*(1-Math.max(.0025,m.atrPct*.20/100)):true;if(g.reason==="TARGET"){const fresh=lowerThanExit&&m.pullbackPct>=Math.max(.80,ev.requiredPull*1.20)&&m.bouncePct>=Math.max(.22,ev.requiredBounce*1.25)&&ev.score>=.76&&c.radar_score>=.78;return fresh?{blocked:false,reason:"",clear:true,metrics:{...base,guard_reset:"NEW_DIP_AFTER_TARGET"}}:{blocked:true,reason:"TARGET_LEG_LOCK",clear:false,metrics:{...base,lower_than_exit:lowerThanExit}};}const loss=g.pnl<0||g.reason==="STOP"||g.reason==="MOMENTUM_BREAK";if(loss){const notChasingOldExit=g.exit_price>0?m.mid<=g.exit_price*(1+Math.max(.0025,m.atrPct*.25/100)):true;const strong=notChasingOldExit&&ev.score>=.84&&ev.opportunity>=.82&&c.radar_score>=.82&&m.pullbackPct>=Math.max(.90,ev.requiredPull*1.40)&&m.bouncePct>=Math.max(.28,ev.requiredBounce*1.55)&&m.recovery&&m.trendOk;return strong?{blocked:false,reason:"",clear:true,metrics:{...base,guard_reset:"STRONG_RECLAIM_AFTER_LOSS"}}:{blocked:true,reason:"LOSS_REENTRY_GUARD",clear:false,metrics:{...base,not_chasing_old_exit:notChasingOldExit}};}const fresh=lowerThanExit&&ev.score>=.78&&ev.opportunity>=.77&&c.radar_score>=.78&&m.pullbackPct>=Math.max(.70,ev.requiredPull*1.15)&&m.recovery;return fresh?{blocked:false,reason:"",clear:true,metrics:{...base,guard_reset:"FRESH_PULLBACK_AFTER_PROFIT"}}:{blocked:true,reason:"PROFIT_REENTRY_GUARD",clear:false,metrics:{...base,lower_than_exit:lowerThanExit}};}
function cooldownMs(reason:string,pnl:number):number{if(reason==="TARGET")return TARGET_COOLDOWN_MS;if(pnl<0||reason==="STOP"||reason==="MOMENTUM_BREAK")return LOSS_COOLDOWN_MS;if(reason==="TRAIL"||pnl>0)return PROFIT_COOLDOWN_MS;return BASE_COOLDOWN_MS;}
async function hydrateGuards(cooldowns:Record<string,number|ReentryGuard>){const since=new Date(Date.now()-GUARD_MAX_AGE_MS).toISOString();const q=await db.from("brian_dip_multiasset_events").select("observed_at,symbol,pnl,reason,price,metadata").eq("engine_id",ENGINE_ID).eq("action","SELL").gte("observed_at",since).order("observed_at",{ascending:false}).limit(80);if(q.error)return;const seen=new Set<string>();for(const row of q.data||[]){const s=String(row.symbol||"");if(!s||seen.has(s)||cooldowns[s])continue;seen.add(s);const at=Date.parse(String(row.observed_at)),pnl=num(row.pnl),reason=String(row.reason||"UNKNOWN"),meta=(row.metadata||{}) as J;cooldowns[s]={until:at+cooldownMs(reason,pnl),reason,exit_price:num(row.price),exit_at:at,pnl,peak_price:num(meta.max_price),atr_pct:num(meta.atr_pct)};}}
async function recentRisk():Promise<{streak:number;lastLossAt:number;sumPnl:number}>{const q=await db.from("brian_dip_multiasset_events").select("observed_at,pnl").eq("engine_id",ENGINE_ID).eq("action","SELL").order("observed_at",{ascending:false}).limit(8);if(q.error)return{streak:0,lastLossAt:0,sumPnl:0};let streak=0,lastLossAt=0,sumPnl=0;for(let i=0;i<(q.data||[]).length;i++){const r=q.data![i];const pnl=num(r.pnl);sumPnl+=pnl;if(i===0&&pnl<0)lastLossAt=Date.parse(String(r.observed_at));if(pnl<0&&streak===i)streak++;else if(i===streak)break;}return{streak,lastLossAt,sumPnl};}
function riskMode(state:State,currentEquity:number,risk:{streak:number;lastLossAt:number;sumPnl:number}):RiskMode{const start=Math.max(1,num(state.starting_equity,1000)),dd=(start-currentEquity)/start,closed=Math.max(0,num(state.win_count)+num(state.loss_count)),wr=closed?num(state.win_count)/closed:0;const streakFrozen=risk.streak>=LOSS_STREAK_STOP&&Date.now()-risk.lastLossAt<LOSS_STREAK_PAUSE_MS;if(dd>=SESSION_DD_STOP||streakFrozen)return{name:"FROZEN",grossCapPct:0,riskCapPct:0,minScore:.99,minOpportunity:.99,frozen:true,reason:dd>=SESSION_DD_STOP?"SESSION_DRAWDOWN":"LOSS_STREAK",drawdownPct:dd,winRate:wr};if(closed<8||wr<.35||num(state.realized_pnl)<-start*.01)return{name:"DEFENSIVE",grossCapPct:.04,riskCapPct:.0035,minScore:.80,minOpportunity:.79,frozen:false,reason:"LOW_SAMPLE_OR_WEAK_ECONOMICS",drawdownPct:dd,winRate:wr};if(closed<20)return{name:"COLD",grossCapPct:.05,riskCapPct:.0040,minScore:.76,minOpportunity:.75,frozen:false,reason:"CALIBRATING",drawdownPct:dd,winRate:wr};return{name:"NORMAL",grossCapPct:.08,riskCapPct:.0050,minScore:.74,minOpportunity:.74,frozen:false,reason:"WARM",drawdownPct:dd,winRate:wr};}
async function insertEvent(row:J){const q=await db.from("brian_dip_multiasset_events").insert(row);if(q.error)throw q.error;}

async function run():Promise<J>{
  const state=await loadOrCreateState(),now=Date.now();
  if(!state.enabled||now>=Date.parse(state.run_until)){await db.from("brian_dip_multiasset_state").update({enabled:false,updated_at:nowIso(),last_scan:{status:"WINDOW_COMPLETE",run_until:state.run_until,policy_version:POLICY_VERSION}}).eq("engine_id",ENGINE_ID);return{status:"WINDOW_COMPLETE",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,run_until:state.run_until,shadow_only:true,live_execution:false};}
  const radar=await latestCandidates();
  const symbols=[...new Set([...Object.keys(state.positions||{}),...radar.rows.map(r=>r.symbol)])].slice(0,MAX_SCAN+MAX_POSITIONS);
  const marketPairs=await Promise.all(symbols.map(async s=>{try{return[s,await loadMarket(s)] as const;}catch(e){return[s,{error:e instanceof Error?e.message:String(e)}] as const;}}));
  const markets=new Map<string,Market>(),errors:J={};for(const[s,v]of marketPairs){if("error" in v)errors[s]=v.error;else markets.set(s,v);}
  const positions={...(state.positions||{})},cooldowns={...(state.cooldowns||{})};await hydrateGuards(cooldowns);
  let cash=num(state.cash),realized=num(state.realized_pnl),tradeCount=num(state.trade_count),wins=num(state.win_count),losses=num(state.loss_count);const actions:J[]=[];

  for(const[symbol,p]of Object.entries(positions)){
    const m=markets.get(symbol);if(!m)continue;
    const heldMs=now-Date.parse(p.opened_at),slipBps=Math.max(2,m.spreadBps/2),estimatedCostBps=num(p.estimated_cost_bps,2*FEE_BPS+m.spreadBps+2*slipBps);p.max_price=Math.max(num(p.max_price,p.entry),m.bid);
    const legacyOversize=p.cost_basis>Math.max(1,num(state.starting_equity))*0.12;if(legacyOversize)p.stop=Math.max(p.stop,p.entry-Math.max(p.atr*.90,p.entry*.006));
    const mfeBps=(p.max_price-p.entry)/p.entry*10000,trailArm=Math.max(estimatedCostBps+18,m.atrPct*100*.75);
    if(mfeBps>=trailArm){const trailGap=Math.max(m.atr*.58,p.entry*.0045),lockFloor=p.entry*(1+(estimatedCostBps+10)/10000),candidate=Math.max(lockFloor,m.bid-trailGap);p.trail=Math.max(num(p.trail,0),candidate);}
    const momentumBreak=heldMs>4*60_000&&m.ema8<m.ema21*.996&&m.lastClose<m.prevClose*.997&&m.bid<p.entry*(1+estimatedCostBps/10000);
    const edgeDecay=heldMs>9*60_000&&!m.recovery&&m.bid<p.entry*(1+Math.max(estimatedCostBps,12)/10000);
    let reason="";if(m.bid<=p.stop)reason="STOP";else if(p.trail&&m.bid<=p.trail)reason="TRAIL";else if(m.bid>=p.target)reason="TARGET";else if(momentumBreak)reason="MOMENTUM_BREAK";else if(edgeDecay)reason="EDGE_DECAY";else if(heldMs>=45*60_000)reason="MAX_HOLD";
    if(!reason)continue;
    const exitPrice=m.bid*(1-slipBps/10000),gross=p.qty*exitPrice,exitFee=gross*FEE_BPS/10000,pnl=gross-exitFee-p.cost_basis;cash+=gross-exitFee;realized+=pnl;tradeCount++;if(pnl>0.01)wins++;else if(pnl<-.01)losses++;delete positions[symbol];const cdMs=cooldownMs(reason,pnl);cooldowns[symbol]={until:now+cdMs,reason,exit_price:exitPrice,exit_at:now,pnl,peak_price:p.max_price,atr_pct:m.atrPct};const event={engine_id:ENGINE_ID,observed_at:nowIso(),symbol,action:"SELL",price:exitPrice,qty:p.qty,notional:gross,pnl,reason,metadata:{policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",entry:p.entry,opened_at:p.opened_at,hold_seconds:Math.round(heldMs/1000),target:p.target,stop:p.stop,trail:p.trail,max_price:p.max_price,spread_bps:m.spreadBps,estimated_cost_bps:estimatedCostBps,mfe_bps:mfeBps,legacy_oversize:legacyOversize,opportunity_score:p.opportunity_score??null,forecast_edge_bps:p.forecast_edge_bps??null,cooldown_minutes:Math.round(cdMs/60000),shadow_only:true,live_execution:false}};await insertEvent(event);actions.push(event);
  }

  const currentEq=equity({...state,cash,positions} as State,markets),recent=await recentRisk(),mode=riskMode({...state,realized_pnl:realized,win_count:wins,loss_count:losses} as State,currentEq,recent);
  const evals:J[]=[],readyRows:Ready[]=[];
  for(const c of radar.rows){const m=markets.get(c.symbol);if(!m)continue;const ev=evaluateEntry(c,m,mode),guard=reentryCheck(cooldowns[c.symbol],c,m,ev,now),already=!!positions[c.symbol];if(guard.clear)delete cooldowns[c.symbol];const reason=already?"POSITION_OPEN":guard.blocked?guard.reason:ev.reason,ready=ev.ok&&!guard.blocked&&!already;evals.push({symbol:c.symbol,price:m.mid,radar_score:c.radar_score,change_pct:c.price_change_pct,range_pct:c.range_pct,spread_bps:m.spreadBps,atr_pct:m.atrPct,pullback_pct:m.pullbackPct,bounce_pct:m.bouncePct,signal_score:ev.score,opportunity_score:ev.opportunity,estimated_cost_bps:ev.costBps,forecast_gross_bps:ev.forecastGrossBps,uncertainty_bps:ev.uncertaintyBps,forecast_net_bps:ev.forecastNetBps,ready,reason,gates:ev.gates,reentry_guard:guard.metrics,policy_version:POLICY_VERSION,risk_mode:mode.name});if(ready)readyRows.push({c,m,ev,guard});}
  readyRows.sort((a,b)=>b.ev.opportunity-a.ev.opportunity||b.ev.forecastNetBps-a.ev.forecastNetBps||b.c.radar_score-a.c.radar_score);

  for(const row of readyRows){if(mode.frozen||Object.keys(positions).length>=MAX_POSITIONS)break;const {c,m,ev,guard}=row;const liveEq=Math.max(0,equity({...state,cash,positions} as State,markets));const openGross=Object.values(positions).reduce((s,p)=>s+p.qty*p.entry,0),totalGrossCap=liveEq*mode.grossCapPct*MAX_POSITIONS,remainingGross=Math.max(0,totalGrossCap-openGross),perPositionGross=liveEq*mode.grossCapPct,riskBudget=liveEq*mode.riskCapPct;const stopDistance=Math.min(m.ask*.022,Math.max(m.atr*1.25,m.ask*.0075)),riskPerDollar=stopDistance/m.ask+ev.costBps/10000,grossByRisk=riskBudget/Math.max(.0001,riskPerDollar),budget=Math.min(cash*.92,perPositionGross,remainingGross,grossByRisk);if(budget<20)continue;const slipBps=Math.max(2,m.spreadBps/2),entry=m.ask*(1+slipBps/10000),grossBudget=budget/(1+FEE_BPS/10000),qty=grossBudget/entry,openFee=grossBudget*FEE_BPS/10000,costBasis=grossBudget+openFee;let targetDistance=Math.max(m.atr*1.55,entry*(ev.costBps*2.8/10000),stopDistance*1.65);targetDistance=Math.min(targetDistance,entry*.045);const p:Position={symbol:c.symbol,entry,qty,opened_at:nowIso(),stop:entry-stopDistance,target:entry+targetDistance,trail:null,max_price:entry,open_fee:openFee,cost_basis:costBasis,atr:m.atr,radar_score:c.radar_score,opportunity_score:ev.opportunity,forecast_edge_bps:ev.forecastNetBps,entry_spread_bps:m.spreadBps,entry_reason:guard.metrics.guard_reset?`V85_${String(guard.metrics.guard_reset)}`:ev.reason,policy_version:POLICY_VERSION,estimated_cost_bps:ev.costBps};positions[c.symbol]=p;cash-=costBasis;const action={engine_id:ENGINE_ID,observed_at:nowIso(),symbol:c.symbol,action:"BUY",price:entry,qty,notional:grossBudget,pnl:null,reason:p.entry_reason,metadata:{policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",risk_mode:mode.name,gross_cap_pct:mode.grossCapPct,risk_cap_pct:mode.riskCapPct,estimated_risk_usd:grossBudget*riskPerDollar,signal_score:ev.score,opportunity_score:ev.opportunity,forecast_gross_bps:ev.forecastGrossBps,uncertainty_bps:ev.uncertaintyBps,forecast_net_bps:ev.forecastNetBps,estimated_cost_bps:ev.costBps,radar_score:c.radar_score,change_pct:c.price_change_pct,atr_pct:m.atrPct,pullback_pct:m.pullbackPct,bounce_pct:m.bouncePct,spread_bps:m.spreadBps,target:p.target,stop:p.stop,fee_bps:FEE_BPS,slippage_bps:slipBps,reentry_guard:guard.metrics,shadow_only:true,live_execution:false}};await insertEvent(action);actions.push(action);}

  const minute=new Date(Math.floor(now/60000)*60000).toISOString();if(state.last_eval_minute!==minute&&evals.length){const rows=evals.map(e=>({engine_id:ENGINE_ID,observed_at:nowIso(),symbol:e.symbol,price:e.price,radar_score:e.radar_score,signal_score:e.signal_score,action:e.ready?"READY":"WAIT",reason:e.reason,metadata:e}));const q=await db.from("brian_dip_multiasset_evaluations").insert(rows);if(q.error)throw q.error;}
  const finalEquity=equity({...state,cash,positions} as State,markets);const finalState={cash,realized_pnl:realized,trade_count:tradeCount,win_count:wins,loss_count:losses,positions,cooldowns,last_eval_minute:minute,last_scan:{status:"RUNNING",policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",risk_mode:mode.name,risk_reason:mode.reason,drawdown_pct:mode.drawdownPct,win_rate:mode.winRate,gross_cap_pct:mode.grossCapPct,risk_cap_pct:mode.riskCapPct,loss_streak:recent.streak,radar_observed_at:radar.observedAt,scanned:evals.slice(0,MAX_SCAN),ranked_ready:readyRows.slice(0,5).map(x=>({symbol:x.c.symbol,opportunity_score:x.ev.opportunity,forecast_net_bps:x.ev.forecastNetBps,radar_score:x.c.radar_score})),actions,market_errors:errors,equity:finalEquity,position_count:Object.keys(positions).length,max_positions:MAX_POSITIONS},updated_at:nowIso(),enabled:true,shadow_only:true,live_execution:false};const uq=await db.from("brian_dip_multiasset_state").update(finalState).eq("engine_id",ENGINE_ID);if(uq.error)throw uq.error;return{status:"RUNNING",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",risk_mode:mode.name,risk_reason:mode.reason,run_until:state.run_until,equity:finalEquity,cash,realized_pnl:realized,trade_count:tradeCount,positions:Object.keys(positions),ranked_ready:(finalState.last_scan as J).ranked_ready,scanned:evals.slice(0,MAX_SCAN),actions,shadow_only:true,live_execution:false};
}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response("method",{status:405});let lease:{owner:string;generation:number}|null=null;try{await requireCron(req);lease=await acquireLease();if(!lease)return Response.json({status:"WAIT_LEASE",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,shadow_only:true,live_execution:false});const out=await run();return Response.json(out,{headers:{"cache-control":"no-store"}});}catch(e){const message=e instanceof Error?e.message:String(e);console.error("dip-v85-guardian",message);return Response.json({status:"FAILED_CLOSED",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,error:message,shadow_only:true,live_execution:false},{status:message.includes("UNAUTHORIZED")?401:500,headers:{"cache-control":"no-store"}});}finally{await releaseLease(lease);}});
