import { createClient } from "npm:@supabase/supabase-js@2.116.0";

const URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(URL, SERVICE, { auth: { persistSession: false, autoRefreshToken: false } });

const ENGINE_ID = "dip-multiasset-v1";
const POLICY_VERSION = "dip-v85-guardian-resilient-20260914.2";
const RUN_HOURS = 18;
const MAX_POSITIONS = 2;
const MAX_SCAN = 12;
const FEE_BPS = 10;
const SESSION_DD_STOP = 0.020;
const LOSS_STREAK_STOP = 3;
const LOSS_STREAK_PAUSE_MS = 45 * 60_000;
const RADAR_SOFT_STALE_MS = 12 * 60_000;
const RADAR_HARD_STALE_MS = 4 * 60 * 60_000;
const LOSS_COOLDOWN_MS = 45 * 60_000;
const TARGET_COOLDOWN_MS = 30 * 60_000;
const PROFIT_COOLDOWN_MS = 25 * 60_000;
const BASE_COOLDOWN_MS = 20 * 60_000;
const GUARD_MAX_AGE_MS = 4 * 60 * 60_000;
const HOSTS = ["https://api.binance.com", "https://api1.binance.com", "https://api2.binance.com"];
const EXCLUDED = new Set(["ETHUSDT","USDTUSDT","USDCUSDT","FDUSDUSDT","TUSDUSDT","DAIUSDT","BUSDUSDT","EURUSDT","TRYUSDT","USD1USDT"]);

type J = Record<string, unknown>;
type Position = { symbol:string; entry:number; qty:number; opened_at:string; stop:number; target:number; trail:number|null; max_price:number; open_fee:number; cost_basis:number; atr:number; radar_score:number; opportunity_score?:number; forecast_edge_bps?:number; entry_spread_bps:number; entry_reason:string; policy_version?:string; estimated_cost_bps?:number; };
type Guard = { until:number; reason:string; exit_price:number; exit_at:number; pnl:number; peak_price:number; atr_pct:number; };
type State = { engine_id:string; started_at:string; run_until:string; starting_equity:number; cash:number; realized_pnl:number; trade_count:number; win_count:number; loss_count:number; positions:Record<string,Position>; cooldowns:Record<string,number|Guard>; last_scan:J; last_eval_minute:string|null; updated_at:string; enabled:boolean; shadow_only:boolean; live_execution:boolean; };
type Candidate = { symbol:string; base_asset:string; radar_score:number; price_change_pct:number; range_pct:number; spread_bps:number; quote_volume:number; trades_24h:number; momentum_score:number; volatility_score:number; };
type Bar = { o:number; h:number; l:number; c:number; v:number; openTime:number; closeTime:number };
type Market = { symbol:string; bid:number; ask:number; mid:number; spreadBps:number; bars:Bar[]; atr:number; atrPct:number; ema8:number; ema21:number; recentLow:number; recentHigh:number; pullbackPct:number; bouncePct:number; lastClose:number; prevClose:number; recovery:boolean; trendOk:boolean; };
type EntryEval = { ok:boolean; score:number; opportunity:number; costBps:number; grossBps:number; uncertaintyBps:number; netBps:number; requiredPull:number; requiredBounce:number; gates:Record<string,boolean>; reason:string; };
type RiskMode = { name:"DEFENSIVE"|"COLD"|"NORMAL"|"FROZEN"; grossCapPct:number; riskCapPct:number; minScore:number; minOpportunity:number; frozen:boolean; reason:string; drawdownPct:number; winRate:number; };
type Ready = { c:Candidate; m:Market; ev:EntryEval; guard:{blocked:boolean;reason:string;clear:boolean;metrics:J} };

function num(v:unknown,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function clip(v:number,lo=0,hi=1){return Math.max(lo,Math.min(hi,v));}
function iso(){return new Date().toISOString();}
async function sha256Hex(v:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)));return[...d].map(b=>b.toString(16).padStart(2,"0")).join("");}
function same(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function requireCron(req:Request){const supplied=(req.headers.get("x-brian-cron-key")||"").trim();if(!supplied)throw Error("UNAUTHORIZED_CRON");const q=await db.from("brian_dashboard_auth").select("cron_key_sha256").eq("auth_id","control-v3").single();if(q.error||!q.data)throw Error("CRON_AUTH_UNAVAILABLE");if(!same(await sha256Hex(supplied),String(q.data.cron_key_sha256||"")))throw Error("UNAUTHORIZED_CRON");}
async function marketJson(path:string){let last="MARKET_UNAVAILABLE";for(const host of HOSTS){try{const r=await fetch(host+path,{headers:{accept:"application/json","user-agent":"Brian-DIP-V85-Guardian/2.0"},signal:AbortSignal.timeout(5000)});if(!r.ok){last=`HTTP_${r.status}`;if(r.status===418||r.status===429)break;continue;}return await r.json();}catch(e){last=e instanceof Error?e.message:String(e);}}throw Error(`BINANCE_SPOT:${last}`);}
function ema(xs:number[],p:number){const k=2/(p+1);let out=xs[0]??0;for(let i=1;i<xs.length;i++)out=xs[i]*k+out*(1-k);return out;}
function atr(b:Bar[],p=14){if(b.length<p+2)return 0;const x:number[]=[];for(let i=1;i<b.length;i++){const z=b[i],pr=b[i-1].c;x.push(Math.max(z.h-z.l,Math.abs(z.h-pr),Math.abs(z.l-pr)));}return x.slice(-p).reduce((a,c)=>a+c,0)/p;}
async function loadMarket(symbol:string):Promise<Market>{const [rb,rbook]=await Promise.all([marketJson(`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=1m&limit=70`),marketJson(`/api/v3/ticker/bookTicker?symbol=${encodeURIComponent(symbol)}`)]);if(!Array.isArray(rb)||rb.length<35)throw Error("INSUFFICIENT_BARS");const now=Date.now();const parsed:Bar[]=rb.map(x=>{if(!Array.isArray(x)||x.length<7)throw Error("BAD_BAR");return{o:num(x[1]),h:num(x[2]),l:num(x[3]),c:num(x[4]),v:num(x[5]),openTime:num(x[0]),closeTime:num(x[6])};});const bars=parsed.filter(x=>x.closeTime<now-250).slice(-60);if(bars.length<30)throw Error("INSUFFICIENT_CLOSED_BARS");const book=rbook as J,bid=num(book.bidPrice),ask=num(book.askPrice);if(!(bid>0&&ask>bid))throw Error("BAD_BOOK");const mid=(bid+ask)/2,spreadBps=(ask-bid)/mid*10000;if(!Number.isFinite(spreadBps)||spreadBps>30)throw Error("WIDE_BOOK");const closes=bars.map(x=>x.c),a=atr(bars),lastClose=bars.at(-1)!.c,prevClose=bars.at(-2)!.c,recent20=bars.slice(-20),recent12=bars.slice(-12),recentHigh=Math.max(...recent20.map(x=>x.h)),recentLow=Math.min(...recent12.map(x=>x.l)),atrPct=a/mid*100;return{symbol,bid,ask,mid,spreadBps,bars,atr:a,atrPct,ema8:ema(closes.slice(-35),8),ema21:ema(closes.slice(-45),21),recentLow,recentHigh,pullbackPct:(recentHigh-mid)/recentHigh*100,bouncePct:(mid-recentLow)/recentLow*100,lastClose,prevClose,recovery:mid>=lastClose*.999&&lastClose>=prevClose*.9975,trendOk:ema(closes.slice(-35),8)>=ema(closes.slice(-45),21)*.992};}
async function acquireLease(){const owner=crypto.randomUUID(),q=await db.rpc("brian_dip_v84_acquire_lease",{p_lease_key:"brian-dip-multiasset-worker-v1",p_owner_id:owner,p_lease_seconds:45});if(q.error)throw Error("LEASE:"+q.error.message);const row=Array.isArray(q.data)?q.data[0]:q.data;if(!row?.acquired)return null;return{owner,generation:Number(row.lease_generation)};}
async function releaseLease(l:{owner:string;generation:number}|null){if(!l)return;try{await db.rpc("brian_dip_v84_release_lease",{p_lease_key:"brian-dip-multiasset-worker-v1",p_owner_id:l.owner,p_lease_generation:l.generation});}catch{}}
async function loadState():Promise<State>{const q=await db.from("brian_dip_multiasset_state").select("*").eq("engine_id",ENGINE_ID).maybeSingle();if(q.error)throw q.error;if(q.data)return q.data as State;const now=new Date(),row={engine_id:ENGINE_ID,started_at:now.toISOString(),run_until:new Date(now.getTime()+RUN_HOURS*3600_000).toISOString(),starting_equity:1000,cash:1000,realized_pnl:0,trade_count:0,win_count:0,loss_count:0,positions:{},cooldowns:{},last_scan:{status:"BOOT",policy_version:POLICY_VERSION},last_eval_minute:null,updated_at:now.toISOString(),enabled:true,shadow_only:true,live_execution:false};const i=await db.from("brian_dip_multiasset_state").insert(row).select("*").single();if(i.error)throw i.error;return i.data as State;}
async function latestCandidates(){const q=await db.from("brian_universe_snapshots").select("observed_at,candidates").order("observed_at",{ascending:false}).limit(1).maybeSingle();if(q.error||!q.data)throw Error("RADAR_UNAVAILABLE");const observedAt=String(q.data.observed_at),ageMs=Date.now()-Date.parse(observedAt);if(!Number.isFinite(ageMs)||ageMs>RADAR_HARD_STALE_MS)throw Error("RADAR_HARD_STALE");const stale=ageMs>RADAR_SOFT_STALE_MS,payload=(q.data.candidates??{}) as J,raw=Array.isArray(payload.candidates)?payload.candidates:[];const rows:Candidate[]=raw.map(v=>{const r=(v??{}) as J;return{symbol:String(r.symbol||"").toUpperCase(),base_asset:String(r.base_asset||"").toUpperCase(),radar_score:num(r.radar_score),price_change_pct:num(r.price_change_pct),range_pct:num(r.range_pct),spread_bps:num(r.spread_bps,999),quote_volume:num(r.quote_volume),trades_24h:num(r.trades_24h),momentum_score:num(r.momentum_score),volatility_score:num(r.volatility_score)}}).filter(r=>/^[A-Z0-9]{2,20}USDT$/.test(r.symbol)&&!EXCLUDED.has(r.symbol)&&r.radar_score>=(stale?.74:.70)&&r.quote_volume>=8_000_000&&r.trades_24h>=35_000&&r.spread_bps<=18&&Math.abs(r.price_change_pct)<=60).sort((a,b)=>(b.radar_score*.62+clip(b.momentum_score)*.22+clip(b.volatility_score)*.16)-(a.radar_score*.62+clip(a.momentum_score)*.22+clip(a.volatility_score)*.16)).slice(0,MAX_SCAN);return{observedAt,ageSec:Math.round(ageMs/1000),stale,rows};}
function equity(state:State,markets:Map<string,Market>){let e=num(state.cash);for(const p of Object.values(state.positions||{})){const m=markets.get(p.symbol);e+=p.qty*(m?.bid??p.entry);}return e;}
function cooldownMs(reason:string,pnl:number){if(reason==="TARGET")return TARGET_COOLDOWN_MS;if(pnl<0||reason==="STOP"||reason==="MOMENTUM_BREAK"||reason==="EDGE_DECAY")return LOSS_COOLDOWN_MS;if(reason==="TRAIL"||pnl>0)return PROFIT_COOLDOWN_MS;return BASE_COOLDOWN_MS;}
function readGuard(raw:unknown):Guard|null{if(typeof raw==="number"&&Number.isFinite(raw))return{until:raw,reason:"LEGACY",exit_price:0,exit_at:raw-BASE_COOLDOWN_MS,pnl:0,peak_price:0,atr_pct:0};if(!raw||typeof raw!=="object")return null;const r=raw as J,until=num(r.until);return until>0?{until,reason:String(r.reason||"UNKNOWN"),exit_price:num(r.exit_price),exit_at:num(r.exit_at,until-BASE_COOLDOWN_MS),pnl:num(r.pnl),peak_price:num(r.peak_price),atr_pct:num(r.atr_pct)}:null;}
async function hydrateGuards(state:State,cooldowns:Record<string,number|Guard>){const q=await db.from("brian_dip_multiasset_events").select("observed_at,symbol,pnl,reason,price,metadata").eq("engine_id",ENGINE_ID).eq("action","SELL").gte("observed_at",state.started_at).order("observed_at",{ascending:false}).limit(60);if(q.error)return;const seen=new Set<string>();for(const r of q.data||[]){const s=String(r.symbol||"");if(!s||seen.has(s)||cooldowns[s])continue;seen.add(s);const at=Date.parse(String(r.observed_at)),pnl=num(r.pnl),reason=String(r.reason||"UNKNOWN"),meta=(r.metadata||{}) as J;cooldowns[s]={until:at+cooldownMs(reason,pnl),reason,exit_price:num(r.price),exit_at:at,pnl,peak_price:num(meta.max_price),atr_pct:num(meta.atr_pct)};}}
async function recentRisk(state:State){const q=await db.from("brian_dip_multiasset_events").select("observed_at,pnl").eq("engine_id",ENGINE_ID).eq("action","SELL").gte("observed_at",state.started_at).order("observed_at",{ascending:false}).limit(8);if(q.error)return{streak:0,lastLossAt:0};let streak=0,lastLossAt=0;for(let i=0;i<(q.data||[]).length;i++){const pnl=num(q.data![i].pnl);if(i===0&&pnl<0)lastLossAt=Date.parse(String(q.data![i].observed_at));if(pnl<0&&streak===i)streak++;else break;}return{streak,lastLossAt};}
function riskMode(state:State,currentEquity:number,risk:{streak:number;lastLossAt:number},radarStale:boolean):RiskMode{const start=Math.max(1,num(state.starting_equity,1000)),dd=(start-currentEquity)/start,closed=num(state.win_count)+num(state.loss_count),wr=closed?num(state.win_count)/closed:0,streakFrozen=risk.streak>=LOSS_STREAK_STOP&&Date.now()-risk.lastLossAt<LOSS_STREAK_PAUSE_MS;if(dd>=SESSION_DD_STOP||streakFrozen)return{name:"FROZEN",grossCapPct:0,riskCapPct:0,minScore:.99,minOpportunity:.99,frozen:true,reason:dd>=SESSION_DD_STOP?"SESSION_DRAWDOWN":"LOSS_STREAK",drawdownPct:dd,winRate:wr};if(radarStale)return{name:"DEFENSIVE",grossCapPct:.03,riskCapPct:.0025,minScore:.82,minOpportunity:.81,frozen:false,reason:"RADAR_SOFT_STALE",drawdownPct:dd,winRate:wr};if(closed<8||wr<.35||num(state.realized_pnl)<-start*.01)return{name:"DEFENSIVE",grossCapPct:.04,riskCapPct:.0035,minScore:.80,minOpportunity:.79,frozen:false,reason:"LOW_SAMPLE_OR_WEAK_ECONOMICS",drawdownPct:dd,winRate:wr};if(closed<20)return{name:"COLD",grossCapPct:.05,riskCapPct:.004,minScore:.76,minOpportunity:.75,frozen:false,reason:"CALIBRATING",drawdownPct:dd,winRate:wr};return{name:"NORMAL",grossCapPct:.08,riskCapPct:.005,minScore:.74,minOpportunity:.74,frozen:false,reason:"WARM",drawdownPct:dd,winRate:wr};}
function evaluate(c:Candidate,m:Market,mode:RiskMode):EntryEval{const atrBps=m.atrPct*100,slip=Math.max(2,m.spreadBps/2),costBps=2*FEE_BPS+m.spreadBps+2*slip,requiredPull=Math.max(.60,m.atrPct*.72),requiredBounce=Math.max(.18,m.atrPct*.18),structural=Math.max(0,(m.recentHigh-m.ask)/m.ask*10000),quality=clip(.60+(c.radar_score-.70)*.85+clip(c.momentum_score-.55,0,.45)*.35,.58,1),grossBps=Math.min(structural,atrBps*1.60)*quality,uncertaintyBps=Math.max(8,atrBps*.18,costBps*.35),netBps=grossBps-costBps-uncertaintyBps,score=clip(c.radar_score*.34+clip(m.pullbackPct/Math.max(requiredPull*1.7,.7))*.20+clip(m.bouncePct/Math.max(requiredBounce*2.6,.3))*.13+(m.recovery?.10:0)+(m.trendOk?.08:0)+clip(netBps/100)*.15),opportunity=clip(score*.62+c.radar_score*.22+clip(c.momentum_score)*.08+clip(netBps/100)*.08),gates={radar:c.radar_score>=(mode.name==="DEFENSIVE"?.80:.76),spread:m.spreadBps<=(mode.name==="DEFENSIVE"?8:12),day_move:Math.abs(c.price_change_pct)<=35,pullback:m.pullbackPct>=requiredPull,bounce:m.bouncePct>=requiredBounce,recovery:m.recovery,trend:m.trendOk,not_chasing:m.mid<=m.recentHigh*(1-Math.max(.002,m.atrPct*.12/100)),economics:netBps>=Math.max(18,costBps*.70)&&grossBps>=costBps*2.15},ok=!mode.frozen&&score>=mode.minScore&&opportunity>=mode.minOpportunity&&Object.values(gates).every(Boolean),failed=Object.entries(gates).filter(([,v])=>!v).map(([k])=>k);return{ok,score,opportunity,costBps,grossBps,uncertaintyBps,netBps,requiredPull,requiredBounce,gates,reason:ok?"V85_EDGE_READY":mode.frozen?`RISK_FROZEN_${mode.reason}`:`WAIT_${failed.join("+")||"SCORE"}`};}
function reentry(raw:unknown,c:Candidate,m:Market,ev:EntryEval,now:number){const g=readGuard(raw);if(!g)return{blocked:false,reason:"",clear:raw!=null,metrics:{}};const age=Math.max(0,now-g.exit_at),base={guard_reason:g.reason,guard_age_sec:Math.round(age/1000),cooldown_left_sec:Math.max(0,Math.round((g.until-now)/1000)),last_exit_price:g.exit_price,last_exit_pnl:g.pnl};if(now<g.until)return{blocked:true,reason:`COOLDOWN_${g.reason}`,clear:false,metrics:base};if(age>GUARD_MAX_AGE_MS||g.reason==="LEGACY")return{blocked:false,reason:"",clear:true,metrics:{...base,guard_reset:"AGED_OUT"}};const lower=g.exit_price>0?m.mid<=g.exit_price*(1-Math.max(.0025,m.atrPct*.20/100)):true;if(g.reason==="TARGET"){const fresh=lower&&m.pullbackPct>=Math.max(.8,ev.requiredPull*1.2)&&m.bouncePct>=Math.max(.22,ev.requiredBounce*1.25)&&ev.score>=.76&&c.radar_score>=.78;return fresh?{blocked:false,reason:"",clear:true,metrics:{...base,guard_reset:"NEW_DIP_AFTER_TARGET"}}:{blocked:true,reason:"TARGET_LEG_LOCK",clear:false,metrics:{...base,lower_than_exit:lower}};}const loss=g.pnl<0||["STOP","MOMENTUM_BREAK","EDGE_DECAY"].includes(g.reason);if(loss){const notChasing=g.exit_price>0?m.mid<=g.exit_price*(1+Math.max(.0025,m.atrPct*.25/100)):true,strong=notChasing&&ev.score>=.84&&ev.opportunity>=.82&&c.radar_score>=.82&&m.pullbackPct>=Math.max(.9,ev.requiredPull*1.4)&&m.bouncePct>=Math.max(.28,ev.requiredBounce*1.55)&&m.recovery&&m.trendOk;return strong?{blocked:false,reason:"",clear:true,metrics:{...base,guard_reset:"STRONG_RECLAIM_AFTER_LOSS"}}:{blocked:true,reason:"LOSS_REENTRY_GUARD",clear:false,metrics:{...base,not_chasing_old_exit:notChasing}};}const fresh=lower&&ev.score>=.78&&ev.opportunity>=.77&&c.radar_score>=.78&&m.pullbackPct>=Math.max(.70,ev.requiredPull*1.15)&&m.recovery;return fresh?{blocked:false,reason:"",clear:true,metrics:{...base,guard_reset:"FRESH_PULLBACK_AFTER_PROFIT"}}:{blocked:true,reason:"PROFIT_REENTRY_GUARD",clear:false,metrics:{...base,lower_than_exit:lower}};}
async function event(row:J){const q=await db.from("brian_dip_multiasset_events").insert(row);if(q.error)throw q.error;}

async function run(){const state=await loadState(),now=Date.now();if(!state.enabled||now>=Date.parse(state.run_until)){await db.from("brian_dip_multiasset_state").update({enabled:false,updated_at:iso(),last_scan:{status:"WINDOW_COMPLETE",policy_version:POLICY_VERSION}}).eq("engine_id",ENGINE_ID);return{status:"WINDOW_COMPLETE",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,shadow_only:true,live_execution:false};}const radar=await latestCandidates(),symbols=[...new Set([...Object.keys(state.positions||{}),...radar.rows.map(x=>x.symbol)])].slice(0,MAX_SCAN+MAX_POSITIONS),pairs=await Promise.all(symbols.map(async s=>{try{return[s,await loadMarket(s)] as const;}catch(e){return[s,{error:e instanceof Error?e.message:String(e)}] as const;}})),markets=new Map<string,Market>(),errors:J={};for(const[s,v]of pairs){if("error" in v)errors[s]=v.error;else markets.set(s,v);}const positions={...(state.positions||{})},cooldowns={...(state.cooldowns||{})};await hydrateGuards(state,cooldowns);let cash=num(state.cash),realized=num(state.realized_pnl),trades=num(state.trade_count),wins=num(state.win_count),losses=num(state.loss_count);const actions:J[]=[];
for(const[s,p]of Object.entries(positions)){const m=markets.get(s);if(!m)continue;const held=now-Date.parse(p.opened_at),slip=Math.max(2,m.spreadBps/2),cost=num(p.estimated_cost_bps,2*FEE_BPS+m.spreadBps+2*slip);p.max_price=Math.max(num(p.max_price,p.entry),m.bid);const legacy=p.policy_version!==POLICY_VERSION||p.cost_basis>Math.max(1,num(state.starting_equity))*0.12,mfe=(p.max_price-p.entry)/p.entry*10000,arm=Math.max(cost+18,m.atrPct*100*.75);if(!legacy&&mfe>=arm){const floor=p.entry*(1+(cost+10)/10000),candidate=Math.max(floor,m.bid-Math.max(m.atr*.58,p.entry*.0045));p.trail=Math.max(num(p.trail),candidate);}const momentum=held>4*60_000&&m.ema8<m.ema21*.996&&m.lastClose<m.prevClose*.997&&m.bid<p.entry*(1+cost/10000),decay=held>9*60_000&&!m.recovery&&m.bid<p.entry*(1+Math.max(cost,12)/10000);let reason=legacy?"LEGACY_RISK_RESET":"";if(!reason&&m.bid<=p.stop)reason="STOP";else if(!reason&&p.trail&&m.bid<=p.trail)reason="TRAIL";else if(!reason&&m.bid>=p.target)reason="TARGET";else if(!reason&&momentum)reason="MOMENTUM_BREAK";else if(!reason&&decay)reason="EDGE_DECAY";else if(!reason&&held>=45*60_000)reason="MAX_HOLD";if(!reason)continue;const exit=m.bid*(1-slip/10000),gross=p.qty*exit,fee=gross*FEE_BPS/10000,pnl=gross-fee-p.cost_basis;cash+=gross-fee;realized+=pnl;trades++;if(pnl>.01)wins++;else if(pnl<-.01)losses++;delete positions[s];const cd=cooldownMs(reason,pnl);cooldowns[s]={until:now+cd,reason,exit_price:exit,exit_at:now,pnl,peak_price:p.max_price,atr_pct:m.atrPct};const row={engine_id:ENGINE_ID,observed_at:iso(),symbol:s,action:"SELL",price:exit,qty:p.qty,notional:gross,pnl,reason,metadata:{policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",entry:p.entry,hold_seconds:Math.round(held/1000),target:p.target,stop:p.stop,trail:p.trail,max_price:p.max_price,estimated_cost_bps:cost,legacy_reset:legacy,shadow_only:true,live_execution:false}};await event(row);actions.push(row);}
const current=equity({...state,cash,positions} as State,markets),rr=await recentRisk({...state,win_count:wins,loss_count:losses} as State),mode=riskMode({...state,realized_pnl:realized,win_count:wins,loss_count:losses} as State,current,rr,radar.stale),evals:J[]=[],ready:Ready[]=[];for(const c of radar.rows){const m=markets.get(c.symbol);if(!m)continue;const ev=evaluate(c,m,mode),g=reentry(cooldowns[c.symbol],c,m,ev,now),open=!!positions[c.symbol];if(g.clear)delete cooldowns[c.symbol];const reason=open?"POSITION_OPEN":g.blocked?g.reason:ev.reason,isReady=ev.ok&&!g.blocked&&!open;evals.push({symbol:c.symbol,price:m.mid,radar_score:c.radar_score,signal_score:ev.score,opportunity_score:ev.opportunity,estimated_cost_bps:ev.costBps,forecast_gross_bps:ev.grossBps,uncertainty_bps:ev.uncertaintyBps,forecast_net_bps:ev.netBps,pullback_pct:m.pullbackPct,bounce_pct:m.bouncePct,spread_bps:m.spreadBps,ready:isReady,reason,gates:ev.gates,reentry_guard:g.metrics,policy_version:POLICY_VERSION,risk_mode:mode.name});if(isReady)ready.push({c,m,ev,guard:g});}ready.sort((a,b)=>b.ev.opportunity-a.ev.opportunity||b.ev.netBps-a.ev.netBps);
for(const x of ready){if(mode.frozen||Object.keys(positions).length>=MAX_POSITIONS)break;const liveEq=Math.max(0,equity({...state,cash,positions} as State,markets)),openGross=Object.values(positions).reduce((s,p)=>s+p.qty*p.entry,0),remaining=Math.max(0,liveEq*mode.grossCapPct*MAX_POSITIONS-openGross),riskUsd=liveEq*mode.riskCapPct,stopDist=Math.min(x.m.ask*.022,Math.max(x.m.atr*1.25,x.m.ask*.0075)),riskPerDollar=stopDist/x.m.ask+x.ev.costBps/10000,budget=Math.min(cash*.92,liveEq*mode.grossCapPct,remaining,riskUsd/Math.max(.0001,riskPerDollar));if(budget<20)continue;const slip=Math.max(2,x.m.spreadBps/2),entry=x.m.ask*(1+slip/10000),gross=budget/(1+FEE_BPS/10000),qty=gross/entry,openFee=gross*FEE_BPS/10000,costBasis=gross+openFee;let targetDist=Math.max(x.m.atr*1.55,entry*(x.ev.costBps*2.8/10000),stopDist*1.65);targetDist=Math.min(targetDist,entry*.045);const p:Position={symbol:x.c.symbol,entry,qty,opened_at:iso(),stop:entry-stopDist,target:entry+targetDist,trail:null,max_price:entry,open_fee:openFee,cost_basis:costBasis,atr:x.m.atr,radar_score:x.c.radar_score,opportunity_score:x.ev.opportunity,forecast_edge_bps:x.ev.netBps,entry_spread_bps:x.m.spreadBps,entry_reason:x.guard.metrics.guard_reset?`V85_${String(x.guard.metrics.guard_reset)}`:x.ev.reason,policy_version:POLICY_VERSION,estimated_cost_bps:x.ev.costBps};positions[x.c.symbol]=p;cash-=costBasis;const row={engine_id:ENGINE_ID,observed_at:iso(),symbol:x.c.symbol,action:"BUY",price:entry,qty,notional:gross,pnl:null,reason:p.entry_reason,metadata:{policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",risk_mode:mode.name,gross_cap_pct:mode.grossCapPct,risk_cap_pct:mode.riskCapPct,estimated_risk_usd:gross*riskPerDollar,signal_score:x.ev.score,opportunity_score:x.ev.opportunity,forecast_net_bps:x.ev.netBps,estimated_cost_bps:x.ev.costBps,target:p.target,stop:p.stop,shadow_only:true,live_execution:false}};await event(row);actions.push(row);}
const minute=new Date(Math.floor(now/60000)*60000).toISOString();if(state.last_eval_minute!==minute&&evals.length){const rows=evals.map(e=>({engine_id:ENGINE_ID,observed_at:iso(),symbol:e.symbol,price:e.price,radar_score:e.radar_score,signal_score:e.signal_score,action:e.ready?"READY":"WAIT",reason:e.reason,metadata:e}));const q=await db.from("brian_dip_multiasset_evaluations").insert(rows);if(q.error)throw q.error;}const finalEq=equity({...state,cash,positions} as State,markets),scan={status:"RUNNING",policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",risk_mode:mode.name,risk_reason:mode.reason,drawdown_pct:mode.drawdownPct,win_rate:mode.winRate,loss_streak:rr.streak,radar_observed_at:radar.observedAt,radar_age_seconds:radar.ageSec,radar_soft_stale:radar.stale,scanned:evals,ranked_ready:ready.slice(0,5).map(x=>({symbol:x.c.symbol,opportunity_score:x.ev.opportunity,forecast_net_bps:x.ev.netBps,radar_score:x.c.radar_score})),actions,market_errors:errors,equity:finalEq,position_count:Object.keys(positions).length,max_positions:MAX_POSITIONS,gross_cap_pct:mode.grossCapPct,risk_cap_pct:mode.riskCapPct};const u=await db.from("brian_dip_multiasset_state").update({cash,realized_pnl:realized,trade_count:trades,win_count:wins,loss_count:losses,positions,cooldowns,last_eval_minute:minute,last_scan:scan,updated_at:iso(),enabled:true,shadow_only:true,live_execution:false}).eq("engine_id",ENGINE_ID);if(u.error)throw u.error;return{status:"RUNNING",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,risk_engine:"V85_GUARDIAN",risk_mode:mode.name,risk_reason:mode.reason,radar_age_seconds:radar.ageSec,radar_soft_stale:radar.stale,equity:finalEq,cash,realized_pnl:realized,trade_count:trades,positions:Object.keys(positions),actions,shadow_only:true,live_execution:false};}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response("method",{status:405});let lease:{owner:string;generation:number}|null=null;try{await requireCron(req);lease=await acquireLease();if(!lease)return Response.json({status:"WAIT_LEASE",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,shadow_only:true,live_execution:false});return Response.json(await run(),{headers:{"cache-control":"no-store"}});}catch(e){const message=e instanceof Error?e.message:String(e);console.error("dip-v85-guardian",message);return Response.json({status:"FAILED_CLOSED",engine_id:ENGINE_ID,policy_version:POLICY_VERSION,error:message,shadow_only:true,live_execution:false},{status:message.includes("UNAUTHORIZED")?401:500,headers:{"cache-control":"no-store"}});}finally{await releaseLease(lease);}});
