import { createClient } from "npm:@supabase/supabase-js@2.116.0";
import { gzip } from "npm:pako@2.1.0";
import { XMLParser } from "npm:fast-xml-parser@4.5.0";
import { requireCronAuth } from "../_shared/cron_auth.ts";
import { withCollectorLease } from "../_shared/collector_lease.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SUPABASE_URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const COLLECTOR_ID="brian-official-primary-eye-v2";
const EVIDENCE="PROSPECTIVE_EVOLUTION_SHADOW";
const BUCKET="brian-intelligence-raw";
const LEASE_SECONDS=150;
const MAX_ENDPOINTS=12;

type FeedItem={title:string;link:string;publishedAt:string|null;guid:string};
function out(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function errorText(error:unknown){if(error instanceof Error)return `${error.name}: ${error.message}`;if(error&&typeof error==="object"){const row=error as Record<string,unknown>;const fields=["code","message","details","hint","status","statusText"].filter(k=>row[k]!=null).map(k=>`${k}=${String(row[k])}`);if(fields.length)return fields.join(" | ");try{return JSON.stringify(error)}catch{}}return String(error)}
async function sha(v:string|Uint8Array){const b=typeof v==="string"?new TextEncoder().encode(v):v;const d=new Uint8Array(await crypto.subtle.digest("SHA-256",b));return[...d].map(x=>x.toString(16).padStart(2,"0")).join("")}
function text(v:unknown):string{if(typeof v==="string")return v.trim();if(v&&typeof v==="object"){const r=v as Record<string,unknown>;return String(r["#text"]??r["@_href"]??r.href??"").trim()}return v==null?"":String(v).trim()}
function arr<T>(v:T|T[]|null|undefined):T[]{return v==null?[]:Array.isArray(v)?v:[v]}
function dateIso(v:unknown):string|null{const raw=text(v);if(!raw)return null;const ms=Date.parse(raw);return Number.isFinite(ms)?new Date(ms).toISOString():null}
function parseFeed(xml:string):FeedItem[]{const parser=new XMLParser({ignoreAttributes:false,trimValues:true,processEntities:true});const doc=parser.parse(xml) as Record<string,unknown>;const rss=(doc.rss as Record<string,unknown>|undefined)?.channel as Record<string,unknown>|undefined;const atom=doc.feed as Record<string,unknown>|undefined;const raw=arr((rss?.item??atom?.entry) as Record<string,unknown>|Record<string,unknown>[]|undefined);const items:FeedItem[]=[];for(const item of raw){if(!item||typeof item!=="object")continue;const links=arr(item.link as unknown);let link="";for(const l of links){const candidate=text(l);if(candidate){link=candidate;break}}const title=text(item.title),guid=text(item.guid??item.id)||link||title,publishedAt=dateIso(item.pubDate??item.published??item.updated);if(title&&guid)items.push({title,link,publishedAt,guid});if(items.length>=100)break}return items}
function assetFor(category:string){if(category.startsWith("CRYPTO_"))return "CRYPTO";if(category.includes("MACRO")||category.includes("CENTRAL_BANK")||category.includes("FUNDING_LIQUIDITY"))return "MACRO";return "GLOBAL_WORLD"}
async function rawCapture(endpoint:any,xml:string,observedAt:string){const raw=new TextEncoder().encode(xml),hash=await sha(raw),compressed=gzip(raw,{level:6}),path=`source-arch-v2/${endpoint.endpoint_id}/${observedAt.slice(0,10)}/${hash}.xml.gz`;const upload=await db.storage.from(BUCKET).upload(path,compressed,{contentType:"application/gzip",upsert:false,cacheControl:"31536000"});if(upload.error&&!/exist|duplicate/i.test(String(upload.error.message)))throw upload.error;const captureId=await sha(`${endpoint.endpoint_id}|${observedAt}|${hash}`);const ins=await db.from("brian_raw_captures").upsert({capture_id:captureId,provider:endpoint.endpoint_id,record_type:`source_arch_v2:${endpoint.category}`,observed_at:observedAt,captured_at:new Date().toISOString(),provenance_uri:endpoint.endpoint_url,payload_hash:hash,payload:{storage_bucket:BUCKET,storage_path:path,content_type:"application/xml",content_encoding:"gzip",source_arch_version:"V2",source_id:endpoint.source_id,tier:endpoint.tier,category:endpoint.category,decision_evidence_locked:true}},{onConflict:"capture_id",ignoreDuplicates:true});if(ins.error)throw ins.error;return captureId}
async function fetchFeed(endpoint:any){const response=await fetch(endpoint.endpoint_url,{redirect:"follow",headers:{accept:"application/rss+xml,application/atom+xml,application/xml,text/xml;q=0.9,*/*;q=0.1","user-agent":"Brian-Market-OS/2.0 primary-eye owner=operator"},signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const xml=await response.text();if(!xml.trim())throw new Error("EMPTY");return xml}
async function ingest(endpoint:any){const observedAt=new Date().toISOString(),xml=await fetchFeed(endpoint),items=parseFeed(xml),captureId=await rawCapture(endpoint,xml,observedAt);const events:any[]=[];for(const item of items){const eventId=await sha(`source-arch-v2|${endpoint.endpoint_id}|${item.guid}|${item.title}`),fingerprint=await sha(`${endpoint.endpoint_id}|${item.title}|${item.link}`),corroboration=await sha(`${endpoint.category}|${item.title.toLowerCase().replace(/[^\p{L}\p{N}]+/gu," ").trim()}`);events.push({event_id:eventId,asset:assetFor(endpoint.category),event_kind:endpoint.tier==="T1_OFFICIAL_PRIMARY"?"OFFICIAL_PRIMARY_RELEASE":"INSTITUTIONAL_RELEASE",source_kind:`SOURCE_ARCH_V2_${endpoint.tier}`,source_id:endpoint.source_id,published_at:item.publishedAt,first_observed_at:observedAt,captured_at:new Date().toISOString(),claim:item.title,direction:0,magnitude:1,trust_class:endpoint.tier==="T1_OFFICIAL_PRIMARY"?"OFFICIAL_PRIMARY":"INDEPENDENT_PROFESSIONAL",entity_confidence:endpoint.tier==="T1_OFFICIAL_PRIMARY"?1:.9,content_fingerprint:fingerprint,corroboration_key:corroboration,provenance_uri:item.link||endpoint.endpoint_url,pit_verified:true,raw_capture_id:captureId,metadata:{source_arch_version:"V2",endpoint_id:endpoint.endpoint_id,organization:endpoint.organization,tier:endpoint.tier,category:endpoint.category,region:endpoint.region,origin_verified:true,direction_not_inferred:true,decision_evidence_locked:true}})}if(events.length){const ins=await db.from("brian_intel_events").upsert(events,{onConflict:"event_id",ignoreDuplicates:true});if(ins.error)throw ins.error}return {endpoint_id:endpoint.endpoint_id,items:items.length,events:events.length,capture_id:captureId}}

async function run(){const startedAt=new Date().toISOString();const q=await db.from("brian_source_endpoints_v2").select("*").eq("lifecycle_state","ACTIVE").in("endpoint_kind",["RSS","ATOM","STATUSPAGE_ATOM"]).is("collector_owner",null).order("priority",{ascending:false}).limit(100);if(q.error)throw q.error;const endpoints=(q.data||[]).filter((e:any)=>e?.metadata?.adapter==="GENERIC_FEED").slice(0,MAX_ENDPOINTS);const results:any[]=[];for(const endpoint of endpoints){try{results.push(await ingest(endpoint))}catch(error){results.push({endpoint_id:endpoint.endpoint_id,error:errorText(error)})}}const failures=results.filter(r=>r.error),observed=results.reduce((a,r)=>a+Number(r.items||0),0),stored=results.reduce((a,r)=>a+Number(r.events||0),0);const runId=await sha(`${COLLECTOR_ID}|${startedAt}|${endpoints.length}|${stored}`);const receipt=await db.from("brian_collector_runs").insert({run_id:runId,collector_id:COLLECTOR_ID,started_at:startedAt,finished_at:new Date().toISOString(),status:failures.length?"DEGRADED":"SUCCESS",observed_records:observed,stored_records:stored,degraded_sources:failures.map(r=>`${r.endpoint_id}:${r.error}`).slice(0,20),error_class:null,error_message:null,evidence_class:EVIDENCE,shadow_only:true,live_execution:false,metadata:{source_arch_version:"V2",active_feed_endpoints:endpoints.length,direction_inference:false,decision_evidence_locked:true}});if(receipt.error)throw receipt.error;return {status:failures.length?"DEGRADED":"SUCCESS",active_feed_endpoints:endpoints.length,observed_items:observed,intel_events:stored,results,shadow_only:true,live_execution:false,decision_evidence_locked:true,dip_touched:false}}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return out({error:"POST required"},405);try{await requireCronAuth(req,db)}catch(error){return out({status:"UNAUTHORIZED",error:errorText(error),shadow_only:true,live_execution:false},401)}try{const lease=await withCollectorLease(db,COLLECTOR_ID,LEASE_SECONDS,run);if(lease.contended)return out({status:"SKIPPED_LEASE_CONTENDED",shadow_only:true,live_execution:false,dip_touched:false});return out(lease.value)}catch(error){return out({status:"FAILED_CLOSED",error:errorText(error),shadow_only:true,live_execution:false,dip_touched:false},500)}});
