export type JsonRecord = Record<string, unknown>;

export type ShadowTick = {
  observed_at: string;
  equity_after_costs: number | string;
  period_pnl: number | string;
  trading_cost: number | string;
  max_drawdown_pct_after: number | string;
  target_weights: Record<string, number | string>;
  drifted_weights: Record<string, number | string>;
  observed_mid_prices: Record<string, number | string>;
  observed_spread_bps?: Record<string, number | string>;
  diagnostics?: JsonRecord;
};

export type TradeEvent = { id:string; observed_at:string; symbol:string; action:"OPEN_LONG"|"OPEN_SHORT"|"ADD"|"REDUCE"|"CLOSE"|"FLIP_TO_LONG"|"FLIP_TO_SHORT"; before_weight:number; after_weight:number; price:number; notional_change:number; estimated_cost:number; realized_pnl:number|null };
export type PositionView = { symbol:string; side:"LONG"|"SHORT"; weight:number; mark_price:number; notional:number; attributed_unrealized_pnl:number };
export type CoinAttribution = { symbol:string; gross_pnl:number; allocated_cost:number; net_pnl:number; action_count:number };
export type EquityPoint = { observed_at:string; equity:number };
export type PolicySnapshot = { starting_equity:number; current_equity:number; session_pnl:number; session_return_pct:number; gross_pnl:number; trading_cost:number; max_drawdown_pct:number; action_count:number; closed_action_count:number; wins:number; losses:number; win_rate_pct:number; open_positions:PositionView[]; trades:TradeEvent[]; coin_attribution:CoinAttribution[]; equity_curve:EquityPoint[]; first_tick_at:string|null; last_tick_at:string|null; source_base_equity:number|null };
export type HourlyReportPayload = { schema_version:"brian.control-center.hourly-report.v1"; session_id:string; policy_kind:"NATIVE"|"PROFIT"; window_start:string; window_end:string; starting_equity:number; ending_equity:number; net_pnl:number; gross_pnl:number; trading_cost:number; return_pct:number; max_drawdown_pct:number; action_count:number; closed_action_count:number; wins:number; losses:number; win_rate_pct:number; best_coin:CoinAttribution|null; worst_coin:CoinAttribution|null; open_positions:PositionView[]; shadow_only:true; live_execution:false };

const EPS=1e-12;
function finite(value:unknown,fallback=0):number{const n=Number(value);return Number.isFinite(n)?n:fallback}
function asWeights(input:Record<string,number|string>|undefined):Record<string,number>{const out:Record<string,number>={};for(const [key,value] of Object.entries(input??{})){const n=finite(value,NaN);if(Number.isFinite(n))out[key]=n}return out}
function allSymbols(...maps:Array<Record<string,unknown>|undefined>):string[]{const set=new Set<string>();for(const map of maps)for(const key of Object.keys(map??{}))set.add(key);return [...set].sort()}
function costAllocation(tick:ShadowTick):Record<string,number>{const drifted=asWeights(tick.drifted_weights),target=asWeights(tick.target_weights),symbols=allSymbols(drifted,target),turnover:Record<string,number>={};let total=0;for(const symbol of symbols){const v=Math.abs((target[symbol]??0)-(drifted[symbol]??0));turnover[symbol]=v;total+=v}const totalCost=Math.max(0,finite(tick.trading_cost)),out:Record<string,number>={};for(const symbol of symbols)out[symbol]=total>EPS?totalCost*turnover[symbol]/total:0;return out}
function markContributions(previous:ShadowTick,current:ShadowTick):Record<string,number>{const previousWeights=asWeights(previous.target_weights),previousPrices=previous.observed_mid_prices??{},currentPrices=current.observed_mid_prices??{},previousEquity=Math.max(0,finite(previous.equity_after_costs)),out:Record<string,number>={};for(const symbol of Object.keys(previousWeights)){const weight=previousWeights[symbol]??0,before=finite(previousPrices[symbol],NaN),now=finite(currentPrices[symbol],NaN);if(Math.abs(weight)<=EPS||!(before>0)||!(now>0))continue;out[symbol]=weight*previousEquity*(now/before-1)}return out}
function classifyAction(before:number,after:number):TradeEvent["action"]|null{if(Math.abs(before-after)<=EPS)return null;if(Math.abs(before)<=EPS&&after>EPS)return"OPEN_LONG";if(Math.abs(before)<=EPS&&after<-EPS)return"OPEN_SHORT";if(Math.abs(after)<=EPS)return"CLOSE";if(Math.sign(before)!==Math.sign(after))return after>0?"FLIP_TO_LONG":"FLIP_TO_SHORT";if(Math.abs(after)>Math.abs(before))return"ADD";return"REDUCE"}

export function derivePolicySnapshot(rawTicks:ShadowTick[],startingEquity:number):PolicySnapshot{
  const ticks=[...rawTicks].sort((a,b)=>Date.parse(a.observed_at)-Date.parse(b.observed_at));const safeStarting=Number.isFinite(startingEquity)&&startingEquity>0?startingEquity:500;
  if(!ticks.length)return{starting_equity:safeStarting,current_equity:safeStarting,session_pnl:0,session_return_pct:0,gross_pnl:0,trading_cost:0,max_drawdown_pct:0,action_count:0,closed_action_count:0,wins:0,losses:0,win_rate_pct:0,open_positions:[],trades:[],coin_attribution:[],equity_curve:[],first_tick_at:null,last_tick_at:null,source_base_equity:null};
  const sourceBase=Math.max(EPS,finite(ticks[0].equity_after_costs,1)),scale=safeStarting/sourceBase,coin=new Map<string,CoinAttribution>(),trades:TradeEvent[]=[],openPnl:Record<string,number>={};const equityCurve:EquityPoint[]=ticks.map(tick=>({observed_at:tick.observed_at,equity:finite(tick.equity_after_costs)*scale}));let grossPnl=0,totalCost=0,previous:ShadowTick=ticks[0];
  for(const tick of ticks.slice(1)){
    const currentCostBySymbol=costAllocation(tick),currentCost=Math.max(0,finite(tick.trading_cost))*scale;totalCost+=currentCost;const marks=markContributions(previous,tick);
    for(const [symbol,sourcePnl] of Object.entries(marks)){const pnl=sourcePnl*scale;grossPnl+=pnl;const row=coin.get(symbol)??{symbol,gross_pnl:0,allocated_cost:0,net_pnl:0,action_count:0};row.gross_pnl+=pnl;row.net_pnl+=pnl;coin.set(symbol,row);openPnl[symbol]=(openPnl[symbol]??0)+pnl}
    for(const [symbol,sourceCost] of Object.entries(currentCostBySymbol)){const allocated=sourceCost*scale;if(allocated<=EPS)continue;const row=coin.get(symbol)??{symbol,gross_pnl:0,allocated_cost:0,net_pnl:0,action_count:0};row.allocated_cost+=allocated;row.net_pnl-=allocated;coin.set(symbol,row)}
    const beforeWeights=asWeights(previous.target_weights),afterWeights=asWeights(tick.target_weights),symbols=allSymbols(beforeWeights,afterWeights),equity=finite(tick.equity_after_costs)*scale,totalTurnover=symbols.reduce((sum,symbol)=>sum+Math.abs((afterWeights[symbol]??0)-(beforeWeights[symbol]??0)),0);
    for(const symbol of symbols){const before=beforeWeights[symbol]??0,after=afterWeights[symbol]??0,action=classifyAction(before,after);if(!action)continue;const price=finite(tick.observed_mid_prices?.[symbol],0),delta=Math.abs(after-before),actionCost=totalTurnover>EPS?currentCost*delta/totalTurnover:0;let realized:number|null=null;if(action==="OPEN_LONG"||action==="OPEN_SHORT"||action==="ADD")openPnl[symbol]=(openPnl[symbol]??0)-actionCost;else if(action==="REDUCE"){const fraction=Math.min(1,Math.max(0,(Math.abs(before)-Math.abs(after))/Math.max(Math.abs(before),EPS))),available=openPnl[symbol]??0;realized=available*fraction-actionCost;openPnl[symbol]=available*(1-fraction)}else if(action==="CLOSE"){realized=(openPnl[symbol]??0)-actionCost;openPnl[symbol]=0}else{realized=(openPnl[symbol]??0)-actionCost/2;openPnl[symbol]=-actionCost/2}const row=coin.get(symbol)??{symbol,gross_pnl:0,allocated_cost:0,net_pnl:0,action_count:0};row.action_count+=1;coin.set(symbol,row);trades.push({id:`${tick.observed_at}|${symbol}|${action}`,observed_at:tick.observed_at,symbol,action,before_weight:before,after_weight:after,price,notional_change:delta*equity,estimated_cost:actionCost,realized_pnl:realized})}
    previous=tick;
  }
  const last=ticks[ticks.length-1],lastWeights=asWeights(last.target_weights),currentEquity=finite(last.equity_after_costs)*scale;const positions:PositionView[]=Object.entries(lastWeights).filter(([,weight])=>Math.abs(weight)>EPS).map(([symbol,weight])=>({symbol,side:weight>0?"LONG" as const:"SHORT" as const,weight,mark_price:finite(last.observed_mid_prices?.[symbol],0),notional:Math.abs(weight)*currentEquity,attributed_unrealized_pnl:openPnl[symbol]??0})).sort((a,b)=>Math.abs(b.weight)-Math.abs(a.weight));const realizedTrades=trades.filter(t=>t.realized_pnl!==null),wins=realizedTrades.filter(t=>(t.realized_pnl??0)>0).length,losses=realizedTrades.filter(t=>(t.realized_pnl??0)<0).length,coinAttribution=[...coin.values()].sort((a,b)=>b.net_pnl-a.net_pnl||a.symbol.localeCompare(b.symbol)),maxDd=maxDrawdownPct(equityCurve.map(p=>p.equity)),sessionPnl=currentEquity-safeStarting;
  return{starting_equity:safeStarting,current_equity:currentEquity,session_pnl:sessionPnl,session_return_pct:100*sessionPnl/safeStarting,gross_pnl:grossPnl,trading_cost:totalCost,max_drawdown_pct:maxDd,action_count:trades.length,closed_action_count:realizedTrades.length,wins,losses,win_rate_pct:realizedTrades.length?100*wins/realizedTrades.length:0,open_positions:positions,trades:trades.slice(-100).reverse(),coin_attribution:coinAttribution,equity_curve:equityCurve.slice(-180),first_tick_at:ticks[0].observed_at,last_tick_at:last.observed_at,source_base_equity:sourceBase};
}

function maxDrawdownPct(equities:number[]):number{let peak=0,maxDd=0;for(const equity of equities){if(!Number.isFinite(equity)||equity<0)continue;peak=Math.max(peak,equity);if(peak>EPS)maxDd=Math.max(maxDd,100*(peak-equity)/peak)}return maxDd}
function attributionDelta(start:CoinAttribution[],end:CoinAttribution[]):CoinAttribution[]{const left=new Map(start.map(r=>[r.symbol,r])),right=new Map(end.map(r=>[r.symbol,r])),symbols=new Set([...left.keys(),...right.keys()]);return[...symbols].map(symbol=>{const before=left.get(symbol),after=right.get(symbol),gross=(after?.gross_pnl??0)-(before?.gross_pnl??0),cost=(after?.allocated_cost??0)-(before?.allocated_cost??0);return{symbol,gross_pnl:gross,allocated_cost:cost,net_pnl:gross-cost,action_count:Math.max(0,(after?.action_count??0)-(before?.action_count??0))}}).filter(r=>Math.abs(r.net_pnl)>EPS||r.action_count>0).sort((a,b)=>b.net_pnl-a.net_pnl||a.symbol.localeCompare(b.symbol))}

export function buildHourlyReport(sessionId:string,policyKind:"NATIVE"|"PROFIT",allTicks:ShadowTick[],startingEquity:number,windowStart:string,windowEnd:string):HourlyReportPayload{
  const all=[...allTicks].sort((a,b)=>Date.parse(a.observed_at)-Date.parse(b.observed_at)),startMs=Date.parse(windowStart),endMs=Date.parse(windowEnd),startSnapshot=derivePolicySnapshot(all.filter(t=>Date.parse(t.observed_at)<=startMs),startingEquity),endSnapshot=derivePolicySnapshot(all.filter(t=>Date.parse(t.observed_at)<=endMs),startingEquity),tradesInWindow=endSnapshot.trades.filter(trade=>{const t=Date.parse(trade.observed_at);return t>startMs&&t<=endMs}),realized=tradesInWindow.filter(t=>t.realized_pnl!==null),wins=realized.filter(t=>(t.realized_pnl??0)>0).length,losses=realized.filter(t=>(t.realized_pnl??0)<0).length,coinDelta=attributionDelta(startSnapshot.coin_attribution,endSnapshot.coin_attribution),best=coinDelta[0]??null,worst=coinDelta.length?coinDelta[coinDelta.length-1]:null,starting=startSnapshot.current_equity,ending=endSnapshot.current_equity,net=ending-starting,gross=endSnapshot.gross_pnl-startSnapshot.gross_pnl,cost=Math.max(0,endSnapshot.trading_cost-startSnapshot.trading_cost),windowEquities=[starting,...endSnapshot.equity_curve.filter(point=>{const t=Date.parse(point.observed_at);return t>startMs&&t<=endMs}).map(point=>point.equity)];
  return{schema_version:"brian.control-center.hourly-report.v1",session_id:sessionId,policy_kind:policyKind,window_start:windowStart,window_end:windowEnd,starting_equity:starting,ending_equity:ending,net_pnl:net,gross_pnl:gross,trading_cost:cost,return_pct:starting>EPS?100*net/starting:0,max_drawdown_pct:maxDrawdownPct(windowEquities),action_count:tradesInWindow.length,closed_action_count:realized.length,wins,losses,win_rate_pct:realized.length?100*wins/realized.length:0,best_coin:best,worst_coin:worst,open_positions:endSnapshot.open_positions,shadow_only:true,live_execution:false};
}

export function formatTelegramReport(report:HourlyReportPayload):string{const money=(v:number)=>`${v>=0?"+":""}$${v.toFixed(2)}`,best=report.best_coin?`${report.best_coin.symbol} ${money(report.best_coin.net_pnl)}`:"-",worst=report.worst_coin?`${report.worst_coin.symbol} ${money(report.worst_coin.net_pnl)}`:"-";return[`📊 Monster Coins Pro · 1 Saatlik SHADOW Rapor`,`Policy: ${report.policy_kind}`,`Net P&L: ${money(report.net_pnl)} (${report.return_pct>=0?"+":""}${report.return_pct.toFixed(2)}%)`,`Gross: ${money(report.gross_pnl)} · Cost: $${report.trading_cost.toFixed(2)}`,`Aksiyon: ${report.action_count} · Kapanış: ${report.closed_action_count} · Win: ${report.wins}/${report.closed_action_count}`,`Max DD: ${report.max_drawdown_pct.toFixed(2)}%`,`🏆 En iyi: ${best}`,`⚠️ En kötü: ${worst}`,`Açık pozisyon: ${report.open_positions.length}`,`🔒 Gerçek emir kapalı · SHADOW ONLY`].join("\n")}
