// @ts-ignore Supabase Edge remote import
import postgres from 'https://deno.land/x/postgresjs@v3.4.5/mod.js';
declare const Deno: any;

const DB_URL=Deno.env.get('SUPABASE_DB_URL')!;
const ENGINE_ID='dip-multiasset-v1';
const ENGINE_VERSION='V8.5.6';
const POLICY_VERSION='dip-v856-opportunity-scout-20260914.1';
const MAX_SCAN=10;
const MAX_POSITIONS=2;
const FEE_BPS=10;
const HOSTS=['https://api.binance.com','https://api1.binance.com','https://api2.binance.com'];
const EXCLUDED=new Set(['ETHUSDT','USDTUSDT','USDCUSDT','FDUSDUSDT','TUSDUSDT','DAIUSDT','BUSDUSDT','EURUSDT','TRYUSDT','USD1USDT']);

type J=Record<string,unknown>;
type Candidate={symbol:string;radar_score:number;price_change_pct:number;spread_bps:number;quote_volume:number;trades_24h:number;momentum_score:number;volatility_score:number};
type Bar={h:number;l:number;c:number;closeTime:number};
type Market={symbol:string;bid:number;ask:number;mid:number;spreadBps:number;atr:number;atrPct:number;ema8:number;ema21:number;recentLow:number;recentHigh:number;pullbackPct:number;bouncePct:number;lastClose:number;prevClose:number;recovery:boolean;trendOk:boolean};
type Position={symbol:string;entry:number;qty:number;opened_at:string;stop:number;target:number;trail:number|null;max_price:number;cost_basis:number;radar_score:number;estimated_cost_bps:number;policy_version:string;entry_reason:string;entry_style?:string};
type State={engine_id:string;started_at:string;run_until:string;starting_equity:number;cash:number;realized_pnl:number;trade_count:number;win_count:number;loss_count:number;positions:Record<string,Position>;cooldowns:Record<string,any>;last_scan:J;last_eval_minute:string|null;enabled:boolean};
type Eval={ok:boolean;coreOk:boolean;scoutRaw:boolean;score:number;opp:number;cost:number;net:number;reason:string;gates:Record<string,boolean>};

const num=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clip=(v:number,lo=0,hi=1)=>Math.max(lo,Math.min(hi,v));
const iso=()=>new Date().toISOString();
function db(){return postgres(DB_URL,{prepare:false,max:1,idle_timeout:1,connect_timeout:8,max_lifetime:30});}
async function sha256Hex(v:string){const d=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)));return[...d].map(b=>b.toString(16).padStart(2,'0')).join('');}
function same(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function requireCron(sql:any,req:Request){const supplied=(req.headers.get('x-brian-cron-key')||'').trim();if(!supplied)throw Error('UNAUTHORIZED_CRON');const rows=await sql`select cron_key_sha256 from public.brian_dashboard_auth where auth_id='control-v3' limit 1`;const expected=String(rows[0]?.cron_key_sha256||'');if(!expected)throw Error('CRON_AUTH_UNAVAILABLE');if(!same(await sha256Hex(supplied),expected))throw Error('UNAUTHORIZED_CRON');}
async function acquireLease(sql:any){const owner=crypto.randomUUID();const rows=await sql`select * from public.brian_dip_v84_acquire_lease('brian-dip-multiasset-worker-v1',${owner},45)`;return rows[0]?.acquired?{owner,generation:Number(rows[0].lease_generation)}:null;}
async function releaseLease(sql:any,l:any){if(!l)return;try{await sql`select public.brian_dip_v84_release_lease('brian-dip-multiasset-worker-v1',${l.owner},${l.generation})`;}catch{}}
async function marketJson(path:string,timeout=5000){let last='MARKET_UNAVAILABLE';for(const host of HOSTS){try{const r=await fetch(host+path,{headers:{accept:'application/json','user-agent':'Brian-DIP-V856/1.0'},signal:AbortSignal.timeout(timeout)});if(!r.ok){last=`HTTP_${r.status}`;if(r.status===418||r.status===429)break;continue;}return await r.json();}catch(e){last=e instanceof Error?e.message:String(e);}}throw Error(`BINANCE:${last}`);}
function ema(xs:number[],p:number){const k=2/(p+1);let out=xs[0]??0;for(let i=1;i<xs.length;i++)out=xs[i]*k+out*(1-k);return out;}
function atr(b:Bar[],p=14){if(b.length<p+2)return 0;const xs:number[]=[];for(let i=1;i<b.length;i++)xs.push(Math.max(b[i].h-b[i].l,Math.abs(b[i].h-b[i-1].c),Math.abs(b[i].l-b[i-1].c)));return xs.slice(-p).reduce((a,x)=>a+x,0)/p;}
async function loadMarket(symbol:string):Promise<Market>{const [rawBars,rawBook]=await Promise.all([marketJson(`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=1m&limit=70`,4500),marketJson(`/api/v3/ticker/bookTicker?symbol=${encodeURIComponent(symbol)}`,4500)]);if(!Array.isArray(rawBars)||rawBars.length<35)throw Error('INSUFFICIENT_BARS');const now=Date.now(),bars:Bar[]=rawBars.map((x:any)=>({h:num(x[2]),l:num(x[3]),c:num(x[4]),closeTime:num(x[6])})).filter(x=>x.closeTime<now-250).slice(-60);if(bars.length<30)throw Error('INSUFFICIENT_CLOSED_BARS');const book=rawBook as J,bid=num(book.bidPrice),ask=num(book.askPrice);if(!(bid>0&&ask>bid))throw Error('BAD_BOOK');const mid=(bid+ask)/2,spreadBps=(ask-bid)/mid*10000;if(spreadBps>30)throw Error('WIDE_BOOK');const closes=bars.map(x=>x.c),a=atr(bars);if(!(a>0))throw Error('BAD_ATR');const r20=bars.slice(-20),r12=bars.slice(-12),recentHigh=Math.max(...r20.map(x=>x.h)),recentLow=Math.min(...r12.map(x=>x.l)),lastClose=bars.at(-1)!.c,prevClose=bars.at(-2)!.c,e8=ema(closes.slice(-35),8),e21=ema(closes.slice(-45),21),atrPct=a/mid*100;return{symbol,bid,ask,mid,spreadBps,atr:a,atrPct,ema8:e8,ema21:e21,recentLow,recentHigh,pullbackPct:(recentHigh-mid)/recentHigh*100,bouncePct:(mid-recentLow)/recentLow*100,lastClose,prevClose,recovery:mid>=lastClose*.999&&lastClose>=prevClose*.9975,trendOk:e8>=e21*.992};}

function sharedCandidates(payload:any,stale:boolean):Candidate[]{const raw=Array.isArray(payload?.candidates)?payload.candidates:[];return raw.map((v:any)=>({symbol:String(v?.symbol||'').toUpperCase(),radar_score:num(v?.radar_score),price_change_pct:num(v?.price_change_pct),spread_bps:num(v?.spread_bps,999),quote_volume:num(v?.quote_volume),trades_24h:num(v?.trades_24h),momentum_score:num(v?.momentum_score),volatility_score:num(v?.volatility_score)})).filter((r:Candidate)=>/^[A-Z0-9]{2,20}USDT$/.test(r.symbol)&&!EXCLUDED.has(r.symbol)&&r.radar_score>=(stale?.70:.68)&&r.quote_volume>=5_000_000&&r.trades_24h>=20_000&&r.spread_bps<=20&&Math.abs(r.price_change_pct)<=45).sort((a:Candidate,b:Candidate)=>(b.radar_score*.62+b.momentum_score*.22+b.volatility_score*.16)-(a.radar_score*.62+a.momentum_score*.22+a.volatility_score*.16)).slice(0,MAX_SCAN);}
async function liveCandidates():Promise<Candidate[]>{const raw=await marketJson('/api/v3/ticker/24hr',7000);if(!Array.isArray(raw))throw Error('LIVE_RADAR_BAD_PAYLOAD');const out:Candidate[]=raw.map((v:any)=>{const symbol=String(v?.symbol||'').toUpperCase(),last=num(v?.lastPrice),high=num(v?.highPrice),low=num(v?.lowPrice),qv=num(v?.quoteVolume),count=num(v?.count),chg=num(v?.priceChangePercent),range=last>0?(high-low)/last*100:0,liq=clip((Math.log10(Math.max(qv,1))-7)/3),act=clip((Math.log10(Math.max(count,1))-4.2)/2),vol=clip(range/14),dipBias=clip((8-chg)/25);const radar=clip(.56+liq*.18+act*.10+vol*.10+dipBias*.06,.50,.97);return{symbol,radar_score:radar,price_change_pct:chg,spread_bps:0,quote_volume:qv,trades_24h:count,momentum_score:clip((chg+20)/40),volatility_score:vol};}).filter((r:Candidate)=>/^[A-Z0-9]{2,20}USDT$/.test(r.symbol)&&!EXCLUDED.has(r.symbol)&&r.quote_volume>=8_000_000&&r.trades_24h>=25_000&&r.price_change_pct>=-35&&r.price_change_pct<=25&&r.radar_score>=.66).sort((a:Candidate,b:Candidate)=>(b.radar_score*.68+b.volatility_score*.22+clip(-b.price_change_pct/20)*.10)-(a.radar_score*.68+a.volatility_score*.22+clip(-a.price_change_pct/20)*.10)).slice(0,MAX_SCAN);if(!out.length)throw Error('LIVE_RADAR_EMPTY');return out;}
async function loadCandidates(sql:any){let shared:any=null;try{const rows=await sql`select observed_at,candidates from public.brian_universe_snapshots order by observed_at desc limit 1`;shared=rows[0]||null;}catch{}const ageMs=shared?Date.now()-Date.parse(String(shared.observed_at)):Infinity;if(Number.isFinite(ageMs)&&ageMs<=10*60_000){const rows=sharedCandidates(shared.candidates,false);if(rows.length)return{rows,source:'SHARED_RADAR',ageSec:Math.round(ageMs/1000),stale:false,observedAt:String(shared.observed_at)};}try{const rows=await liveCandidates();return{rows,source:'BINANCE_LIVE_FALLBACK',ageSec:0,stale:false,observedAt:iso()};}catch(e){if(shared&&Number.isFinite(ageMs)&&ageMs<6*60*60_000){const rows=sharedCandidates(shared.candidates,true);if(rows.length)return{rows,source:'SHARED_RADAR_STALE_FALLBACK',ageSec:Math.round(ageMs/1000),stale:true,observedAt:String(shared.observed_at)};}throw e;}}

async function loadState(sql:any):Promise<State>{const rows=await sql`select * from public.brian_dip_multiasset_state where engine_id=${ENGINE_ID} limit 1`;if(rows.length)return rows[0] as State;const now=new Date(),until=new Date(now.getTime()+18*3600_000),scan={status:'BOOT',policy_version:POLICY_VERSION,engine_version:ENGINE_VERSION};const out=await sql`insert into public.brian_dip_multiasset_state (engine_id,started_at,run_until,starting_equity,cash,realized_pnl,trade_count,win_count,loss_count,positions,cooldowns,last_scan,last_eval_minute,updated_at,enabled,shadow_only,live_execution) values (${ENGINE_ID},${now},${until},1000,1000,0,0,0,0,${sql.json({})},${sql.json({})},${sql.json(scan)},null,${now},true,true,false) returning *`;return out[0] as State;}
function equity(cash:number,positions:Record<string,Position>,markets:Map<string,Market>){let e=cash;for(const p of Object.values(positions))e+=p.qty*(markets.get(p.symbol)?.bid??p.entry);return e;}
function riskMode(state:State,current:number,radarStale:boolean){const start=Math.max(1,num(state.starting_equity,1000)),dd=(start-current)/start,closed=num(state.win_count)+num(state.loss_count),wr=closed?num(state.win_count)/closed:0,streak=num(state.last_scan?.loss_streak),lastLoss=num(state.last_scan?.last_loss_at);if(dd>=.02||(streak>=3&&Date.now()-lastLoss<45*60_000))return{name:'FROZEN',gross:.0,risk:.0,minScore:.99,minOpp:.99,frozen:true,reason:dd>=.02?'SESSION_DRAWDOWN':'LOSS_STREAK',dd,wr};if(radarStale)return{name:'DEFENSIVE',gross:.025,risk:.0020,minScore:.82,minOpp:.81,frozen:false,reason:'RADAR_STALE_FALLBACK',dd,wr};if(closed<8||wr<.35||num(state.realized_pnl)<-start*.01)return{name:'DEFENSIVE',gross:.03,risk:.0025,minScore:.79,minOpp:.78,frozen:false,reason:'LOW_SAMPLE',dd,wr};if(closed<20)return{name:'COLD',gross:.045,risk:.0035,minScore:.76,minOpp:.75,frozen:false,reason:'CALIBRATING',dd,wr};return{name:'NORMAL',gross:.07,risk:.0045,minScore:.73,minOpp:.73,frozen:false,reason:'WARM',dd,wr};}
function evaluate(c:Candidate,m:Market,mode:any):Eval{const atrBps=m.atrPct*100,slip=Math.max(2,m.spreadBps/2),cost=2*FEE_BPS+m.spreadBps+2*slip,reqPull=Math.max(.50,m.atrPct*.65),reqBounce=Math.max(.15,m.atrPct*.16),struct=Math.max(0,(m.recentHigh-m.ask)/m.ask*10000),quality=clip(.60+(c.radar_score-.68)*.85+clip(c.momentum_score-.50,0,.5)*.25,.56,1),gross=Math.min(struct,atrBps*1.65)*quality,unc=Math.max(7,atrBps*.16,cost*.32),net=gross-cost-unc,score=clip(c.radar_score*.34+clip(m.pullbackPct/Math.max(reqPull*1.7,.65))*.20+clip(m.bouncePct/Math.max(reqBounce*2.6,.26))*.13+(m.recovery?.10:0)+(m.trendOk?.08:0)+clip(net/100)*.15),opp=clip(score*.62+c.radar_score*.22+clip(c.momentum_score)*.08+clip(net/100)*.08),gates={radar:c.radar_score>=(mode.name==='DEFENSIVE'?.76:.73),spread:m.spreadBps<=(mode.name==='DEFENSIVE'?10:14),day_move:Math.abs(c.price_change_pct)<=40,pullback:m.pullbackPct>=reqPull,bounce:m.bouncePct>=reqBounce,recovery:m.recovery,trend:m.trendOk,not_chasing:m.mid<=m.recentHigh*(1-Math.max(.0015,m.atrPct*.10/100)),economics:net>=Math.max(14,cost*.55)&&gross>=cost*1.9};const failed=Object.entries(gates).filter(([,v])=>!v).map(([k])=>k),coreOk=!mode.frozen&&score>=mode.minScore&&opp>=mode.minOpp&&!failed.length;const scoutRaw=!mode.frozen&&failed.length===1&&failed[0]==='economics'&&score>=.80&&opp>=.72&&net>=5&&cost<=40&&gross>=cost*1.25;return{ok:coreOk,coreOk,scoutRaw,score,opp,cost,net,reason:coreOk?'V856_CORE_EDGE':mode.frozen?`RISK_FROZEN_${mode.reason}`:`WAIT_${failed.join('+')||'SCORE'}`,gates};}
async function insertEvent(sql:any,row:any){await sql`insert into public.brian_dip_multiasset_events (engine_id,observed_at,symbol,action,price,qty,notional,pnl,reason,metadata) values (${ENGINE_ID},${new Date(row.observed_at)},${row.symbol},${row.action},${row.price},${row.qty},${row.notional},${row.pnl},${row.reason},${sql.json(row.metadata||{})})`;}

async function run(sql:any){
  const state=await loadState(sql),now=Date.now();
  if(!state.enabled||now>=Date.parse(state.run_until)){const scan={status:'WINDOW_COMPLETE',policy_version:POLICY_VERSION,engine_version:ENGINE_VERSION};await sql`update public.brian_dip_multiasset_state set enabled=false,updated_at=now(),last_scan=${sql.json(scan)} where engine_id=${ENGINE_ID}`;return{status:'WINDOW_COMPLETE',engine_version:ENGINE_VERSION};}
  const radar=await loadCandidates(sql),symbols=[...new Set([...Object.keys(state.positions||{}),...radar.rows.map((x:Candidate)=>x.symbol)])].slice(0,MAX_SCAN+MAX_POSITIONS);
  const pairs=await Promise.all(symbols.map(async s=>{try{return[s,await loadMarket(s)] as const;}catch(e){return[s,{error:e instanceof Error?e.message:String(e)}] as const;}}));
  const markets=new Map<string,Market>(),marketErrors:J={};for(const[s,v]of pairs){if('error'in v)marketErrors[s]=v.error;else markets.set(s,v);}
  const positions={...(state.positions||{})},cooldowns={...(state.cooldowns||{})};let cash=num(state.cash),realized=num(state.realized_pnl),trades=num(state.trade_count),wins=num(state.win_count),losses=num(state.loss_count),lossStreak=num(state.last_scan?.loss_streak),lastLossAt=num(state.last_scan?.last_loss_at);const actions:any[]=[];

  for(const[s,p]of Object.entries(positions)){
    const m=markets.get(s);if(!m)continue;const held=now-Date.parse(p.opened_at),slip=Math.max(2,m.spreadBps/2),cost=num(p.estimated_cost_bps,25);p.max_price=Math.max(num(p.max_price,p.entry),m.bid);const mfe=(p.max_price-p.entry)/p.entry*10000;if(mfe>=Math.max(cost+18,m.atrPct*75)){const floor=p.entry*(1+(cost+10)/10000),candidate=Math.max(floor,m.bid-Math.max(m.atr*.58,p.entry*.0045));p.trail=Math.max(num(p.trail),candidate);}let reason='';if(m.bid<=p.stop)reason='STOP';else if(p.trail&&m.bid<=p.trail)reason='TRAIL';else if(m.bid>=p.target)reason='TARGET';else if(held>9*60_000&&!m.recovery&&m.ema8<m.ema21*.996&&m.bid<p.entry*(1+cost/10000))reason='EDGE_DECAY';else if(held>=45*60_000)reason='MAX_HOLD';if(!reason)continue;const exit=m.bid*(1-slip/10000),gross=p.qty*exit,fee=gross*FEE_BPS/10000,pnl=gross-fee-p.cost_basis;cash+=gross-fee;realized+=pnl;trades++;if(pnl>.01){wins++;lossStreak=0;}else if(pnl<-.01){losses++;lossStreak++;lastLossAt=now;}delete positions[s];cooldowns[s]={until:now+(pnl<0?45:25)*60_000,reason,exit_price:exit,exit_at:now,pnl};const row={observed_at:iso(),symbol:s,action:'SELL',price:exit,qty:p.qty,notional:gross,pnl,reason,metadata:{policy_version:POLICY_VERSION,engine_version:ENGINE_VERSION,risk_engine:'V856_GUARDIAN',entry_style:p.entry_style||'CORE',entry:p.entry,target:p.target,stop:p.stop,trail:p.trail,max_price:p.max_price,estimated_cost_bps:cost,shadow_only:true,live_execution:false}};await insertEvent(sql,row);actions.push(row);
  }

  const mode=riskMode({...state,realized_pnl:realized,win_count:wins,loss_count:losses,last_scan:{...state.last_scan,loss_streak:lossStreak,last_loss_at:lastLossAt}} as State,equity(cash,positions,markets),radar.stale),evals:any[]=[],ready:any[]=[];
  const prevScout=((state.last_scan?.scout_streaks||{}) as Record<string,number>),scoutStreaks:Record<string,number>={};
  for(const c of radar.rows){
    const m=markets.get(c.symbol);if(!m)continue;const ev=evaluate(c,m,mode),open=!!positions[c.symbol],guard:any=cooldowns[c.symbol],blocked=num(guard?.until)>now;
    const streak=ev.scoutRaw?Math.min(3,num(prevScout[c.symbol])+1):0;scoutStreaks[c.symbol]=streak;const scoutReady=ev.scoutRaw&&streak>=2;
    const isReady=!open&&!blocked&&(ev.coreOk||scoutReady),style=ev.coreOk?'CORE':scoutReady?'RECOVERY_SCOUT':'WAIT';
    const reason=open?'POSITION_OPEN':blocked?`COOLDOWN_${String(guard?.reason||'EXIT')}`:ev.coreOk?'V856_CORE_EDGE':scoutReady?'V856_RECOVERY_SCOUT':ev.scoutRaw?'WAIT_SCOUT_CONFIRM':ev.reason;
    const rec={symbol:c.symbol,price:m.mid,radar_score:c.radar_score,signal_score:ev.score,opportunity_score:ev.opp,estimated_cost_bps:ev.cost,forecast_net_bps:ev.net,pullback_pct:m.pullbackPct,bounce_pct:m.bouncePct,spread_bps:m.spreadBps,ready:isReady,entry_style:style,scout_streak:streak,reason,gates:ev.gates,policy_version:POLICY_VERSION,engine_version:ENGINE_VERSION,risk_mode:mode.name};evals.push(rec);if(isReady)ready.push({c,m,ev,style});
  }
  ready.sort((a,b)=>b.ev.opp-a.ev.opp||b.ev.net-a.ev.net);

  for(const x of ready){
    if(mode.frozen||Object.keys(positions).length>=MAX_POSITIONS)break;const scout=x.style==='RECOVERY_SCOUT',scale=scout?.50:1.0,liveEq=Math.max(0,equity(cash,positions,markets)),openGross=Object.values(positions).reduce((s,p)=>s+p.qty*p.entry,0),remaining=Math.max(0,liveEq*mode.gross*MAX_POSITIONS-openGross),riskUsd=liveEq*mode.risk*scale,stopDist=Math.min(x.m.ask*.022,Math.max(x.m.atr*1.25,x.m.ask*.0075)),riskPerDollar=stopDist/x.m.ask+x.ev.cost/10000,budget=Math.min(cash*.92,liveEq*mode.gross*scale,remaining,riskUsd/Math.max(.0001,riskPerDollar));if(budget<20)continue;const slip=Math.max(2,x.m.spreadBps/2),entry=x.m.ask*(1+slip/10000),gross=budget/(1+FEE_BPS/10000),qty=gross/entry,openFee=gross*FEE_BPS/10000,costBasis=gross+openFee;let targetDist=Math.max(x.m.atr*(scout?1.8:1.55),entry*(x.ev.cost*(scout?2.9:2.6)/10000),stopDist*(scout?1.75:1.6));targetDist=Math.min(targetDist,entry*.045);const p:Position={symbol:x.c.symbol,entry,qty,opened_at:iso(),stop:entry-stopDist,target:entry+targetDist,trail:null,max_price:entry,cost_basis:costBasis,radar_score:x.c.radar_score,estimated_cost_bps:x.ev.cost,policy_version:POLICY_VERSION,entry_reason:x.style==='RECOVERY_SCOUT'?'V856_RECOVERY_SCOUT':'V856_CORE_EDGE',entry_style:x.style};positions[x.c.symbol]=p;cash-=costBasis;const row={observed_at:iso(),symbol:x.c.symbol,action:'BUY',price:entry,qty,notional:gross,pnl:null,reason:p.entry_reason,metadata:{policy_version:POLICY_VERSION,engine_version:ENGINE_VERSION,risk_engine:'V856_GUARDIAN',entry_style:x.style,risk_mode:mode.name,position_scale:scale,signal_score:x.ev.score,opportunity_score:x.ev.opp,forecast_net_bps:x.ev.net,estimated_cost_bps:x.ev.cost,target:p.target,stop:p.stop,radar_source:radar.source,shadow_only:true,live_execution:false}};await insertEvent(sql,row);actions.push(row);
  }

  const minute=new Date(Math.floor(now/60000)*60000).toISOString();if(state.last_eval_minute!==minute&&evals.length){for(const e of evals){try{await sql`insert into public.brian_dip_multiasset_evaluations (engine_id,observed_at,symbol,price,radar_score,signal_score,action,reason,metadata) values (${ENGINE_ID},now(),${e.symbol},${e.price},${e.radar_score},${e.signal_score},${e.ready?'READY':'WAIT'},${e.reason},${sql.json(e)})`;}catch{}}}
  const finalEq=equity(cash,positions,markets),scan={status:'RUNNING',policy_version:POLICY_VERSION,engine_version:ENGINE_VERSION,risk_engine:'V856_GUARDIAN',risk_mode:mode.name,risk_reason:mode.reason,drawdown_pct:mode.dd,win_rate:mode.wr,loss_streak:lossStreak,last_loss_at:lastLossAt,radar_source:radar.source,radar_observed_at:radar.observedAt,radar_age_seconds:radar.ageSec,radar_soft_stale:radar.stale,scout_streaks:scoutStreaks,scanned:evals,ranked_ready:ready.slice(0,5).map(x=>({symbol:x.c.symbol,entry_style:x.style,opportunity_score:x.ev.opp,forecast_net_bps:x.ev.net,radar_score:x.c.radar_score})),actions,market_errors:marketErrors,equity:finalEq,position_count:Object.keys(positions).length,max_positions:MAX_POSITIONS,gross_cap_pct:mode.gross,risk_cap_pct:mode.risk,heartbeat_at:iso()};
  await sql`update public.brian_dip_multiasset_state set cash=${cash},realized_pnl=${realized},trade_count=${trades},win_count=${wins},loss_count=${losses},positions=${sql.json(positions)},cooldowns=${sql.json(cooldowns)},last_eval_minute=${new Date(minute)},last_scan=${sql.json(scan)},updated_at=now(),enabled=true,shadow_only=true,live_execution=false where engine_id=${ENGINE_ID}`;
  return{status:'RUNNING',engine_id:ENGINE_ID,engine_version:ENGINE_VERSION,policy_version:POLICY_VERSION,risk_mode:mode.name,risk_reason:mode.reason,radar_source:radar.source,radar_age_seconds:radar.ageSec,equity:finalEq,cash,realized_pnl:realized,trade_count:trades,positions:Object.keys(positions),actions,shadow_only:true,live_execution:false};
}

Deno.serve(async(req:Request)=>{if(req.method!=='POST')return new Response('method',{status:405});const sql=db();let lease:any=null;try{await requireCron(sql,req);lease=await acquireLease(sql);if(!lease)return Response.json({status:'WAIT_LEASE',engine_id:ENGINE_ID,engine_version:ENGINE_VERSION,policy_version:POLICY_VERSION,shadow_only:true,live_execution:false});return Response.json(await run(sql),{headers:{'cache-control':'no-store'}});}catch(e){const message=e instanceof Error?e.message:String(e);try{const rows=await sql`select last_scan from public.brian_dip_multiasset_state where engine_id=${ENGINE_ID} limit 1`;const scan={...((rows[0]?.last_scan||{}) as J),status:'FAILED_CLOSED',error:message,error_at:iso(),policy_version:POLICY_VERSION,engine_version:ENGINE_VERSION,risk_engine:'V856_GUARDIAN'};await sql`update public.brian_dip_multiasset_state set last_scan=${sql.json(scan)},updated_at=now() where engine_id=${ENGINE_ID}`;}catch{}return Response.json({status:'FAILED_CLOSED',engine_id:ENGINE_ID,engine_version:ENGINE_VERSION,policy_version:POLICY_VERSION,error:message,shadow_only:true,live_execution:false},{status:message.includes('UNAUTHORIZED')?401:500});}finally{await releaseLease(sql,lease);try{await sql.end({timeout:1});}catch{}}});
