create table if not exists public.brian_multiasset_instruments (
  asset_id text primary key,
  asset_class text not null,
  provider_symbol text not null,
  themes text[] not null default '{}',
  priority integer not null default 50,
  active boolean not null default true,
  provider text not null default 'yahoo_chart_public',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.brian_multiasset_instruments(asset_id,asset_class,provider_symbol,themes,priority,active)
values
('fx:EURUSD','fx','EURUSD=X',array['MONETARY','FX'],100,true),
('fx:GBPUSD','fx','GBPUSD=X',array['MONETARY','FX'],95,true),
('fx:USDJPY','fx','JPY=X',array['MONETARY','FX','GEOPOLITICAL'],100,true),
('fx:USDCHF','fx','CHF=X',array['MONETARY','FX','GEOPOLITICAL'],85,true),
('index:SP500','index','^GSPC',array['MONETARY','FINANCIAL','GEOPOLITICAL'],100,true),
('index:NASDAQ100','index','^NDX',array['MONETARY','FINANCIAL','AI_TECH'],100,true),
('index:DAX','index','^GDAXI',array['MONETARY','FINANCIAL','GEOPOLITICAL'],95,true),
('commodity:GOLD','commodity','GC=F',array['MONETARY','FINANCIAL','FX','GEOPOLITICAL'],100,true),
('commodity:SILVER','commodity','SI=F',array['MONETARY','FINANCIAL','GEOPOLITICAL'],80,true),
('commodity:WTI','commodity','CL=F',array['ENERGY','GEOPOLITICAL'],100,true),
('commodity:BRENT','commodity','BZ=F',array['ENERGY','GEOPOLITICAL'],100,true),
('commodity:NATGAS','commodity','NG=F',array['ENERGY','GEOPOLITICAL'],85,true),
('equity:NVDA','equity','NVDA',array['AI_TECH'],100,true),
('equity:AAPL','equity','AAPL',array['AI_TECH'],85,true),
('equity:MSFT','equity','MSFT',array['AI_TECH'],95,true),
('equity:META','equity','META',array['AI_TECH'],90,true),
('equity:GOOGL','equity','GOOGL',array['AI_TECH'],90,true),
('equity:AMZN','equity','AMZN',array['AI_TECH'],85,true),
('equity:TSLA','equity','TSLA',array['AI_TECH'],80,true),
('equity:JPM','equity','JPM',array['FINANCIAL'],90,true),
('equity:XOM','equity','XOM',array['ENERGY','GEOPOLITICAL'],90,true),
('equity:CVX','equity','CVX',array['ENERGY','GEOPOLITICAL'],85,true),
('etf:SPY','etf','SPY',array['MONETARY','FINANCIAL','GEOPOLITICAL'],95,true),
('etf:QQQ','etf','QQQ',array['MONETARY','FINANCIAL','AI_TECH'],95,true),
('etf:IWM','etf','IWM',array['MONETARY','FINANCIAL'],80,true),
('etf:TLT','etf','TLT',array['MONETARY','FINANCIAL'],95,true),
('etf:GLD','etf','GLD',array['MONETARY','FINANCIAL','GEOPOLITICAL'],90,true),
('etf:USO','etf','USO',array['ENERGY','GEOPOLITICAL'],85,true),
('etf:XLE','etf','XLE',array['ENERGY','GEOPOLITICAL'],90,true),
('etf:XLF','etf','XLF',array['FINANCIAL','MONETARY'],90,true),
('etf:SMH','etf','SMH',array['AI_TECH'],90,true),
('etf:EWG','etf','EWG',array['MONETARY','FINANCIAL','GEOPOLITICAL'],75,true)
on conflict (asset_id) do update
set asset_class=excluded.asset_class,
    provider_symbol=excluded.provider_symbol,
    themes=excluded.themes,
    priority=excluded.priority,
    active=excluded.active,
    updated_at=now();
