-- Brian Control Center: SHADOW-only mobile control/session/report layer.
-- This does NOT modify Phase 3.7 model weights, thresholds, learning, or exchange execution.

create table if not exists public.brian_dashboard_auth (
  auth_id text primary key check (auth_id = 'control-v1'), dashboard_key_sha256 text not null check (dashboard_key_sha256 ~ '^[0-9a-f]{64}$'), cron_key_sha256 text not null check (cron_key_sha256 ~ '^[0-9a-f]{64}$'), shadow_only boolean not null default true check (shadow_only), live_execution boolean not null default false check (not live_execution), created_at timestamptz not null default now()
);
insert into public.brian_dashboard_auth (auth_id,dashboard_key_sha256,cron_key_sha256,shadow_only,live_execution) values ('control-v1','e09808d662bbb456f53e8c5e697ba65b53c632a1714cf953722ea3972ee0fa07','8c2cf522bc17ffb90dedd123dd0107c3df26fc510f4285716a21b235aa0cbf4f',true,false) on conflict (auth_id) do nothing;

create table if not exists public.brian_dashboard_session_events (
  event_id text primary key, session_id text not null, event_kind text not null check (event_kind in ('START','PAUSE')), requested_at timestamptz not null default now(), starting_equity numeric, policy_scope text, source_experiment_id text not null references public.brian_live_shadow_experiments(experiment_id), requested_by text not null default 'monster-coins-pro-pwa', note text, shadow_only boolean not null default true check (shadow_only), live_execution boolean not null default false check (not live_execution), created_at timestamptz not null default now(),
  constraint brian_dashboard_event_shape check ((event_kind='START' and starting_equity>0 and starting_equity<=1000000 and policy_scope in ('BOTH','NATIVE','PROFIT')) or (event_kind='PAUSE' and starting_equity is null and policy_scope is null))
);
create index if not exists brian_dashboard_session_events_time_idx on public.brian_dashboard_session_events(requested_at desc,event_id desc);
create index if not exists brian_dashboard_session_events_session_idx on public.brian_dashboard_session_events(session_id,requested_at asc);

create table if not exists public.brian_dashboard_hourly_reports (
  report_id text primary key, session_id text not null, policy_kind text not null check (policy_kind in ('NATIVE','PROFIT')), window_start timestamptz not null, window_end timestamptz not null, generated_at timestamptz not null default now(), payload jsonb not null, telegram_attempted boolean not null default false, telegram_sent boolean not null default false, telegram_error text, evidence_class text not null default 'PROSPECTIVE_DEVELOPMENT_SHADOW' check (evidence_class='PROSPECTIVE_DEVELOPMENT_SHADOW'), shadow_only boolean not null default true check (shadow_only), live_execution boolean not null default false check (not live_execution), created_at timestamptz not null default now(), constraint brian_dashboard_report_window check (window_end>window_start), unique(session_id,policy_kind,window_start,window_end)
);
create index if not exists brian_dashboard_hourly_reports_session_time_idx on public.brian_dashboard_hourly_reports(session_id,window_end desc);

alter table public.brian_dashboard_auth enable row level security;alter table public.brian_dashboard_session_events enable row level security;alter table public.brian_dashboard_hourly_reports enable row level security;
revoke all on public.brian_dashboard_auth from anon,authenticated;revoke all on public.brian_dashboard_session_events from anon,authenticated;revoke all on public.brian_dashboard_hourly_reports from anon,authenticated;
revoke update,delete,truncate,references,trigger on public.brian_dashboard_auth from service_role;revoke update,delete,truncate,references,trigger on public.brian_dashboard_session_events from service_role;revoke update,delete,truncate,references,trigger on public.brian_dashboard_hourly_reports from service_role;
grant select on public.brian_dashboard_auth to service_role;grant select,insert on public.brian_dashboard_session_events to service_role;grant select,insert on public.brian_dashboard_hourly_reports to service_role;
drop trigger if exists brian_dashboard_auth_append_only on public.brian_dashboard_auth;create trigger brian_dashboard_auth_append_only before update or delete on public.brian_dashboard_auth for each row execute function public.brian_reject_mutation();
drop trigger if exists brian_dashboard_session_events_append_only on public.brian_dashboard_session_events;create trigger brian_dashboard_session_events_append_only before update or delete on public.brian_dashboard_session_events for each row execute function public.brian_reject_mutation();
drop trigger if exists brian_dashboard_hourly_reports_append_only on public.brian_dashboard_hourly_reports;create trigger brian_dashboard_hourly_reports_append_only before update or delete on public.brian_dashboard_hourly_reports for each row execute function public.brian_reject_mutation();

create or replace function public.brian_dashboard_start_session(p_event_id text,p_session_id text,p_starting_equity numeric,p_policy_scope text,p_source_experiment_id text) returns public.brian_dashboard_session_events language plpgsql security definer set search_path=pg_catalog,public as $$
declare latest public.brian_dashboard_session_events%rowtype;inserted public.brian_dashboard_session_events%rowtype;begin perform pg_advisory_xact_lock(hashtextextended('brian-dashboard-control',0));select * into latest from public.brian_dashboard_session_events order by requested_at desc,event_id desc limit 1;if latest.event_kind='START' then raise exception 'BRIAN_DASHBOARD: an active shadow session already exists';end if;insert into public.brian_dashboard_session_events(event_id,session_id,event_kind,starting_equity,policy_scope,source_experiment_id,shadow_only,live_execution) values(p_event_id,p_session_id,'START',p_starting_equity,p_policy_scope,p_source_experiment_id,true,false) returning * into inserted;return inserted;end;$$;
create or replace function public.brian_dashboard_pause_session(p_event_id text,p_session_id text) returns public.brian_dashboard_session_events language plpgsql security definer set search_path=pg_catalog,public as $$
declare latest public.brian_dashboard_session_events%rowtype;inserted public.brian_dashboard_session_events%rowtype;begin perform pg_advisory_xact_lock(hashtextextended('brian-dashboard-control',0));select * into latest from public.brian_dashboard_session_events order by requested_at desc,event_id desc limit 1;if latest.event_kind is distinct from 'START' or latest.session_id is distinct from p_session_id then raise exception 'BRIAN_DASHBOARD: no matching active shadow session';end if;insert into public.brian_dashboard_session_events(event_id,session_id,event_kind,starting_equity,policy_scope,source_experiment_id,shadow_only,live_execution) values(p_event_id,p_session_id,'PAUSE',null,null,latest.source_experiment_id,true,false) returning * into inserted;return inserted;end;$$;
create or replace function public.brian_dashboard_restart_session(p_pause_event_id text,p_start_event_id text,p_new_session_id text,p_starting_equity numeric,p_policy_scope text,p_source_experiment_id text) returns public.brian_dashboard_session_events language plpgsql security definer set search_path=pg_catalog,public as $$
declare latest public.brian_dashboard_session_events%rowtype;inserted public.brian_dashboard_session_events%rowtype;begin perform pg_advisory_xact_lock(hashtextextended('brian-dashboard-control',0));select * into latest from public.brian_dashboard_session_events order by requested_at desc,event_id desc limit 1;if latest.event_kind='START' then insert into public.brian_dashboard_session_events(event_id,session_id,event_kind,starting_equity,policy_scope,source_experiment_id,note,shadow_only,live_execution) values(p_pause_event_id,latest.session_id,'PAUSE',null,null,latest.source_experiment_id,'atomic restart',true,false);end if;insert into public.brian_dashboard_session_events(event_id,session_id,event_kind,starting_equity,policy_scope,source_experiment_id,note,shadow_only,live_execution) values(p_start_event_id,p_new_session_id,'START',p_starting_equity,p_policy_scope,p_source_experiment_id,'atomic restart',true,false) returning * into inserted;return inserted;end;$$;
revoke all on function public.brian_dashboard_start_session(text,text,numeric,text,text) from public,anon,authenticated;revoke all on function public.brian_dashboard_pause_session(text,text) from public,anon,authenticated;revoke all on function public.brian_dashboard_restart_session(text,text,text,numeric,text,text) from public,anon,authenticated;grant execute on function public.brian_dashboard_start_session(text,text,numeric,text,text) to service_role;grant execute on function public.brian_dashboard_pause_session(text,text) to service_role;grant execute on function public.brian_dashboard_restart_session(text,text,text,numeric,text,text) to service_role;

create or replace function brian_private.schedule_control_center_reports() returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare existing_job bigint;scheduled_job bigint;begin if not exists(select 1 from vault.decrypted_secrets where name='brian_project_url') then raise exception 'BRIAN_RUNTIME: Vault secret brian_project_url is missing';end if;if not exists(select 1 from vault.decrypted_secrets where name='brian_dashboard_cron_key') then raise exception 'BRIAN_RUNTIME: Vault secret brian_dashboard_cron_key is missing';end if;for existing_job in select jobid from cron.job where jobname='brian-control-center-report-5m' loop perform cron.unschedule(existing_job);end loop;scheduled_job:=cron.schedule('brian-control-center-report-5m','*/5 * * * *',$cron$ select net.http_post(url := (select decrypted_secret || '/functions/v1/brian-control-center' from vault.decrypted_secrets where name='brian_project_url' limit 1),headers := jsonb_build_object('Content-Type','application/json','x-brian-cron-key',(select decrypted_secret from vault.decrypted_secrets where name='brian_dashboard_cron_key' limit 1)),body := '{"action":"hourly_report"}'::jsonb); $cron$);return scheduled_job;end;$$;
revoke all on function brian_private.schedule_control_center_reports() from public,anon,authenticated,service_role;grant execute on function brian_private.schedule_control_center_reports() to postgres;
